/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type _ExportActivityStatus = typeof _ExportActivityStatus[keyof typeof _ExportActivityStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _ExportActivityStatus = {
  CLOSED: 'CLOSED',
  FAIL: 'FAIL',
  IN_PROGRESS: 'IN_PROGRESS',
  PASS_TO_BE_START: 'PASS_TO_BE_START',
  TO_BE_REVIEW: 'TO_BE_REVIEW',
} as const;
