/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type _ExportParams = { gteCreateTime?: string; id?: number; isPage?: boolean; lteCreateTime?: string; page?: number; size?: number; terminal?: number; tokenUserCode?: string; tokenUserName?: string };
