/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { ActivityListBossReqActivityStatus } from './activityListBossReqActivityStatus';

/**
 * 活动分页查询
 */
export interface ActivityListBossReq {
  /** 活动编码 */
  activityCode?: string;
  /** 状态,TO_BE_REVIEW:待审核,FAIL:审核驳回,PASS_TO_BE_START:审核通过,待开始,IN_PROGRESS:进行中,CLOSED:结束 */
  activityStatus?: ActivityListBossReqActivityStatus;
  /** 活动标题 */
  activityTitle?: string;
  /** 创建开始时间 */
  gteCreateTime?: string;
  /** id */
  id?: string;
  /** 是否删除（0-否，1-是） */
  isDelete?: number;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 创建结束时间 */
  lteCreateTime?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 页量(默认值:10) */
  size?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
