/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { MoneyRes } from './moneyRes';
import type { ActivitySkuExDtoResActivityRealTimeStatus } from './activitySkuExDtoResActivityRealTimeStatus';
import type { ActivitySkuExDtoResActivityStatus } from './activitySkuExDtoResActivityStatus';

export interface ActivitySkuExDtoRes {
  activityCode?: string;
  activityComments?: string;
  activityPic?: string;
  activityPrice?: MoneyRes;
  /** null,TO_BE_REVIEW:待审核,FAIL:审核驳回,PASS_TO_BE_START:审核通过,待开始,IN_PROGRESS:进行中,CLOSED:结束 */
  activityRealTimeStatus?: ActivitySkuExDtoResActivityRealTimeStatus;
  activitySkuId?: string;
  activityStartStock?: number;
  /** null,TO_BE_REVIEW:待审核,FAIL:审核驳回,PASS_TO_BE_START:审核通过,待开始,IN_PROGRESS:进行中,CLOSED:结束 */
  activityStatus?: ActivitySkuExDtoResActivityStatus;
  activityTitle?: string;
  bottomPrice?: MoneyRes;
  countDownTime?: number;
  createTime?: string;
  endTime?: string;
  endTimeStamp?: number;
  id?: string;
  isDelete?: number;
  isLongAgreement?: boolean;
  longAgreementPrice?: MoneyRes;
  promotionPrice?: MoneyRes;
  salesVolume?: number;
  skuCode: string;
  skuName?: string;
  spuId?: string;
  spuPic?: string;
  startTime?: string;
  /** 单位 */
  unit?: string;
  updateTime?: string;
}
