/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { 营销活动实体 } from './营销活动实体';
import type { 营销活动审核记录实体Res } from './营销活动审核记录实体Res';
import type { ActivitySkuExDto } from './activitySkuExDto';

/**
 * 活动详情结果集
 */
export interface ActivityResp {
  /** 活动 */
  activity?: 营销活动实体;
  /** 活动审核记录 */
  reviewLogs?: 营销活动审核记录实体Res[];
  /** sku列表 */
  skuList?: ActivitySkuExDto[];
}
