/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 活动商品信息搜索
 */
export interface ActivitySpuReq {
  /** 商品名称orSKU编码 */
  spuName?: string;
}
