/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { MoneyRes } from './moneyRes';

/**
 * 活动商品信息
 */
export interface ActivitySpuInfoResp {
  /** 商品名称 */
  name?: string;
  /** 建议售价 */
  promotionPrice?: MoneyRes;
  /** sku编码 */
  skuCode?: string;
  /** 单位 */
  unit?: string;
}
