/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { AfterSalesListQueryRequestAfterSalesStatus } from './afterSalesListQueryRequestAfterSalesStatus';
import type { AfterSalesListQueryRequestAfterSalesType } from './afterSalesListQueryRequestAfterSalesType';
import type { AfterSalesListQueryRequestSelfStatus } from './afterSalesListQueryRequestSelfStatus';

/**
 * 售后分页查询
 */
export interface AfterSalesListQueryRequest {
  /** 售后单编号 */
  afterSalesNo?: string;
  /** 售后状态,WAIT_APPROVED:待审核,APPROVED:审核通过,NO_APPROVED:审核不通过,WAIT_REFUND:待退款,CONFIRM_REFUND:待确认退款,WAIT_PAY:待付款,CONFIRM_PAY:待确认付款,REFUND_ING:退款中,PAY_ING:付款中,REFUND_FAIL:退款失败,PAY_FAIL:付款失败,FINISH:已完成,CANCEL:取消,WAIT_BUYER_SEND:待买家寄回,WAIT_SELLER_PICK:待卖家取货,WAIT_SELLER_REC:待卖家收货 */
  afterSalesStatus?: AfterSalesListQueryRequestAfterSalesStatus;
  /** 售后类型,SEC_SETTLE:二次结算,REFUND:退货(已收货退货),REJECTION:退货(未收货退货) */
  afterSalesType?: AfterSalesListQueryRequestAfterSalesType;
  /** 买家企业名称 */
  buyEnterpriseName?: string;
  /** 买家企业编号 */
  buyEnterpriseNo?: string;
  /** 申请结束时间 */
  endTime?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 订单编号 */
  orderNo?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 申请结束时间 */
  productName?: string;
  /** 是否自营,yes:是,no:否 */
  selfStatus?: AfterSalesListQueryRequestSelfStatus;
  /** 卖家企业编号 */
  sellerEnterpriseNo?: string;
  /** 店铺名称 */
  shopName?: string;
  /** 店铺编码 */
  shopNo?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 申请开始时间 */
  startTime?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
