/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type AfterSalesExportSelfStatus = typeof AfterSalesExportSelfStatus[keyof typeof AfterSalesExportSelfStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AfterSalesExportSelfStatus = {
  no: 'no',
  yes: 'yes',
} as const;
