/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { AfterSalesExportAfterSalesStatus } from './afterSalesExportAfterSalesStatus';
import type { AfterSalesExportAfterSalesType } from './afterSalesExportAfterSalesType';
import type { AfterSalesExportSelfStatus } from './afterSalesExportSelfStatus';

export type AfterSalesExportParams = { afterSalesNo?: string; afterSalesStatus?: AfterSalesExportAfterSalesStatus; afterSalesType?: AfterSalesExportAfterSalesType; buyEnterpriseName?: string; buyEnterpriseNo?: string; endTime?: string; isPage?: boolean; orderNo?: string; page?: number; productName?: string; selfStatus?: AfterSalesExportSelfStatus; sellerEnterpriseNo?: string; shopName?: string; shopNo?: string; size?: number; startTime?: string; tokenUserCode?: string; tokenUserName?: string };
