/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type AfterSalesExport1Params = { commodityCode?: string; disType?: number; gteCreateTime?: string; id?: number; isPage?: boolean; lteCreateTime?: string; name?: string; page?: number; productCategoryName?: string; proprietary?: number; publishStatus?: number; releaseScope?: string; shopId?: number; shopName?: string; size?: number; standardCommodityCode?: string; tokenUserCode?: string; tokenUserName?: string };
