/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type AfterSalesExportAfterSalesStatus = typeof AfterSalesExportAfterSalesStatus[keyof typeof AfterSalesExportAfterSalesStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AfterSalesExportAfterSalesStatus = {
  APPROVED: 'APPROVED',
  CANCEL: 'CANCEL',
  CONFIRM_PAY: 'CONFIRM_PAY',
  CONFIRM_REFUND: 'CONFIRM_REFUND',
  FINISH: 'FINISH',
  NO_APPROVED: 'NO_APPROVED',
  PAY_FAIL: 'PAY_FAIL',
  PAY_ING: 'PAY_ING',
  REFUND_FAIL: 'REFUND_FAIL',
  REFUND_ING: 'REFUND_ING',
  WAIT_APPROVED: 'WAIT_APPROVED',
  WAIT_BUYER_SEND: 'WAIT_BUYER_SEND',
  WAIT_PAY: 'WAIT_PAY',
  WAIT_REFUND: 'WAIT_REFUND',
  WAIT_SELLER_PICK: 'WAIT_SELLER_PICK',
  WAIT_SELLER_REC: 'WAIT_SELLER_REC',
} as const;
