/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * sku表中sp_data数据的组装
 */
export interface AssembleVO {
  /** 输入商品id */
  commodityIds?: string[];
}
