/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { AttriListQueryRequestExcludeCategoryIdAttribute } from './attriListQueryRequestExcludeCategoryIdAttribute';

/**
 * 属性列表分页查询
 */
export interface AttriListQueryRequest {
  /** 属性类目id */
  categoryId?: string;
  /** 是否排除传入的categoryId下面的属性，不传默认不排除,yes:是,no:否 */
  excludeCategoryIdAttribute?: AttriListQueryRequestExcludeCategoryIdAttribute;
  /** 创建开始时间 */
  gteCreateTime?: string;
  /** id */
  id?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 类目和属性的关系0：未解除；1：解除，不填默认查询全部，只有当categoryId字段有值才有效 */
  isRelation?: number;
  /** 创建结束时间 */
  lteCreateTime?: string;
  /** 属性名称 */
  name?: string;
  /** 属性名称或属性id */
  nameOrId?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 属性类型 */
  selectType?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 属性状态；0->正常；1->删除;状态（正常/删除） */
  status?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** 属性的类型；0->规格；1->参数;type字段用于控制其是规格还是参数 */
  type?: string;
}
