/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 是否排除传入的categoryId下面的属性，不传默认不排除,yes:是,no:否
 */
export type AttriListQueryRequestExcludeCategoryIdAttribute = typeof AttriListQueryRequestExcludeCategoryIdAttribute[keyof typeof AttriListQueryRequestExcludeCategoryIdAttribute];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AttriListQueryRequestExcludeCategoryIdAttribute = {
  no: 'no',
  yes: 'yes',
} as const;
