/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 查询通用对象
 */
export interface BasicPageQuery {
  /** 状态 待审核0 审核通过1 审核驳回-1 */
  auditStatus?: number;
  /** 创建日期起 */
  begCreateTime?: string;
  /** 企业名称 */
  comName?: string;
  /** 创建日期止 */
  endCreateTime?: string;
  /** 企业编码 */
  enterpriseNo?: string;
  /** 0表示过期，1表示未过期 */
  expiredStatus?: number;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 页码(默认值:1) */
  page?: number;
  /** 资质编码 */
  qualificationCode?: string;
  /** 资质名称 */
  qualificationName?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 现在时刻 */
  time?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
