/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * null,QZT:企账通,BANK:银行
 */
export type BillReconciliationPayeeAccountType = typeof BillReconciliationPayeeAccountType[keyof typeof BillReconciliationPayeeAccountType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BillReconciliationPayeeAccountType = {
  BANK: 'BANK',
  QZT: 'QZT',
} as const;
