/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 对账类型,FORWARD:正向,REVERSE:逆向
 */
export type BillReconciliationPaymentDirection = typeof BillReconciliationPaymentDirection[keyof typeof BillReconciliationPaymentDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BillReconciliationPaymentDirection = {
  FORWARD: 'FORWARD',
  REVERSE: 'REVERSE',
} as const;
