/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * null,INIT:已创建,WAIT_RECONCILIATION:待对账,SELLER_CONFIRMED_WAIT_BUYER_CONFIRM:卖方已确认待买方确认,BUYER_CONFIRMED_WAIT_SELLER_CONFIRM:买方已确认待卖方确认,DELETED:已删除,REJECTED:驳回,COMPLETED:完成,CLOSED:已关闭
 */
export type BillReconciliationBillReconciliationStatus = typeof BillReconciliationBillReconciliationStatus[keyof typeof BillReconciliationBillReconciliationStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BillReconciliationBillReconciliationStatus = {
  BUYER_CONFIRMED_WAIT_SELLER_CONFIRM: 'BUYER_CONFIRMED_WAIT_SELLER_CONFIRM',
  CLOSED: 'CLOSED',
  COMPLETED: 'COMPLETED',
  DELETED: 'DELETED',
  INIT: 'INIT',
  REJECTED: 'REJECTED',
  SELLER_CONFIRMED_WAIT_BUYER_CONFIRM: 'SELLER_CONFIRMED_WAIT_BUYER_CONFIRM',
  WAIT_RECONCILIATION: 'WAIT_RECONCILIATION',
} as const;
