/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Money } from './money';
import type { BillReconciliationBillReconciliationStatus } from './billReconciliationBillReconciliationStatus';
import type { BillReconciliationContainsLongAgreement } from './billReconciliationContainsLongAgreement';
import type { BillReconciliationInvoiceType } from './billReconciliationInvoiceType';
import type { BillReconciliationPayeeAccountType } from './billReconciliationPayeeAccountType';
import type { BillReconciliationPayerAccountType } from './billReconciliationPayerAccountType';
import type { BillReconciliationPaymentDirection } from './billReconciliationPaymentDirection';
import type { BillReconciliationProductSettleMethod } from './billReconciliationProductSettleMethod';

/**
 * 对账单
 */
export interface BillReconciliation {
  address?: string;
  agreementNo?: string;
  /** 付款金额 */
  amount?: Money;
  bankAccountNo?: string;
  bankName?: string;
  /** 对账单编码 */
  billReconciliationNo?: string;
  /** null,INIT:已创建,WAIT_RECONCILIATION:待对账,SELLER_CONFIRMED_WAIT_BUYER_CONFIRM:卖方已确认待买方确认,BUYER_CONFIRMED_WAIT_SELLER_CONFIRM:买方已确认待卖方确认,DELETED:已删除,REJECTED:驳回,COMPLETED:完成,CLOSED:已关闭 */
  billReconciliationStatus?: BillReconciliationBillReconciliationStatus;
  /** 买家名称 */
  buyerName?: string;
  buyerNo: string;
  comments?: string;
  /** null,yes:是,no:否 */
  containsLongAgreement?: BillReconciliationContainsLongAgreement;
  createTime?: string;
  id?: string;
  invoiceBodyId?: string;
  invoiceHeader?: string;
  /** 发票记录编码 */
  invoiceRecordNo?: string;
  /** null,VAT_ORDINARY:增值税普通发票,VAT_SPECIAL:增值税专用发票 */
  invoiceType?: BillReconciliationInvoiceType;
  mobileNo?: string;
  /** 订单号门,分割 */
  orderNos?: string;
  payeeAccountNo?: string;
  /** null,QZT:企账通,BANK:银行 */
  payeeAccountType?: BillReconciliationPayeeAccountType;
  payeeBankAccountCoreNo?: string;
  payeeBankAccountName?: string;
  payeeBankCardNo?: string;
  payeeBankName?: string;
  payeeName?: string;
  payeeNo: string;
  payerAccountNo?: string;
  /** null,QZT:企账通,BANK:银行 */
  payerAccountType?: BillReconciliationPayerAccountType;
  payerBankAccountCoreNo?: string;
  payerBankAccountName?: string;
  payerBankCardNo?: string;
  payerBankName?: string;
  payerName: string;
  payerNo: string;
  /** 对账类型,FORWARD:正向,REVERSE:逆向 */
  paymentDirection?: BillReconciliationPaymentDirection;
  /** 付款单号 */
  paymentOrderNo?: string;
  /** null,BEFORE_PRODUCT:先货后款,BEFORE_PAY:先款后货 */
  productSettleMethod?: BillReconciliationProductSettleMethod;
  reconciliationFinishTime?: string;
  /** 卖家名称 */
  sellerName?: string;
  sellerNo: string;
  taxNumber?: string;
  unpaidBillNo?: string;
  /** 挂帐单号门,分割 */
  unpaidBillNos?: string;
  updateTime?: string;
}
