/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { BillReconciliationPageQueryRequestSearchEQBillReconciliationStatus } from './billReconciliationPageQueryRequestSearchEQBillReconciliationStatus';
import type { BillReconciliationPageQueryRequestSearchEQPaymentDirection } from './billReconciliationPageQueryRequestSearchEQPaymentDirection';

/**
 * 对账单分页查询
 */
export interface BillReconciliationPageQueryRequest {
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 页码(默认值:1) */
  page?: number;
  /** 对账单号 */
  search_EQ_billReconciliationNo?: string;
  /** 状态,INIT:已创建,WAIT_RECONCILIATION:待对账,SELLER_CONFIRMED_WAIT_BUYER_CONFIRM:卖方已确认待买方确认,BUYER_CONFIRMED_WAIT_SELLER_CONFIRM:买方已确认待卖方确认,DELETED:已删除,REJECTED:驳回,COMPLETED:完成,CLOSED:已关闭 */
  search_EQ_billReconciliationStatus?: BillReconciliationPageQueryRequestSearchEQBillReconciliationStatus;
  /** 订单号 */
  search_EQ_orderNo?: string;
  /** 类型,FORWARD:正向,REVERSE:逆向 */
  search_EQ_paymentDirection?: BillReconciliationPageQueryRequestSearchEQPaymentDirection;
  /** 开始生成时间，请严格按照提供的示例时间格式传入精确到秒！！ */
  search_GTE_createTime?: string;
  /** 付款单号模糊查询 */
  search_LIKE_billReconciliationNo?: string;
  /** 订单号模糊查询 */
  search_LIKE_orderNo?: string;
  /** 挂账单号模糊查 */
  search_LIKE_unpaidBillNo?: string;
  /** 结束生成时间，请严格按照提供的示例时间格式传入精确到秒！！ */
  search_LTE_createTime?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
