/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CommodityCategoryVO } from './commodityCategoryVO';
import type { CategoryDetailVO } from './categoryDetailVO';
import type { CategoryLayoutExtVO } from './categoryLayoutExtVO';

export interface BindCategoryPageVO {
  /** 商品分类 */
  commodityCategorys?: CommodityCategoryVO[];
  /** 首页类目布局详情 */
  details?: CategoryDetailVO[];
  /** 热门分类 */
  homeCategory?: CategoryLayoutExtVO;
}
