/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface BindCommodityRequest {
  /** 选择的商品ID */
  chooseCommodityIds?: string;
  /** 热门分类详情ID */
  detailId?: string;
}
