/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { BuyOrderEnterprisePayVO } from './buyOrderEnterprisePayVO';

export interface BossEnterprisePayVO {
  /** 买家银行信息 */
  buyer?: BuyOrderEnterprisePayVO;
  /** 卖家银行信息 */
  seller?: BuyOrderEnterprisePayVO;
}
