/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface BossCategoryLayoutRequest {
  /** 背景图 */
  background?: string;
  /** ID */
  id?: string;
  remark?: string;
  /** 序号 */
  sequence?: number;
  status: number;
  /** 次标题 */
  subtitle?: string;
  /** 标题 */
  title?: string;
}
