/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Money } from './money';

export interface BuyOrderLogisticsProductVO {
  /** 描述 */
  comments?: string;
  /** 差异金额 */
  diffAmount?: Money;
  /** 差异数量 */
  diffNum?: number;
  /** 差异类型,1->多退，2->少补 */
  diffType?: number;
  /** 记录ID */
  id?: string;
  /** 订单编号 */
  orderNo?: string;
  /** 商品图片 */
  productImg?: string;
  /** 商品名称 */
  productName?: string;
  /** 商品编号 */
  productNo?: string;
  /** 商品数量 */
  productNum?: number;
  /** 商品价格 */
  productPrice?: Money;
  /** 商品规格 */
  productSpec?: string;
  /** 商品剩余数量 */
  productSurplusAmount?: Money;
  /** 商品剩余数量 */
  productSurplusNum?: number;
  /** 商品单位 */
  productUnit?: string;
  /** 商品单价 */
  productUnitPrice?: Money;
  /** 收货金额 */
  recAmount?: Money;
  /** 收货数量 */
  recNum?: number;
  /** 发货数量 */
  sendNum?: number;
}
