/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 发货类型,ONCE:一次性发货,MANY:多次发货
 */
export type BuyOrderLogistSendOrderVOLogisticsSendType = typeof BuyOrderLogistSendOrderVOLogisticsSendType[keyof typeof BuyOrderLogistSendOrderVOLogisticsSendType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderLogistSendOrderVOLogisticsSendType = {
  MANY: 'MANY',
  ONCE: 'ONCE',
} as const;
