/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { BuyOrderProductVOLongAgree } from './buyOrderProductVOLongAgree';
import type { ProductAttrDto } from './productAttrDto';
import type { Money } from './money';
import type { BuyOrderProductVOProductSettleMethod } from './buyOrderProductVOProductSettleMethod';
import type { BuyOrderProductVOSelf } from './buyOrderProductVOSelf';

export interface BuyOrderProductVO {
  /** 描述 */
  comments?: string;
  /** 限制城市 */
  limitCity?: string[];
  /** 是否长协,yes:是,no:否 */
  longAgree?: BuyOrderProductVOLongAgree;
  /** 最大起订 */
  maxVolume?: number;
  /** 最小起订 */
  minVolume?: number;
  /** 订单编号 */
  orderNo?: string;
  /** 商品关键属性 */
  productAttrs?: ProductAttrDto[];
  /** 商品品牌 */
  productBrand?: string;
  /** 商品ID */
  productId?: string;
  /** 商品图片 */
  productImg?: string;
  /** 商品型号 */
  productModel?: string;
  /** 商品名称 */
  productName?: string;
  /** 商品编号 */
  productNo?: string;
  /** 商品数量 */
  productNum?: number;
  /** 商品价格 */
  productPrice?: Money;
  /** 商品结算方式,BEFORE_PRODUCT:先货后款,BEFORE_PAY:先款后货 */
  productSettleMethod?: BuyOrderProductVOProductSettleMethod;
  /** 商品规格 */
  productSpec?: string;
  /** 库存 */
  productStock?: number;
  /** 商品剩余数量 */
  productSurplusNum?: number;
  /** 商品单位 */
  productUnit?: string;
  /** 商品单价 */
  productUnitPrice?: Money;
  /** 发布状态 */
  publishStatus?: number;
  /** 是否自营,yes:是,no:否 */
  self?: BuyOrderProductVOSelf;
  /** 店铺名称 */
  shopName?: string;
  /** 店铺编号 */
  shopNo?: string;
  /** 主订单编号 */
  unionOrderNo?: string;
}
