/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 退单状态,WAIT_APPROVED:待审核,APPROVED:审核通过,NO_APPROVED:审核不通过,WAIT_REFUND:待退款,CONFIRM_REFUND:待确认退款,REFUND_ING:退款中,REFUND_FAIL:退款失败,FINISH:已退单
 */
export type BuyOrderRefundApplyVORefundApplyStatus = typeof BuyOrderRefundApplyVORefundApplyStatus[keyof typeof BuyOrderRefundApplyVORefundApplyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderRefundApplyVORefundApplyStatus = {
  APPROVED: 'APPROVED',
  CONFIRM_REFUND: 'CONFIRM_REFUND',
  FINISH: 'FINISH',
  NO_APPROVED: 'NO_APPROVED',
  REFUND_FAIL: 'REFUND_FAIL',
  REFUND_ING: 'REFUND_ING',
  WAIT_APPROVED: 'WAIT_APPROVED',
  WAIT_REFUND: 'WAIT_REFUND',
} as const;
