/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { BuyOrderLogistSendOrderVOLogisticsSendType } from './buyOrderLogistSendOrderVOLogisticsSendType';
import type { BuyOrderLogisticsProductVO } from './buyOrderLogisticsProductVO';
import type { BuyOrderLogistSendOrderVOReceiveStatus } from './buyOrderLogistSendOrderVOReceiveStatus';

export interface BuyOrderLogistSendOrderVO {
  /** 车牌号码 */
  carNo?: string;
  /** 描述 */
  comments?: string;
  /** 创建时间 */
  createTime?: string;
  /** 收货单号 */
  logistRecNo?: string;
  /** 收货时间 */
  logistRecTime?: string;
  /** 发货单号 */
  logistSendNo?: string;
  /** 物流方CODE */
  logisticsCode?: string;
  /** 物流方名称 */
  logisticsName?: string;
  /** 物流单号 */
  logisticsNo?: string;
  /** 物流签收单凭证 */
  logisticsReceiveVoucher?: string;
  /** 发货类型,ONCE:一次性发货,MANY:多次发货 */
  logisticsSendType?: BuyOrderLogistSendOrderVOLogisticsSendType;
  /** 物流发货单凭证 */
  logisticsSendVoucher?: string;
  /** 订单编号 */
  orderNo?: string;
  /** 发货商品 */
  products?: BuyOrderLogisticsProductVO[];
  /** 收货备注 */
  receiveComment?: string;
  /** 收货状态,WAIT_REC:待收货,REJECT:拒绝收货,RECEIVED:已收货 */
  receiveStatus?: BuyOrderLogistSendOrderVOReceiveStatus;
  /** 收货凭证 */
  receiveVoucher?: string;
  /** 接收人 */
  receiver?: string;
  /** 接收人名称 */
  receiverName?: string;
  /** 拒收时间 */
  rejectDate?: string;
  /** 拒收人ID */
  rejectUserId?: string;
  /** 拒收人姓名 */
  rejectUserName?: string;
  /** 发货备注 */
  sendComment?: string;
  /** 发货时间 */
  sendTime?: string;
  /** 发货凭证 */
  sendVoucher?: string;
  /** 发货人 */
  sender?: string;
  /** 发货人名称 */
  senderName?: string;
  /** 发货人电话 */
  senderPhone?: string;
  /** 更新时间 */
  updateTime?: string;
}
