/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 审核状态,APPROVED:审核通过,NO_APPROVED:审核不通过
 */
export type BuyOrderRefundApplyDetailVOAuditStatus = typeof BuyOrderRefundApplyDetailVOAuditStatus[keyof typeof BuyOrderRefundApplyDetailVOAuditStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderRefundApplyDetailVOAuditStatus = {
  APPROVED: 'APPROVED',
  NO_APPROVED: 'NO_APPROVED',
} as const;
