/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 改价状态,WAIT:待买家确认,FINISH:已确认,REJECT:驳回,DEL:已删除
 */
export type BuyOrderChangePriceQueryInfoVOChangeStatus = typeof BuyOrderChangePriceQueryInfoVOChangeStatus[keyof typeof BuyOrderChangePriceQueryInfoVOChangeStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderChangePriceQueryInfoVOChangeStatus = {
  DEL: 'DEL',
  FINISH: 'FINISH',
  REJECT: 'REJECT',
  WAIT: 'WAIT',
} as const;
