/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 开票状态,UN_INVOICE:未开票,INVOICED:已开票
 */
export type BuyOrderInfoVOInvoiceStatus = typeof BuyOrderInfoVOInvoiceStatus[keyof typeof BuyOrderInfoVOInvoiceStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderInfoVOInvoiceStatus = {
  INVOICED: 'INVOICED',
  UN_INVOICE: 'UN_INVOICE',
} as const;
