/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Money } from './money';

export interface BuyOrderLogistSendProductDetailVO {
  /** 描述 */
  comments?: string;
  /** 差异金额 */
  diffAmount?: Money;
  /** 差异数量 */
  diffNum?: number;
  /** 差异类型 */
  diffType?: number;
  /** 收货单号 */
  logistRecNo?: string;
  /** 发货单号 */
  logistSendNo?: string;
  /** 订单号 */
  orderNo?: string;
  /** 商品图片 */
  productImg?: string;
  /** 商品名称 */
  productName?: string;
  /** 商品编号 */
  productNo?: string;
  /** 商品数量 */
  productNum?: number;
  /** 商品价格 */
  productPrice?: Money;
  /** 商品规格 */
  productSpec?: string;
  /** 商品单价 */
  productUnitPrice?: Money;
  /** 收货金额 */
  recAmount?: Money;
  /** 收货数量 */
  recNum?: number;
  /** 发货金额 */
  sendAmount?: Money;
  /** 发货数量 */
  sendNum?: number;
  /** 剩余金额 */
  surplusAmount?: Money;
  /** 剩余数量 */
  surplusNum?: number;
}
