/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 是否默认地址,yes:是,no:否
 */
export type BuyOrderLogisticsRecInfoVODefaultAddr = typeof BuyOrderLogisticsRecInfoVODefaultAddr[keyof typeof BuyOrderLogisticsRecInfoVODefaultAddr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderLogisticsRecInfoVODefaultAddr = {
  no: 'no',
  yes: 'yes',
} as const;
