/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface BuyOrderAfterSalesLogisticsVO {
  /** 售后申请表id */
  afterSalesApplyId?: string;
  /** 返货车牌号 */
  carNo?: string;
  /** 取货物流公司 */
  piLogistics?: string;
  /** 取货物流录入时间 */
  piLogisticsOptTime?: string;
  /** 取货物流录入人 */
  piLogisticsOptUser?: string;
  /** 取货物流录入人名称 */
  piLogisticsOptUserName?: string;
  /** 取货备注 */
  pickUpComment?: string;
  /** 取货时间 */
  pickUpTime?: string;
  /** 返货物流公司 */
  reLogistics?: string;
  /** 返货备注 */
  reLogisticsComment?: string;
  /** 返货物流单号 */
  reLogisticsNo?: string;
  /** 返货物流录入时间 */
  reLogisticsOptTime?: string;
  /** 返货物流录入人 */
  reLogisticsOptUser?: string;
  /** 返货物流录入人名称 */
  reLogisticsOptUserName?: string;
  /** 返货物流时间 */
  reLogisticsTime?: string;
  /** 返货物流凭证 */
  reLogisticsVoucher?: string;
  /** 签收备注 */
  signComment?: string;
  /** 签收数量 */
  signNum?: number;
  /** 签收操作人 */
  signOptUser?: string;
  /** 签收操作名称 */
  signOptUserName?: string;
  /** 签收时间 */
  signTime?: string;
  /** 签收凭证 */
  signVoucher?: string;
}
