/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 取货方式,SELLER_PICK:卖家上门取货,BUYER_SEND:买家寄给卖家
 */
export type BuyOrderAfterSalesApplyInfoVOPickMethod = typeof BuyOrderAfterSalesApplyInfoVOPickMethod[keyof typeof BuyOrderAfterSalesApplyInfoVOPickMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderAfterSalesApplyInfoVOPickMethod = {
  BUYER_SEND: 'BUYER_SEND',
  SELLER_PICK: 'SELLER_PICK',
} as const;
