/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 订单商品结算方式,BEFORE_PRODUCT:先货后款,BEFORE_PAY:先款后货
 */
export type BuyOrderRefundApplyVOProductSettleMethod = typeof BuyOrderRefundApplyVOProductSettleMethod[keyof typeof BuyOrderRefundApplyVOProductSettleMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderRefundApplyVOProductSettleMethod = {
  BEFORE_PAY: 'BEFORE_PAY',
  BEFORE_PRODUCT: 'BEFORE_PRODUCT',
} as const;
