/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 退款方式,original_road:原路退回,offline_pay:线下支付
 */
export type BuyOrderRefundApplyDetailVORefundMethod = typeof BuyOrderRefundApplyDetailVORefundMethod[keyof typeof BuyOrderRefundApplyDetailVORefundMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderRefundApplyDetailVORefundMethod = {
  offline_pay: 'offline_pay',
  original_road: 'original_road',
} as const;
