/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { BuyOrderAfterSalesApplyInfoVOAfterSalesStatus } from './buyOrderAfterSalesApplyInfoVOAfterSalesStatus';
import type { BuyOrderAfterSalesApplyInfoVOAfterSalesType } from './buyOrderAfterSalesApplyInfoVOAfterSalesType';
import type { Money } from './money';
import type { BuyOrderAfterSalesApplyInfoVOPayScene } from './buyOrderAfterSalesApplyInfoVOPayScene';
import type { BuyOrderAfterSalesApplyInfoVOPickMethod } from './buyOrderAfterSalesApplyInfoVOPickMethod';

/**
 * 订单详情售后实体
 */
export interface BuyOrderAfterSalesApplyInfoVO {
  /** 售后申请时间 */
  afterSalesApplyTime?: string;
  /** 售后申请描述 */
  afterSalesApplyvalue?: string;
  /** 售后单号 */
  afterSalesNo?: string;
  /** 售后状态,WAIT_APPROVED:待审核,APPROVED:审核通过,NO_APPROVED:审核不通过,WAIT_REFUND:待退款,CONFIRM_REFUND:待确认退款,WAIT_PAY:待付款,CONFIRM_PAY:待确认付款,REFUND_ING:退款中,PAY_ING:付款中,REFUND_FAIL:退款失败,PAY_FAIL:付款失败,FINISH:已完成,CANCEL:取消,WAIT_BUYER_SEND:待买家寄回,WAIT_SELLER_PICK:待卖家取货,WAIT_SELLER_REC:待卖家收货 */
  afterSalesStatus?: BuyOrderAfterSalesApplyInfoVOAfterSalesStatus;
  /** 售后类型,SEC_SETTLE:二次结算,REFUND:退货(已收货退货),REJECTION:退货(未收货退货) */
  afterSalesType?: BuyOrderAfterSalesApplyInfoVOAfterSalesType;
  /** 申请人ID */
  applyUserId?: string;
  /** 申请人名称 */
  applyUserName?: string;
  /** 买家企业名称 */
  buyEnterpriseName?: string;
  /** 买家企业id */
  buyEnterpriseNo?: string;
  /** 买家用户id */
  buyUserId?: string;
  /** 买家名称 */
  buyUserName?: string;
  /** 创建时间 */
  createTime?: string;
  /** 差异金额 */
  diffAmount?: Money;
  /** 差异数量 */
  diffNum?: number;
  /** 差异类型 */
  diffType?: number;
  /** 子订单编号 */
  orderNo?: string;
  /** 付款单号 */
  payOrderNo?: string;
  /** 支付方式,ONLINE:线上,OFFLINE:线下 */
  payScene?: BuyOrderAfterSalesApplyInfoVOPayScene;
  /** 取货方式,SELLER_PICK:卖家上门取货,BUYER_SEND:买家寄给卖家 */
  pickMethod?: BuyOrderAfterSalesApplyInfoVOPickMethod;
  /** 商品名称 */
  productName?: string;
  /** 商品编号 */
  productNo?: string;
  /** 退货金额 */
  refundAmount?: Money;
  /** 退货数量 */
  refundNum?: number;
  /** 卖家名称 */
  sellerEnterpriseName?: string;
  /** 卖家用户id */
  sellerEnterpriseNo?: string;
  /** 店铺名称 */
  shopName?: string;
  /** 店铺编码 */
  shopNo?: string;
  /** 主订单编号 */
  unionOrderNo?: string;
  /** 更新时间 */
  updateTime?: string;
}
