/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { BuyOrderRefundApplyDetailVOAuditStatus } from './buyOrderRefundApplyDetailVOAuditStatus';
import type { BuyOrderAccountVO } from './buyOrderAccountVO';
import type { Money } from './money';
import type { BuyOrderRefundApplyDetailVOPayMethod } from './buyOrderRefundApplyDetailVOPayMethod';
import type { BuyOrderRefundPayeeVO } from './buyOrderRefundPayeeVO';
import type { BuyOrderRefundApplyDetailVOProductSettleMethod } from './buyOrderRefundApplyDetailVOProductSettleMethod';
import type { BuyOrderRefundApplyDetailVORefundApplyStatus } from './buyOrderRefundApplyDetailVORefundApplyStatus';
import type { BuyOrderRefundApplyDetailVORefundMethod } from './buyOrderRefundApplyDetailVORefundMethod';
import type { BuyOrderRefundApplyDetailVOSettleStatus } from './buyOrderRefundApplyDetailVOSettleStatus';

/**
 * 退单详情实体
 */
export interface BuyOrderRefundApplyDetailVO {
  /** 申请人用户ID */
  applyUserId?: string;
  /** 申请人用户名称 */
  applyUserName?: string;
  /** 审核描述 */
  auditDesc?: string;
  /** 审核状态,APPROVED:审核通过,NO_APPROVED:审核不通过 */
  auditStatus?: BuyOrderRefundApplyDetailVOAuditStatus;
  /** 审核时间 */
  auditTime?: string;
  /** 审核会员ID */
  auditUserId?: string;
  /** 审核会员名称 */
  auditUserName?: string;
  /** 买家账户信息 */
  buyAccountInfo?: BuyOrderAccountVO;
  /** 买家企业名称 */
  buyEnterpriseName?: string;
  /** 买家企业编号 */
  buyEnterpriseNo?: string;
  /** 订单金额 */
  orderAmount?: Money;
  /** 订单编号 */
  orderNo?: string;
  /** 支付方式,OFFLINE_PAY:线下支付,BALANCE_PAY:余额支付,CREDIT_PAY:授信支付 */
  payMethod?: BuyOrderRefundApplyDetailVOPayMethod;
  /** 买家收款信息 */
  payeeInfo?: BuyOrderRefundPayeeVO;
  /** 商品结算方式,BEFORE_PRODUCT:先货后款,BEFORE_PAY:先款后货 */
  productSettleMethod?: BuyOrderRefundApplyDetailVOProductSettleMethod;
  /** 退款金额 */
  refundAmount?: Money;
  /** 退款申请附图 */
  refundApplyImg?: string[];
  /** 退单状态,WAIT_APPROVED:待审核,APPROVED:审核通过,NO_APPROVED:审核不通过,WAIT_REFUND:待退款,CONFIRM_REFUND:待确认退款,REFUND_ING:退款中,REFUND_FAIL:退款失败,FINISH:已退单 */
  refundApplyStatus?: BuyOrderRefundApplyDetailVORefundApplyStatus;
  /** 退款申请时间 */
  refundApplyTime?: string;
  /** 买家退款确认时间 */
  refundBuyerConfirmTime?: string;
  /** 买家退款确认人用户ID */
  refundConfirmBuyUserId?: string;
  /** 买退款确认人用户名称 */
  refundConfirmBuyUserName?: string;
  /** 退款描述 */
  refundDesc?: string;
  /** 退款完成时间 */
  refundFinishTime?: string;
  /** 退款方式,original_road:原路退回,offline_pay:线下支付 */
  refundMethod?: BuyOrderRefundApplyDetailVORefundMethod;
  /** 退单编号 */
  refundNo?: string;
  /** 卖家退款确执行人ID */
  refundOptSellerUserId?: string;
  /** 卖家退款确执行人名称 */
  refundOptSellerUserName?: string;
  /** 退款原因 */
  refundReason?: string;
  /** 卖家退款操作时间 */
  refundSellerExecTime?: string;
  /** 退款凭证 */
  refundVoucher?: string;
  /** 卖家企业名称 */
  sellerEnterpriseName?: string;
  /** 卖家企业编号 */
  sellerEnterpriseNo?: string;
  /** 结算状态,WAIT:待结算,PART:部分结算,SETTED:已结算,CLOSED:已关闭 */
  settleStatus?: BuyOrderRefundApplyDetailVOSettleStatus;
  /** 结算状态msg */
  settleStatusMsg?: string;
  /** 店铺名称 */
  shopName?: string;
  /** 店铺编号 */
  shopNo?: string;
  /** 主订单编号 */
  unionOrderNo?: string;
}
