/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 售后类型,SEC_SETTLE:二次结算,REFUND:退货(已收货退货),REJECTION:退货(未收货退货)
 */
export type BuyOrderAfterSalesApplyInfoVOAfterSalesType = typeof BuyOrderAfterSalesApplyInfoVOAfterSalesType[keyof typeof BuyOrderAfterSalesApplyInfoVOAfterSalesType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderAfterSalesApplyInfoVOAfterSalesType = {
  REFUND: 'REFUND',
  REJECTION: 'REJECTION',
  SEC_SETTLE: 'SEC_SETTLE',
} as const;
