/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 支付方式,ONLINE:线上,OFFLINE:线下
 */
export type BuyOrderAfterSalesDetailVOPayScene = typeof BuyOrderAfterSalesDetailVOPayScene[keyof typeof BuyOrderAfterSalesDetailVOPayScene];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderAfterSalesDetailVOPayScene = {
  OFFLINE: 'OFFLINE',
  ONLINE: 'ONLINE',
} as const;
