/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { BuyOrderAfterSalesApplyInfoVO } from './buyOrderAfterSalesApplyInfoVO';
import type { BuyOrderChangePriceQueryInfoVO } from './buyOrderChangePriceQueryInfoVO';
import type { InvoiceBodyInfoVO } from './invoiceBodyInfoVO';
import type { BuyOrderInvoiceInfoVO } from './buyOrderInvoiceInfoVO';
import type { BuyOrderLogisticsRecInfoVO } from './buyOrderLogisticsRecInfoVO';
import type { BuyOrderLogisticsSendRecInfoVO } from './buyOrderLogisticsSendRecInfoVO';
import type { BuyOrderInfoVO } from './buyOrderInfoVO';
import type { BuyOrderPayInfoVO } from './buyOrderPayInfoVO';
import type { PaymentRecordInfoVO } from './paymentRecordInfoVO';
import type { BuyOrderProductDto } from './buyOrderProductDto';

export interface BuyOrderBossDetailInfoVO {
  /** 售后记录 */
  buyOrderAfterSalesApplyInfoList?: BuyOrderAfterSalesApplyInfoVO[];
  /** 订单信息 */
  changePriceQueryInfoVO?: BuyOrderChangePriceQueryInfoVO;
  /** 发票主题信息 */
  invoiceBodyInfo?: InvoiceBodyInfoVO;
  /** 订单开票信息 */
  invoiceInfo?: BuyOrderInvoiceInfoVO[];
  /** 订单收货信息 */
  logisticsRecInfo?: BuyOrderLogisticsRecInfoVO;
  /** 订单发货信息 */
  logisticsSendInfo?: BuyOrderLogisticsSendRecInfoVO[];
  /** 订单信息 */
  orderInfo?: BuyOrderInfoVO;
  /** 订单支付信息 */
  payInfos?: BuyOrderPayInfoVO[];
  /** 支付记录 */
  paymentRecordInfoList?: PaymentRecordInfoVO[];
  /** 购买商品详情 */
  products?: BuyOrderProductDto[];
}
