/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { BuyOrderLogistSendProductDetailVO } from './buyOrderLogistSendProductDetailVO';
import type { BuyOrderLogisticsSendRecInfoVOLogisticsSendType } from './buyOrderLogisticsSendRecInfoVOLogisticsSendType';
import type { BuyOrderLogisticsSendRecInfoVOReceiveStatus } from './buyOrderLogisticsSendRecInfoVOReceiveStatus';

/**
 * 订单发货信息实体
 */
export interface BuyOrderLogisticsSendRecInfoVO {
  /** 车牌号 */
  carNo?: string;
  /** 是否有差异 */
  diffStatus?: number;
  /** 收货单号 */
  logistRecNo?: string;
  /** 收货时间 */
  logistRecTime?: string;
  /** 发货单号 */
  logistSendNo?: string;
  /** 发货商品明细 */
  logistSendProductDetail?: BuyOrderLogistSendProductDetailVO[];
  /** 物流方名称 */
  logisticsName?: string;
  /** 物流单号 */
  logisticsNo?: string;
  /** 物流签收单凭证 */
  logisticsReceiveVoucher?: string;
  /** 发货类型,ONCE:一次性发货,MANY:多次发货 */
  logisticsSendType?: BuyOrderLogisticsSendRecInfoVOLogisticsSendType;
  /** 物流发货单凭证 */
  logisticsSendVoucher?: string;
  /** 订单编号 */
  orderNo?: string;
  /** 收货备注 */
  receiveComment?: string;
  /** 收货状态,WAIT_REC:待收货,REJECT:拒绝收货,RECEIVED:已收货 */
  receiveStatus?: BuyOrderLogisticsSendRecInfoVOReceiveStatus;
  /** 收货凭证 */
  receiveVoucher?: string;
  /** 接收人 */
  receiver?: string;
  /** 接收人名称 */
  receiver_name?: string;
  /** 发货备注 */
  sendComment?: string;
  /** 发货时间 */
  sendTime?: string;
  /** 发货凭证 */
  sendVoucher?: string;
  /** 发货人 */
  sender?: string;
  /** 发货人名称 */
  senderName?: string;
  /** 发货人电话 */
  senderPhone?: string;
  /** 更新时间 */
  updateTime?: string;
}
