/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 卖家签章状态,INIT:初始化,NO_SIGN:未签章,SIGN_ING:签章中,SIGND:已签章
 */
export type BuyOrderInfoVOSellerSignStatus = typeof BuyOrderInfoVOSellerSignStatus[keyof typeof BuyOrderInfoVOSellerSignStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderInfoVOSellerSignStatus = {
  INIT: 'INIT',
  NO_SIGN: 'NO_SIGN',
  SIGND: 'SIGND',
  SIGN_ING: 'SIGN_ING',
} as const;
