/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 订单状态,INIT:初始化,WAIT_BUYER_CONFIRM:待买家确认,WAIT_SELLER_CONFIRM:待卖家确认,WAIT_CONFIRM_INVOICING_INFO:待确认开票信息,COMPLETED:已完成,BILL_REJECTED:对账驳回,DELETD:已删除,WAIT_PAY:待支付,PROCESSING:支付中,PAY_PART:部分支付,PAY_FAIL:支付失败,PAID:已支付,WAIT_SELLER_CONFIRM_BILL:待卖家确认对账单,CLOSED:已关闭
 */
export type BuyOrderPayInfoVOOrderStatus = typeof BuyOrderPayInfoVOOrderStatus[keyof typeof BuyOrderPayInfoVOOrderStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderPayInfoVOOrderStatus = {
  BILL_REJECTED: 'BILL_REJECTED',
  CLOSED: 'CLOSED',
  COMPLETED: 'COMPLETED',
  DELETD: 'DELETD',
  INIT: 'INIT',
  PAID: 'PAID',
  PAY_FAIL: 'PAY_FAIL',
  PAY_PART: 'PAY_PART',
  PROCESSING: 'PROCESSING',
  WAIT_BUYER_CONFIRM: 'WAIT_BUYER_CONFIRM',
  WAIT_CONFIRM_INVOICING_INFO: 'WAIT_CONFIRM_INVOICING_INFO',
  WAIT_PAY: 'WAIT_PAY',
  WAIT_SELLER_CONFIRM: 'WAIT_SELLER_CONFIRM',
  WAIT_SELLER_CONFIRM_BILL: 'WAIT_SELLER_CONFIRM_BILL',
} as const;
