/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Money } from './money';
import type { BuyOrderChangePriceQueryDtoVOPriceCalType } from './buyOrderChangePriceQueryDtoVOPriceCalType';

export interface BuyOrderChangePriceQueryDtoVO {
  /** 计算后的小计 */
  calAfterProductPrice?: Money;
  /** 计算后的小计金额增加减少幅度 */
  calAfterProductPriceRange?: Money;
  /** 计算后的单价 */
  calAfterProductUnitPrice?: Money;
  /** 计算值 */
  calValue?: number;
  /** 记录ID */
  id?: string;
  /** 价格计算类型,FIX:固定值改价,RATE:按比例改价 */
  priceCalType?: BuyOrderChangePriceQueryDtoVOPriceCalType;
  /** 商品图片 */
  productImg?: string;
  /** 商品名称 */
  productName?: string;
  /** 商品编号 */
  productNo?: string;
  /** 商品数量 */
  productNum?: number;
  /** 商品小计价格 */
  productPrice?: Money;
  /** 商品单位 */
  productUnit?: string;
  /** 商品单价 */
  productUnitPrice?: Money;
}
