/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 订单账号实体
 */
export interface BuyOrderAccountVO {
  /** 账户名称 */
  accountName?: string;
  /** 开户银行 */
  bank?: string;
  /** 银行账号 */
  bankNo?: string;
}
