/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { BuyOrderAfterSalesPayVOPaymentOrderStatus } from './buyOrderAfterSalesPayVOPaymentOrderStatus';
import type { Money } from './money';

export interface BuyOrderAfterSalesPayVO {
  /** 收款账户名称 */
  payeeAccountName?: string;
  /** 收款银行 */
  payeeBank?: string;
  /** 收款银行账号 */
  payeeBankNo?: string;
  /** 付款账户名称 */
  payerAccountName?: string;
  /** 付款银行 */
  payerBank?: string;
  /** 付款银行账号 */
  payerBankNo?: string;
  /** 付款单状态,INIT:初始化,WAIT_BUYER_CONFIRM:待买家确认,WAIT_SELLER_CONFIRM:待卖家确认,WAIT_CONFIRM_INVOICING_INFO:待确认开票信息,COMPLETED:已完成,BILL_REJECTED:对账驳回,DELETD:已删除,WAIT_PAY:待支付,PROCESSING:支付中,PAY_PART:部分支付,PAY_FAIL:支付失败,PAID:已支付,WAIT_SELLER_CONFIRM_BILL:待卖家确认对账单,CLOSED:已关闭 */
  paymentOrderStatus?: BuyOrderAfterSalesPayVOPaymentOrderStatus;
  /** 交易金额 */
  tradeAmount?: Money;
  /** 交易完成时间 */
  tradeFinishTime?: string;
  /** 交易流水号 */
  tradeNo?: string;
  /** 交易时间 */
  tradeTime?: string;
}
