/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 状态,INIT:初始化,WAIT_CONFIRM:待确认,CONFIRMED:已确认,REJECTED:已驳回,INVOICING:开票中,FAIL:失败,SUCCESS:成功,INVALIDATE:作废,UPLOADED:已上传,CLOSED:已关闭
 */
export type BuyOrderInvoiceInfoVOStatus = typeof BuyOrderInvoiceInfoVOStatus[keyof typeof BuyOrderInvoiceInfoVOStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderInvoiceInfoVOStatus = {
  CLOSED: 'CLOSED',
  CONFIRMED: 'CONFIRMED',
  FAIL: 'FAIL',
  INIT: 'INIT',
  INVALIDATE: 'INVALIDATE',
  INVOICING: 'INVOICING',
  REJECTED: 'REJECTED',
  SUCCESS: 'SUCCESS',
  UPLOADED: 'UPLOADED',
  WAIT_CONFIRM: 'WAIT_CONFIRM',
} as const;
