/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 结算状态,WAIT:待结算,PART:部分结算,SETTED:已结算,CLOSED:已关闭
 */
export type BuyOrderVOSettleStatus = typeof BuyOrderVOSettleStatus[keyof typeof BuyOrderVOSettleStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderVOSettleStatus = {
  CLOSED: 'CLOSED',
  PART: 'PART',
  SETTED: 'SETTED',
  WAIT: 'WAIT',
} as const;
