/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Money } from './money';

export interface BuyOrderRefundPayeeVO {
  /** 收款银行 */
  bank?: string;
  /** 收款账户名称 */
  payeeAccountName?: string;
  /** 收款银行账号 */
  payeeBankNo?: string;
  /** 退款金额 */
  refundAmount?: Money;
  /** 退款完成时间 */
  refundFinishTime?: string;
}
