/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Money } from './money';
import type { BuyOrderChangePriceQueryDtoVO } from './buyOrderChangePriceQueryDtoVO';
import type { BuyOrderChangePriceQueryInfoVOChangeStatus } from './buyOrderChangePriceQueryInfoVOChangeStatus';
import type { BuyOrderChangePriceQueryInfoVOOrderStatus } from './buyOrderChangePriceQueryInfoVOOrderStatus';

export interface BuyOrderChangePriceQueryInfoVO {
  /** 物流费 */
  afterLogistMoney?: Money;
  /** 申请时间 */
  applyTime?: string;
  /** 申请人ID */
  applyUserId?: string;
  /** 申请人名称 */
  applyUserName?: string;
  /** 审核描述 */
  auitDesc?: string;
  /** 审核时间 */
  auitTime?: string;
  /** 审核人userid */
  auitUserId?: string;
  /** 审核人姓名 */
  auitUserName?: string;
  /** 改价备注 */
  changeComment?: string;
  /** 改价记录ID */
  changePriceId?: string;
  /** 改价列表 */
  changePriceList?: BuyOrderChangePriceQueryDtoVO[];
  /** 改价状态,WAIT:待买家确认,FINISH:已确认,REJECT:驳回,DEL:已删除 */
  changeStatus?: BuyOrderChangePriceQueryInfoVOChangeStatus;
  /** 原订单物流费 */
  logistMoney?: Money;
  /** 订单原始金额 */
  orderAmount?: Money;
  /** 订单金额改变幅度 */
  orderAmountChangeRange?: Money;
  /** 订单金额(不包括物流费) */
  orderAmountNotLogist?: Money;
  /** 订单调整后金额 */
  orderChangeAfterAmount?: Money;
  /** 订单状态,INIT:初始化,WAIT_CONTRACT:待签署,WAIT_PAY:待付款,WAIT_CONFIRM_AMOUNT:待确认付款,WAIT_SEND:待发货,PART_ISSUED:部分发货,ISSUED:发货完成,FINISH:已完成,CANCEL:已取消,REFUND_APPLY_ING:退单申请中,REFUND:已退单,REFUND_GOODS_ING:退货申请中,REFUND_PART_GOODS:部分退货,REFUND_GOODS:已退货 */
  orderStatus?: BuyOrderChangePriceQueryInfoVOOrderStatus;
  /** 收货地址 */
  receiveAddr?: string;
}
