/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { BuyOrderProductDtoLongAgree } from './buyOrderProductDtoLongAgree';
import type { ProductAttrDto } from './productAttrDto';
import type { Money } from './money';
import type { BuyOrderProductDtoProductSettleMethod } from './buyOrderProductDtoProductSettleMethod';
import type { BuyOrderProductDtoSelf } from './buyOrderProductDtoSelf';

/**
 * 订单详情商品实体
 */
export interface BuyOrderProductDto {
  /** 活动编码 */
  activityCode?: string;
  /** 长协编号 */
  agreementNo?: string;
  /** 描述 */
  comments?: string;
  /** 删除状态 */
  deleteStatus?: number;
  /** 是否启用 */
  enable?: number;
  /** 可见客户 */
  enterCustomer?: string;
  /** 商品关键属性 */
  limitCity?: string;
  /** 是否长协,yes:是,no:否 */
  longAgree?: BuyOrderProductDtoLongAgree;
  /** 最大起订 */
  maxVolume?: number;
  /** 最小起订 */
  minVolume?: number;
  multiSettleFalg?: boolean;
  /** 订单编号 */
  orderNo?: string;
  /** 商品产地 */
  productArea?: string;
  /** 商品关键属性 */
  productAttrs?: ProductAttrDto[];
  /** 商品品牌 */
  productBrand?: string;
  /** 成本价格 */
  productCostPrice?: Money;
  /** 商品ID */
  productId?: string;
  /** 商品图片 */
  productImg?: string;
  /** 商品型号 */
  productModel?: string;
  /** 商品名称 */
  productName?: string;
  /** 商品编号 */
  productNo?: string;
  /** 商品数量 */
  productNum?: number;
  /** 商品市场价 */
  productOriginalPrice?: Money;
  /** 商品价格 */
  productPrice?: Money;
  /** 商品售价单价 */
  productSalesUnitPrice?: Money;
  /** 商品结算方式,BEFORE_PRODUCT:先货后款,BEFORE_PAY:先款后货 */
  productSettleMethod?: BuyOrderProductDtoProductSettleMethod;
  /** 商品规格 */
  productSpec?: string;
  /** 库存 */
  productStock?: number;
  /** 商品剩余数量 */
  productSurplusNum?: number;
  /** 商品单位 */
  productUnit?: string;
  /** 商品付款单价 */
  productUnitPrice?: Money;
  /** 商品重量 */
  productWeight?: number;
  /** 发布状态 */
  publishStatus?: number;
  /** 询价起订量 */
  quantity?: number;
  /** 询价供应商报价编码 */
  quotatioCode?: string;
  /** 发布范围 */
  releaseScope?: string;
  /** 是否自营,yes:是,no:否 */
  self?: BuyOrderProductDtoSelf;
  sellerEnterpriseNo?: string;
  /** 店铺名称 */
  shopName?: string;
  /** 店铺编号 */
  shopNo?: string;
  /** 主订单编号 */
  unionOrderNo?: string;
}
