/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 售后状态,WAIT_APPROVED:待审核,APPROVED:审核通过,NO_APPROVED:审核不通过,WAIT_REFUND:待退款,CONFIRM_REFUND:待确认退款,WAIT_PAY:待付款,CONFIRM_PAY:待确认付款,REFUND_ING:退款中,PAY_ING:付款中,REFUND_FAIL:退款失败,PAY_FAIL:付款失败,FINISH:已完成,CANCEL:取消,WAIT_BUYER_SEND:待买家寄回,WAIT_SELLER_PICK:待卖家取货,WAIT_SELLER_REC:待卖家收货
 */
export type BuyOrderAfterSalesDetailVOSalesStatus = typeof BuyOrderAfterSalesDetailVOSalesStatus[keyof typeof BuyOrderAfterSalesDetailVOSalesStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderAfterSalesDetailVOSalesStatus = {
  APPROVED: 'APPROVED',
  CANCEL: 'CANCEL',
  CONFIRM_PAY: 'CONFIRM_PAY',
  CONFIRM_REFUND: 'CONFIRM_REFUND',
  FINISH: 'FINISH',
  NO_APPROVED: 'NO_APPROVED',
  PAY_FAIL: 'PAY_FAIL',
  PAY_ING: 'PAY_ING',
  REFUND_FAIL: 'REFUND_FAIL',
  REFUND_ING: 'REFUND_ING',
  WAIT_APPROVED: 'WAIT_APPROVED',
  WAIT_BUYER_SEND: 'WAIT_BUYER_SEND',
  WAIT_PAY: 'WAIT_PAY',
  WAIT_REFUND: 'WAIT_REFUND',
  WAIT_SELLER_PICK: 'WAIT_SELLER_PICK',
  WAIT_SELLER_REC: 'WAIT_SELLER_REC',
} as const;
