/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Money } from './money';
import type { BuyOrderInvoiceInfoVOInvoiceType } from './buyOrderInvoiceInfoVOInvoiceType';
import type { BuyOrderInvoiceInfoVOStatus } from './buyOrderInvoiceInfoVOStatus';

/**
 * 订单详情发票详细实体
 */
export interface BuyOrderInvoiceInfoVO {
  /** 金额 */
  amount?: Money;
  /** 发票主体id */
  buyerInvoiceBodyId?: string;
  /** 备注 */
  comments?: string;
  /** 创建时间 */
  createTime?: string;
  /** 文件名称 */
  invoiceFileName?: string;
  /** 发票抬头 */
  invoiceHeader?: string;
  /** 发票记录编码 */
  invoiceRecordNo?: string;
  /** 发票类型,VAT_ORDINARY:增值税普通发票,VAT_SPECIAL:增值税专用发票 */
  invoiceType?: BuyOrderInvoiceInfoVOInvoiceType;
  /** 文件路径 */
  invoiceUrl?: string;
  /** 付款单号 */
  paymentOrderNo?: string;
  /** 卖家企业名称 */
  sellerEnterpriseName?: string;
  /** 状态,INIT:初始化,WAIT_CONFIRM:待确认,CONFIRMED:已确认,REJECTED:已驳回,INVOICING:开票中,FAIL:失败,SUCCESS:成功,INVALIDATE:作废,UPLOADED:已上传,CLOSED:已关闭 */
  status?: BuyOrderInvoiceInfoVOStatus;
  /** 纳税人识别号 */
  taxNumber?: string;
}
