/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 支付状态,INIT:初始化,PAY_SUCCESS:支付成功,PAY_FAIL:支付失败,REFUND_ING:退款中,REFUND_SUCCESS:退款成功,REFUND_FAIL:退款失败
 */
export type BuyOrderInfoVOPayStatus = typeof BuyOrderInfoVOPayStatus[keyof typeof BuyOrderInfoVOPayStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderInfoVOPayStatus = {
  INIT: 'INIT',
  PAY_FAIL: 'PAY_FAIL',
  PAY_SUCCESS: 'PAY_SUCCESS',
  REFUND_FAIL: 'REFUND_FAIL',
  REFUND_ING: 'REFUND_ING',
  REFUND_SUCCESS: 'REFUND_SUCCESS',
} as const;
