/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 订单卖家类型,SELF:自营订单,SUPPLIER:撮合订单
 */
export type BuyOrderInfoVOSellerType = typeof BuyOrderInfoVOSellerType[keyof typeof BuyOrderInfoVOSellerType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuyOrderInfoVOSellerType = {
  SELF: 'SELF',
  SUPPLIER: 'SUPPLIER',
} as const;
