/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 登录验证码表单模型
 */
export interface CaptchaResponse {
  /** 验证码图片base64串 */
  base64Img?: string;
  /** 验证码标识符 */
  captchaKey?: string;
  /** 验证码过期时间 */
  expire?: number;
}
