/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Money } from './money';

export interface CategoryCommodityVO {
  /** 一级类目编码 */
  categoryId?: string;
  /** 商品编码 */
  commodityCode?: string;
  /** 商品id */
  commodityId?: string;
  /** 创建时间 */
  createTime?: string;
  /** layout_id */
  id?: string;
  /** layout_id */
  layoutId?: string;
  /** 商品名称 */
  name?: string;
  /** 市场价 */
  originalPrice?: Money;
  /** 主图片 */
  pic?: string;
  /** 成本价; */
  price?: Money;
  /** 类目名称 */
  productCategoryName?: string;
  /** 建议售价 */
  promotionPrice?: Money;
  /** 0非自营 1自营 （聚合店铺自营字段到此） */
  proprietary?: number;
  /** 上架状态：0->下架；1->上架；2->待上架；3->违规下架； */
  publishStatus?: number;
  /** 序号 */
  sequence?: number;
  /** 店铺id */
  shopId?: string;
  /** 店铺名称 */
  shopName?: string;
}
