/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CateUpDownMoveReqOperateType } from './cateUpDownMoveReqOperateType';

/**
 * 标准类目上移下移请求实体
 */
export interface CateUpDownMoveReq {
  /** 分类id */
  id?: string;
  /** 操作类型,UP:上移,DOWN:下移 */
  operateType?: CateUpDownMoveReqOperateType;
}
