/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface CategoryLayoutExtVO {
  /** 背景图 */
  background?: string;
  /** 关联类目id，多个类目用","号分割 */
  categoryIds?: string;
  /** 关联类目名称，多个类目用","号分割 */
  categoryNames?: string;
  /** 关联类目名称，多个类目用","号分割 */
  createTime?: string;
  /** ID */
  id?: string;
  /** remark */
  remark?: string;
  /** 序号 */
  sequence?: number;
  /** 状态 1正常0停用 */
  status?: number;
  /** 次标题 */
  subtitle?: string;
  /** 标题 */
  title?: string;
  /** 关联类目名称，多个类目用","号分割 */
  updateTime?: string;
}
