/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface CategoryQualificationResultInfo {
  /** 分类ID */
  categoryId?: string;
  /** 创建时间 */
  createTime?: string;
  id: string;
  /** 资质分类id */
  qualificationCategoryId?: string;
  /** 资质分类编码 */
  qualificationCode?: string;
  /** 资质名称 */
  qualificationName?: string;
  /** 状态 1已关联 0未关联 */
  status?: number;
  /** 更新时间 */
  updateTime?: string;
}
