/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 终端,WECHAT:微信,H5:H5,PC:前端PC,ANDROID:安卓,IOS:苹果,BOSS:管理BOSS,other:其他
 */
export type CategoryFrontQueryTreeRequestTerminal = typeof CategoryFrontQueryTreeRequestTerminal[keyof typeof CategoryFrontQueryTreeRequestTerminal];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryFrontQueryTreeRequestTerminal = {
  ANDROID: 'ANDROID',
  BOSS: 'BOSS',
  H5: 'H5',
  IOS: 'IOS',
  OTHER: 'OTHER',
  PC: 'PC',
  WECHAT: 'WECHAT',
} as const;
