/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface CategoryDetailVO {
  /** 一级类目编码 */
  categoryId?: string;
  /** 一级类目名称 */
  categoryName?: string;
  createTime?: string;
  id?: string;
  /** layout_id */
  layoutId?: string;
  /** 序号 */
  sequence?: number;
  updateTime?: string;
}
