/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 常见问题查询实体
 */
export interface CmsCommonProblemClassifyReq {
  /** 买家、卖家查询类型  buyer_problem、 seller_problem */
  classify?: string;
  /** 创建开始时间 */
  gteCreateTime?: string;
  /** id */
  id?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 问题分类层级  一级：1  二级：2 */
  level?: number;
  /** 创建结束时间 */
  lteCreateTime?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 父ID  二级联动使用 */
  parentId?: number;
  /** 页量(默认值:10) */
  size?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
