/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CmsContentInfoReqType } from './cmsContentInfoReqType';

/**
 * cms树查询请求实体
 */
export interface CmsContentInfoReq {
  /** 创建开始时间 */
  gteCreateTime?: string;
  /** id */
  id?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 创建结束时间 */
  lteCreateTime?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 页量(默认值:10) */
  size?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** 类型,BANNER:banner,BASIC:基础,MALL_MAIN_NAVIGATION:商城主导航,NOTICE:公告,QUICK_START:快速开始,AGREEMENT:协议,COMMON_PROBLEM:常见问题,HOME_PAGE_FOOTER:首页footer,HEADER_NAVIGATION_MENU:页眉导航菜单 */
  type?: CmsContentInfoReqType;
}
