/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CmsMoveUpAndDownReqOperateType } from './cmsMoveUpAndDownReqOperateType';
import type { CmsMoveUpAndDownReqType } from './cmsMoveUpAndDownReqType';

/**
 * cms上移下移请求实体
 */
export interface CmsMoveUpAndDownReq {
  /** id */
  id?: string;
  /** 操作类型,UP:上移,DOWN:下移 */
  operateType?: CmsMoveUpAndDownReqOperateType;
  /** CMS类型,BANNER:banner,BASIC:基础,MALL_MAIN_NAVIGATION:商城主导航,NOTICE:公告,QUICK_START:快速开始,AGREEMENT:协议,COMMON_PROBLEM:常见问题,HOME_PAGE_FOOTER:首页footer,HEADER_NAVIGATION_MENU:页眉导航菜单 */
  type?: CmsMoveUpAndDownReqType;
}
