/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CMSTree配置实体Status } from './cMSTree配置实体Status';
import type { CMSTree配置实体Type } from './cMSTree配置实体Type';

export interface CMSTree配置实体 {
  /** 编码 */
  code?: string;
  /** 备注 */
  comments?: string;
  createTime?: string;
  /** icon图片 */
  icon?: string;
  id?: string;
  /** 跳转类型 0-文章 1-列表 2-链接 */
  jumpType?: number;
  /** 层级 */
  level?: number;
  /** 链接 */
  link?: string;
  /** 名称 */
  name?: string;
  /** 父ID */
  parentId?: string;
  /** 搜索路径 */
  path?: string;
  /** 排序值 */
  sort?: number;
  /** 状态,ENABLE:启用,UNENABLE:停用 */
  status?: CMSTree配置实体Status;
  /** 类型,BANNER:banner,BASIC:基础,MALL_MAIN_NAVIGATION:商城主导航,NOTICE:公告,QUICK_START:快速开始,AGREEMENT:协议,COMMON_PROBLEM:常见问题,HOME_PAGE_FOOTER:首页footer,HEADER_NAVIGATION_MENU:页眉导航菜单 */
  type?: CMSTree配置实体Type;
  updateTime?: string;
}
