/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 状态,ENABLE:启用,UNENABLE:停用
 */
export type Cms内容拓展实体Status = typeof Cms内容拓展实体Status[keyof typeof Cms内容拓展实体Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Cms内容拓展实体Status = {
  ENABLE: 'ENABLE',
  UNENABLE: 'UNENABLE',
} as const;
