/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Cms常见问题拓展属性实体 } from './cms常见问题拓展属性实体';
import type { Cms内容拓展实体Status } from './cms内容拓展实体Status';
import type { Cms内容拓展实体Type } from './cms内容拓展实体Type';

export interface Cms内容拓展实体 {
  /** 操作人 */
  author?: string;
  /** 类型子级分类标识符 */
  classify?: string;
  /** 编码 */
  code?: string;
  /** 备注 */
  comments?: string;
  /** 常见问题拓展属性 */
  commonProblemEx?: Cms常见问题拓展属性实体;
  /** 内容 */
  content?: string;
  createTime?: string;
  /** icon图片 */
  icon?: string;
  id?: string;
  /** 置顶 0-是 1-否 */
  isTop?: number;
  /** 链接 */
  link?: string;
  /** 名称 */
  name?: string;
  /** 图片 */
  pic?: string;
  /** 发布时间 */
  pubDate?: string;
  /** 排序值 */
  sort?: number;
  /** 状态,ENABLE:启用,UNENABLE:停用 */
  status?: Cms内容拓展实体Status;
  /** 终端 0-PC */
  terminal?: number;
  /** 标题 */
  title?: string;
  /** 类型,BANNER:banner,BASIC:基础,MALL_MAIN_NAVIGATION:商城主导航,NOTICE:公告,QUICK_START:快速开始,AGREEMENT:协议,COMMON_PROBLEM:常见问题,HOME_PAGE_FOOTER:首页footer,HEADER_NAVIGATION_MENU:页眉导航菜单 */
  type?: Cms内容拓展实体Type;
  updateTime?: string;
}
