/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * boss端状态参数
 */
export interface CommodityBossStatusVO {
  /** 删除状态：0->删除；1->未删除 */
  deleteStatus?: number;
  /** 商品id集合 */
  ids?: string[];
  /** 违规下架说明 */
  illegalExplain?: string;
  /** 上架状态：0->下架；1->上架；2->待上架；3->违规下架 */
  publishStatus?: number;
}
