/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Commodity } from './commodity';
import type { CommodityAttributeValue } from './commodityAttributeValue';
import type { CommoditySkuStock } from './commoditySkuStock';

/**
 * 审核|查看商品信息
 */
export interface CommodityValueInfoVO {
  /** 商品信息实体 */
  commodity?: Commodity;
  /** 商品属性值集合 */
  commodityAttributeValueInfos?: CommodityAttributeValue[];
  /** 商品sku值集合 */
  skuStockInfoList?: CommoditySkuStock[];
  /** 是否特殊类目 */
  specialCate?: boolean;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
