/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 状态,enable:正常,disable:禁用
 */
export type CommodityCategoryFrontConfigurationFrontCategoryConfigurationStatus = typeof CommodityCategoryFrontConfigurationFrontCategoryConfigurationStatus[keyof typeof CommodityCategoryFrontConfigurationFrontCategoryConfigurationStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommodityCategoryFrontConfigurationFrontCategoryConfigurationStatus = {
  disable: 'disable',
  enable: 'enable',
} as const;
