/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Resource } from './resource';

export interface CommodityCategory {
  backCategory?: string;
  child?: CommodityCategory[];
  childName?: string;
  children?: Resource[];
  createTime?: string;
  description?: string;
  frontCategory?: string;
  grandsonName?: string;
  icon?: string;
  id?: string;
  isStandardCate?: number;
  keywords?: string;
  level?: number;
  name?: string;
  parentId?: string;
  qualificationCategoryName?: string;
  showStatus?: number;
  sort?: number;
  standardCateCode?: string;
  updateTime?: string;
}
