/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { MoneyRes } from './moneyRes';

export interface CommoditySkuStock {
  /** 商家商品sku编码 */
  businessSkuCode?: string;
  /** 商品id */
  commodityId?: string;
  createTime?: string;
  /** 删除状态：0->删除；1->未删除 */
  deleteStatus?: number;
  /** 商品详细属性 */
  dpData?: string;
  id?: string;
  /** 是否启用【0：是；1：不是】 */
  isEnable?: number;
  /** 锁定库存 小数点后最多4位 */
  lockStock?: number;
  /** 预警库存 小数点后最多4位 */
  lowStock?: number;
  /** 厂商 */
  manufacturer?: string;
  /** 市场价 */
  originalPrice?: MoneyRes;
  /** 成本价 */
  price?: MoneyRes;
  /** 建议售价;单品建议价格 */
  promotionPrice?: MoneyRes;
  /** 销售属性 */
  salesAttribute?: string;
  /** sku编码 */
  skuCode?: string;
  /** sku商品名称 */
  skuName?: string;
  /** 库存展示图片 */
  skuPic?: string;
  /** 商品销售属性，json格式 */
  spData?: string;
  /** 库存 小数点后最多4位 */
  stock?: number;
  updateTime?: string;
}
