/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 操作,EDIT:编辑,CREATE:创建,DELETE:删除
 */
export type CommodityCateFrontOperationRequestOperation = typeof CommodityCateFrontOperationRequestOperation[keyof typeof CommodityCateFrontOperationRequestOperation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommodityCateFrontOperationRequestOperation = {
  CREATE: 'CREATE',
  DELETE: 'DELETE',
  EDIT: 'EDIT',
} as const;
