/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CommodityCategoryInfo } from './commodityCategoryInfo';

/**
 * 选中类目树
 */
export interface CommodityCateCheckedTree {
  /** 选中的数据 */
  checkedArrayJson?: string;
  /** 商品分类树 */
  commodityCategoryInfoList?: CommodityCategoryInfo[];
}
