/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CommodityAttributeValueInfo } from './commodityAttributeValueInfo';
import type { MoneyRes } from './moneyRes';
import type { CommoditySkuStockInfoRes } from './commoditySkuStockInfoRes';
import type { CommodityBossCreateVOResTerminal } from './commodityBossCreateVOResTerminal';

/**
 * boss端商品参数
 */
export interface CommodityBossCreateVORes {
  /** 画册图片，连产品图片限制为5张，以逗号分割需要新建表来存储多图 */
  albumPics?: string;
  /** 产地 */
  area?: string;
  /** 提供发票 */
  bill?: string;
  /** 品牌id */
  brandId?: string;
  /** 商品类目id; */
  categoryId?: string;
  /** 商品详细属性|关键属性|销售属性 */
  commodityAttributeValueInfos?: CommodityAttributeValueInfo[];
  /** 商品编码 */
  commodityCode?: string;
  /** 货号 */
  commoditySn?: string;
  /** 商品视频地址存放 */
  commodityVideo?: string;
  /** 交期;工作日当天发货|下单后3-5天发货 */
  deliveryDate?: string;
  /** 发货地 */
  deliveryPlace?: string;
  /** 商品描述 */
  description?: string;
  /** 区分标品与正常商品【0：正常商品；1：标品】 */
  disType?: number;
  /** 下架时间 */
  downTime?: string;
  /** 输入客户 */
  enterCustomer?: string;
  /** 输入客户编码 */
  enterCustomerNo?: string;
  /** 厂家编码 */
  enterpriseNo?: string;
  /** 运费承担方 */
  fareBear?: string;
  /** 前台类目 */
  frontCategory?: string;
  /** 高 */
  height?: number;
  /** 商品id */
  id?: string;
  /** 关键字 */
  keywords?: string;
  /** 上架时间 */
  launchTime?: string;
  /** 长 */
  length?: number;
  /** 限购城市 */
  limitCity?: string;
  /** 单笔最大购买量 */
  maxVolume?: number;
  /** 最小起订量 */
  minVolume?: number;
  /** 商品名称 */
  name?: string;
  /** 市场价 */
  originalPrice?: MoneyRes;
  /** 主图片 */
  pic?: string;
  /** 是否为现货商品：0->不是；1->是 */
  previewStatus?: number;
  /** 成本价;(厂家商品的结算价) */
  price?: MoneyRes;
  /** 商品分类名称 */
  productCategoryName?: string;
  /** 建议售价 */
  promotionPrice?: MoneyRes;
  /** 上架状态：0->下架；1->上架；2->待上架；3->违规下架； */
  publishStatus?: number;
  /** 上架时间 */
  publishTime?: string;
  /** 件装数量文本类型30个字符 */
  quantity?: string;
  /** 发布范围【全平台可见、指定客户可见】 */
  releaseScope?: string;
  /** 结算方式 */
  settlementType?: string;
  /** 下架时间 */
  shelfTime?: string;
  /** 商品店铺id */
  shopId?: string;
  /** 店铺名称 */
  shopName?: string;
  /** 商品的sku信息 */
  skuStockList?: CommoditySkuStockInfoRes[];
  /** 税类编码 */
  taxCategoryCode?: string;
  /** 税类名称 */
  taxCategoryName?: string;
  /** 税率 */
  taxRate?: number;
  /** 录入终端,BOSS:BOSS端,PC:PC端 */
  terminal?: CommodityBossCreateVOResTerminal;
  /** 总库存 */
  totalStock?: number;
  /** 运输方式 */
  transType?: string;
  /** 单位 */
  unit?: string;
  /** 审核状态：0->待审核；1->审核通过；2->审核驳回 */
  verifyStatus?: number;
  /** 商品重量 */
  weight?: number;
  /** 宽 */
  width?: number;
}
