/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface CommodityVertifyLog {
  commodityId?: string;
  createTime?: string;
  id?: string;
  updateTime?: string;
  vertifyAccount?: string;
  vertifyName?: string;
  vertifyRemark?: string;
  vertifyResult?: number;
  vertifyTime?: string;
}
