/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CommodityStandardStockInfoStatus } from './commodityStandardStockInfoStatus';

export interface CommodityStandardStockInfo {
  categoryName?: string;
  commodityId?: string;
  createTime?: string;
  createdBy?: string;
  deleteStatus?: number;
  id: string;
  standardCommodityCode?: string;
  standardCommodityName?: string;
  /** null,0:待审核,1:审核通过,2:审核驳回 */
  status?: CommodityStandardStockInfoStatus;
  updateTime?: string;
}
