/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 录入终端,BOSS:BOSS端,PC:PC端
 */
export type CommodityBossCreateVOReqTerminal = typeof CommodityBossCreateVOReqTerminal[keyof typeof CommodityBossCreateVOReqTerminal];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommodityBossCreateVOReqTerminal = {
  BOSS: 'BOSS',
  PC: 'PC',
} as const;
