/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 商品审核列表分页查询
 */
export interface CommodityVertifyLogQueryRequest {
  /** 商品编码 */
  commodityCode?: string;
  /** 区分标品与正常商品 */
  disType?: number;
  /** 创建开始时间 */
  gteCreateTime?: string;
  /** id */
  id?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 创建结束时间 */
  lteCreateTime?: string;
  /** 商品名称 */
  name?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 类目名称 */
  productCategoryName?: string;
  /** 是否自营【1自营 0非自营】 */
  proprietary?: number;
  /** 状态 */
  publishStatus?: number;
  /** 店铺编码 */
  shopId?: string;
  /** 店铺名称 */
  shopName?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** 审核状态：0->待审核；1->审核通过；2->审核驳回 */
  verifyStatus?: number;
}
