/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CommodityCategoryInfoChecked } from './commodityCategoryInfoChecked';

/**
 * 商品分类表
 */
export interface CommodityCategoryInfo {
  /** 后台类目 */
  backCategory?: string;
  /** 是否勾选-取决于入参是否传入属性id,yes:是,no:否 */
  checked?: CommodityCategoryInfoChecked;
  /** 分类树返回 */
  child?: CommodityCategoryInfo[];
  /** 创建时间 */
  createTime?: string;
  /** 描述 */
  description?: string;
  /** 前台类目 */
  frontCategory?: string;
  /** 图标;PC-前端分类的图标 */
  icon?: string;
  /** 分类ID */
  id?: string;
  /** 是否为末级类目 */
  inTheEnd?: boolean;
  /** 是否标品类目【0：否（默认），1：是】 */
  isStandardCate?: number;
  /** 关键字 */
  keywords?: string;
  /** 分类级别：0->1级；1->2级；2->3级 */
  level?: number;
  /** 名称 */
  name?: string;
  /** 上级分类的编号：0表示一级分类;控制商品分类的层级 */
  parentId?: string;
  /** 资质分类名称 */
  qualificationCategoryName?: string;
  /** 显示状态：0->不显示；1->显示;控制PC前端是否显示 */
  showStatus?: number;
  /** 排序 */
  sort?: number;
  /** 特殊类目 */
  specialCategory?: boolean;
  /** 标品类目代号 */
  standardCateCode?: string;
  /** 更新时间 */
  updateTime?: string;
}
