/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { ActivitySkuExDtoReq } from './activitySkuExDtoReq';
import type { MoneyReq } from './moneyReq';

export interface CommoditySkuStockInfoReq {
  /** 营销活动商品统计集合 */
  activitySkuExDtoList?: ActivitySkuExDtoReq[];
  businessSkuCode?: string;
  commodityId?: string;
  createTime?: string;
  deleteStatus?: number;
  dpData?: string;
  id: string;
  isEnable?: number;
  lockStock?: number;
  longAssociationPrice?: MoneyReq;
  lowStock?: number;
  manufacturer?: string;
  originalPrice?: MoneyReq;
  price?: MoneyReq;
  promotionPrice?: MoneyReq;
  salesAttribute?: string;
  skuCode: string;
  skuName?: string;
  skuPic?: string;
  spData?: string;
  stock?: number;
  updateTime?: string;
  validActivity?: boolean;
}
