/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CommodityAttrComplicatedInfoCategoryAttributeRelationInfoMaps } from './commodityAttrComplicatedInfoCategoryAttributeRelationInfoMaps';
import type { CommodityAttributeConfigurationValue } from './commodityAttributeConfigurationValue';
import type { CommodityAttrComplicatedInfoValueType } from './commodityAttrComplicatedInfoValueType';

/**
 * 类目属性复杂详情数据组装一般用于详情
 */
export interface CommodityAttrComplicatedInfo {
  /** 属性别名 */
  alias?: string;
  /** 属性类目关联关系,末级id为key */
  categoryAttributeRelationInfoMaps?: CommodityAttrComplicatedInfoCategoryAttributeRelationInfoMaps;
  /** 备注 */
  comments?: string;
  /** 属性配置值们 */
  configurationValueList?: CommodityAttributeConfigurationValue[];
  /** 属性配置值的json形式 */
  configurationValues?: string;
  /** 创建时间 */
  createTime?: string;
  /** id */
  id?: string;
  /** 属性可选值的列表 */
  inputList?: string;
  /** 是否自定义【0：不是；1：是】 */
  isCustom?: number;
  /** 是否必填 */
  isRequire?: number;
  /** 属性的名称 */
  name?: string;
  /** 0->唯一；1->单选；2->多选 */
  selectType?: number;
  /** 排序字段 */
  sort?: number;
  /** 状态；0->正常；1->删除; */
  status?: number;
  /** 属性的类型；0->规格（销售属性）；1->参数（详细属性）;2->关键属性 */
  type?: number;
  /** 更新时间 */
  updateTime?: string;
  /** 值类型;【枚举：ENUMERATION;文本：TEXT;数字：NUMBER;日期：DATE】,ENUMERATION:枚举,TEXT:文本,NUMBER:数字,DATE:日期 */
  valueType?: CommodityAttrComplicatedInfoValueType;
}
