/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CommodityCategoryAttributeRelationDto } from './commodityCategoryAttributeRelationDto';

/**
 * 属性类目关联关系,末级id为key
 */
export type CommodityAttrComplicatedInfoCategoryAttributeRelationInfoMaps = {[key: string]: CommodityCategoryAttributeRelationDto[]};
