/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { ActivitySkuExDtoRes } from './activitySkuExDtoRes';
import type { MoneyRes } from './moneyRes';

export interface CommoditySkuStockInfoRes {
  /** 营销活动商品统计集合 */
  activitySkuExDtoList?: ActivitySkuExDtoRes[];
  businessSkuCode?: string;
  commodityId?: string;
  createTime?: string;
  deleteStatus?: number;
  dpData?: string;
  id: string;
  isEnable?: number;
  lockStock?: number;
  longAssociationPrice?: MoneyRes;
  lowStock?: number;
  manufacturer?: string;
  originalPrice?: MoneyRes;
  price?: MoneyRes;
  promotionPrice?: MoneyRes;
  salesAttribute?: string;
  skuCode: string;
  skuName?: string;
  skuPic?: string;
  spData?: string;
  stock?: number;
  updateTime?: string;
  validActivity?: boolean;
}
