/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 类目状态,enable:正常,disable:禁用
 */
export type CommodityCateFrontOperationRequestFrontCategoryStatus = typeof CommodityCateFrontOperationRequestFrontCategoryStatus[keyof typeof CommodityCateFrontOperationRequestFrontCategoryStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommodityCateFrontOperationRequestFrontCategoryStatus = {
  disable: 'disable',
  enable: 'enable',
} as const;
