/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { ActivitySkuExDto } from './activitySkuExDto';
import type { Money } from './money';

export interface CommoditySkuStockInfo {
  /** 营销活动商品统计集合 */
  activitySkuExDtoList?: ActivitySkuExDto[];
  businessSkuCode?: string;
  commodityId?: string;
  createTime?: string;
  deleteStatus?: number;
  dpData?: string;
  id: string;
  isEnable?: number;
  lockStock?: number;
  longAssociationPrice?: Money;
  lowStock?: number;
  manufacturer?: string;
  originalPrice?: Money;
  price?: Money;
  promotionPrice?: Money;
  salesAttribute?: string;
  skuCode: string;
  skuName?: string;
  skuPic?: string;
  spData?: string;
  stock?: number;
  updateTime?: string;
  validActivity?: boolean;
}
