/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 状态,0:待审核,1:审核通过,2:审核驳回
 */
export type CommodityStandardStockVOStatus = typeof CommodityStandardStockVOStatus[keyof typeof CommodityStandardStockVOStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommodityStandardStockVOStatus = {
  NOVERIFY: 'NOVERIFY',
  REJECT: 'REJECT',
  VERIFY: 'VERIFY',
} as const;
