/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CommodityStandardStockStatus } from './commodityStandardStockStatus';

export interface CommodityStandardStock {
  /** 类目名称;归属类目名称（存ID，保持最新名称） */
  categoryName?: string;
  /** 商品id */
  commodityId?: string;
  createTime?: string;
  /** 标品创建人 */
  createdBy?: string;
  /** 删除状态：0->已删除；1->未删除 */
  deleteStatus?: number;
  id?: string;
  /** 标准商品编码;标品编码 */
  standardCommodityCode?: string;
  /** 标准商品名称;标品编码对应的名称 */
  standardCommodityName?: string;
  /** 状态;状态枚举值：  待审核  正常  审核驳回,0:待审核,1:审核通过,2:审核驳回 */
  status?: CommodityStandardStockStatus;
  updateTime?: string;
}
