/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 状态;状态枚举值：  待审核  正常  审核驳回,0:待审核,1:审核通过,2:审核驳回
 */
export type CommodityStandardStockStatus = typeof CommodityStandardStockStatus[keyof typeof CommodityStandardStockStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommodityStandardStockStatus = {
  NOVERIFY: 'NOVERIFY',
  REJECT: 'REJECT',
  VERIFY: 'VERIFY',
} as const;
