/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CommodityStandardStockVOStatus } from './commodityStandardStockVOStatus';

/**
 * 标品列表分页查询实体
 */
export interface CommodityStandardStockVO {
  /** 产地 */
  area?: string;
  /** 类目名称 */
  categoryName?: string;
  /** 商品id */
  commodityId?: string;
  /** 货号 */
  commoditySn?: string;
  /** 标品id */
  commodityStandardStockId?: string;
  /** 创建时间 */
  createTime?: string;
  /** 删除状态 */
  deleteStatus?: number;
  /** 商品分类ID */
  frontCategory?: string;
  /** 创建开始时间 */
  gteCreateTime?: string;
  /** 高 */
  height?: number;
  /** id */
  id?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 关键字 */
  keywords?: string;
  /** 长 */
  length?: number;
  /** 创建结束时间 */
  lteCreateTime?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 商品分类名称 */
  productCategoryName?: string;
  /** 件装数量 */
  quantity?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 标准商品编码 */
  standardCommodityCode?: string;
  /** 标准商品名称 */
  standardCommodityName?: string;
  /** 用于存放标品的属性 */
  standardDpData?: string;
  /** 状态,0:待审核,1:审核通过,2:审核驳回 */
  status?: CommodityStandardStockVOStatus;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** 单位 */
  unit?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 商品重量 */
  weight?: number;
  /** 宽 */
  width?: number;
}
