/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CommodityAttributeConfigurationValue } from './commodityAttributeConfigurationValue';
import type { CommodityAttributeParamValueType } from './commodityAttributeParamValueType';

/**
 * 商品属性参数
 */
export interface CommodityAttributeParam {
  /** 备注 */
  alias?: string;
  /** 备注 */
  comments?: string;
  /** 配置值参数 */
  configurationValueParamsList?: CommodityAttributeConfigurationValue[];
  /** 创建开始时间 */
  gteCreateTime?: string;
  /** 属性id */
  id?: string;
  /** 可选值列表，以逗号隔开 */
  inputList?: string;
  /** 是否自定义【0：不是；1：是】 */
  isCustom?: number;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 属性是否必选；0->不是；1->是 */
  isRequire?: number;
  /** 创建结束时间 */
  lteCreateTime?: string;
  /** 属性名称 */
  name?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 属性选择类型：0->唯一；1->单选；2->多选 */
  selectType?: number;
  /** 页量(默认值:10) */
  size?: number;
  sort?: number;
  status?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** 属性的类型；0->规格[销售属性]；1->参数[详细属性]；2->关键属性 */
  type?: number;
  /** 值类型;【枚举：ENUMERATION;文本：TEXT;数字：NUMBER;日期：DATE】,ENUMERATION:枚举,TEXT:文本,NUMBER:数字,DATE:日期 */
  valueType?: CommodityAttributeParamValueType;
}
