/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CommodityCategoryFrontConfigurationBizType } from './commodityCategoryFrontConfigurationBizType';
import type { CommodityCategoryFrontConfigurationFrontCategoryConfigurationStatus } from './commodityCategoryFrontConfigurationFrontCategoryConfigurationStatus';
import type { CommodityCategoryFrontConfigurationLinkType } from './commodityCategoryFrontConfigurationLinkType';

/**
 * 前端类目配置
 */
export interface CommodityCategoryFrontConfiguration {
  /** 业务数据 */
  bizData?: string;
  /** 业务类型,URL:URL,STANDARD_CATEGORY_ID:标准类目ID,STANDARD_CATEGORY_CODE:标准类目编码,STANDARD_CATEGORY_NAME:标准类目名称,KEYWORD:关键字,OTHER:其他 */
  bizType?: CommodityCategoryFrontConfigurationBizType;
  comments?: string;
  createTime?: string;
  /** 前端类目编码 */
  frontCategoryCode?: string;
  /** 状态,enable:正常,disable:禁用 */
  frontCategoryConfigurationStatus?: CommodityCategoryFrontConfigurationFrontCategoryConfigurationStatus;
  id?: string;
  /** 跳转类型,LINK_URL:跳转链接,SEARCH_KEYWORD:搜索关键字,ASSOCIATED_STANDARD_CATEGORY:关联标准类目 */
  linkType?: CommodityCategoryFrontConfigurationLinkType;
  /** 展示名称 */
  showName?: string;
  /** 排序值 */
  sortTime?: number;
  updateTime?: string;
}
