/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CommodityCategoryFrontConfiguration } from './commodityCategoryFrontConfiguration';
import type { CommodityCategoryFrontFrontCategoryStatus } from './commodityCategoryFrontFrontCategoryStatus';

/**
 * 前端类目
 */
export interface CommodityCategoryFront {
  /** 类目编码 */
  categoryCode?: string;
  /** 树的子节点 */
  children?: CommodityCategoryFront[];
  comments?: string;
  /** 当前节点的类目设置 */
  configurations?: CommodityCategoryFrontConfiguration[];
  createTime?: string;
  /** 类目状态,enable:正常,disable:禁用 */
  frontCategoryStatus?: CommodityCategoryFrontFrontCategoryStatus;
  /** icon */
  icon?: string;
  id?: string;
  /** 节点级别 */
  level?: number;
  /** 类目名称 */
  name?: string;
  /** 上级类目编码 */
  parentId?: string;
  /** 搜索路径 */
  path?: string;
  /** 类目展示名称 */
  showName?: string;
  /** 排序值 */
  sortTime?: number;
  /** 子节点的数量 */
  subCount?: number;
  text?: string;
  /** 树主题 */
  theme?: string;
  updateTime?: string;
}
