/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 标品审核记录列表实体
 */
export interface CommodityStandardVertifyLogVO {
  /** 创建时间 */
  createTime?: string;
  /** 主键id */
  id?: string;
  /** 标品id */
  standardId?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 审核人账号 */
  vertifyAccount?: string;
  /** 审核人名称 */
  vertifyName?: string;
  /** 审核备注 */
  vertifyRemark?: string;
  /** 审核结果 */
  vertifyResult?: string;
  /** 审核时间 */
  vertifyTime?: string;
}
