/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 添加|修改商品分类所需参数
 */
export interface CommodityCategoryParamVO {
  /** 后台类目 */
  backCategory?: string;
  /** 二级名称 */
  childName?: string;
  /** 商品相关筛选属性集合 */
  commodityAttributeIdList?: string[];
  /** 描述 */
  description?: string;
  /** 前台类目 */
  frontCategory?: string;
  /** 三级名称 */
  grandsonName?: string;
  /** 图标 */
  icon?: string;
  /** 分类id */
  id?: string;
  /** 是否；标品类目【0：否（默认），1：是】 */
  isStandardCate?: number;
  /** 关键字 */
  keywords?: string;
  /** 商品分类名称 */
  name?: string;
  /** 父分类id */
  parentId?: string;
  /** 父分类名称 */
  parentName?: string;
  /** 资质分类名称 */
  qualificationCategoryName?: string;
  /** 是否进行显示 */
  showStatus?: number;
  /** 排序 */
  sort?: number;
  /** 标品类目代码 */
  standardCateCode?: string;
}
