/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface CommodityAttributeValueInfo {
  commodityAttributeId?: string;
  commodityId?: string;
  createTime?: string;
  id: string;
  type?: number;
  updateTime?: string;
  value?: string;
}
