/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 商品审核列表实体
 */
export interface CommodityVertifyLogVO {
  /** 商品id */
  commodityId?: string;
  /** 创建时间 */
  createTime?: string;
  /** 创建开始时间 */
  gteCreateTime?: string;
  /** id */
  id?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 创建结束时间 */
  lteCreateTime?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 页量(默认值:10) */
  size?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 审核人账号 */
  vertifyAccount?: string;
  /** 审核人名称 */
  vertifyName?: string;
  /** 审核备注 */
  vertifyRemark?: string;
  /** 审核结果 */
  vertifyResult?: number;
  /** 审核时间 */
  vertifyTime?: string;
}
