/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 移动类型,up:上移,down:下移
 */
export type CommodityCateFrontMoveRequestMoveType = typeof CommodityCateFrontMoveRequestMoveType[keyof typeof CommodityCateFrontMoveRequestMoveType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommodityCateFrontMoveRequestMoveType = {
  down: 'down',
  up: 'up',
} as const;
