/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CommodityAttributeValueInfo } from './commodityAttributeValueInfo';
import type { KapCommodityInfo } from './kapCommodityInfo';
import type { Money } from './money';
import type { CommodityInfoShelfType } from './commodityInfoShelfType';
import type { CommoditySkuStockInfo } from './commoditySkuStockInfo';
import type { CommodityInfoTerminal } from './commodityInfoTerminal';

/**
 * 商品信息
 */
export interface CommodityInfo {
  /** 画册图片，连产品图片限制为5张，以逗号分割 */
  albumPics?: string;
  /** 产地 */
  area?: string;
  /** 后台类目 */
  backCategory?: string;
  /** 提供发票：增值税普通发票|增值税专用发票 */
  bill?: string;
  /** 品牌id */
  brandId?: string;
  /** 品牌名称 */
  brandName?: string;
  /** 商品类目id */
  categoryId?: string;
  /** 渠道商品编码 */
  channelCommodityCode?: string;
  /** 渠道供应商编码;分集成供应商（API）和厂家供应商（登录） */
  channelSupplierCode?: string;
  /** 渠道供应商名称 */
  channelSupplierName?: string;
  /** 商品详细属性和关键属性 */
  commodityAttributeValueInfos?: CommodityAttributeValueInfo[];
  /** 商品编码；区别于货号，前端展示 */
  commodityCode?: string;
  /** 货号 */
  commoditySn?: string;
  /** 商品视频地址存放 */
  commodityVideo?: string;
  /** 创建时间 */
  createTime?: string;
  /** 创建时间 */
  createTimeStr?: string;
  /** 创建人 */
  createdBy?: string;
  /** 价格小数点控制 */
  decimalPointLimit?: number;
  /** 删除状态：0->删除；1->未删除 */
  deleteStatus?: number;
  /** 交期：工作日当天发货|下单后3-5天发货 */
  deliveryDate?: string;
  /** 发货地 */
  deliveryPlace?: string;
  /** 商品描述 */
  description?: string;
  /** 商品详情网页内容 */
  detailHtml?: string;
  disType?: number;
  /** 下架时间 */
  downTime?: string;
  /** 输入客户 */
  enterCustomer?: string;
  /** 输入客户编码 */
  enterCustomerNo?: string;
  /** 运费承担方 */
  fareBear?: string;
  /** 前台类目 */
  frontCategory?: string;
  /** 商品前端展示名 */
  frontName?: string;
  /** 高度 */
  height?: number;
  id?: string;
  illegalExplain?: string;
  /** 是否置顶【0:否;1:是】 */
  isTop?: number;
  itemDownshelfFlag?: string;
  /** 商品PV访问量统计集合[spu级别的统计] */
  kapCommodityInfo?: KapCommodityInfo;
  /** 商品PV访问量统计集合[sku级别的统计] */
  kapCommodityInfoList?: KapCommodityInfo[];
  /** 关键字 */
  keywords?: string;
  /** 上架时间 */
  launchTime?: string;
  /** 上架时间 */
  launchTimeStr?: string;
  /** 长度 */
  length?: number;
  /** 限购城市 */
  limitCity?: string;
  /** 是否为长协商品:0->不是；1->是 */
  longAssociation?: number;
  /** 库存预警值 */
  lowStock?: number;
  /** 厂商 */
  manufacturer?: string;
  /** 单笔最大购买量 */
  maxVolume?: number;
  /** 最小起订量 */
  minVolume?: number;
  /** 商品名称 */
  name?: string;
  /** 市场价 */
  originalPrice?: Money;
  /** 主图片 */
  pic?: string;
  /** 是否为现货商品：0->不是；1->是 */
  previewStatus?: number;
  /** 成本价 */
  price?: Money;
  /** 商品分类名称 */
  productCategoryName?: string;
  /** 建议售价 */
  promotionPrice?: Money;
  /** 聚合店铺自营字段 1自营 0非自营 */
  proprietary?: number;
  /** 上架状态：0->下架；1->上架；2->待上架；3->违规下架； */
  publishStatus?: number;
  /** 上架时间 */
  publishTime?: string;
  /** 定时上架时间 */
  publishTimeStr?: string;
  /** 件装数量 */
  quantity?: string;
  /** 发布范围【全平台可见、指定客户可见】 */
  releaseScope?: string;
  /** 销量 */
  saleVolume?: number;
  sequence?: number;
  /** 结算方式：0->先货后款；1->先款后货； */
  settlementType?: string;
  /** 下架时间 */
  shelfTime?: string;
  /** 下架时间 */
  shelfTimeStr?: string;
  /** 商品下架类型,0:手动下架,1:到达预设时间自动下架,2:超过阈值自动下架,3:违规下架,4:店铺禁用下架,5:空值 */
  shelfType?: CommodityInfoShelfType;
  /** 商品店铺id */
  shopId?: string;
  /** 店铺名称 */
  shopName?: string;
  /** 商品的sku库存信息,businessSkuCode:商家商品sku编码 */
  skuStockList?: CommoditySkuStockInfo[];
  /** 排序字段;主要用户与boss后端 */
  sort?: number;
  /** 商品类目spuCode */
  spuCode?: string;
  standardCommodityCode?: string;
  standardDpData?: string;
  /** 库存 */
  stock?: number;
  /** 总库存 */
  stockStr?: string;
  /** 税类编码 */
  taxCategoryCode?: string;
  /** 税类名称 */
  taxCategoryName?: string;
  /** 税率 */
  taxRate?: number;
  /** 录入终端,BOSS:BOSS端,PC:PC端 */
  terminal?: CommodityInfoTerminal;
  /** 精确到sku编码统计的总PV */
  totalPv?: number;
  /** 总库存 */
  totalStock?: string;
  /** 运输方式 */
  transType?: string;
  /** 单位 */
  unit?: string;
  /** 更新时间 */
  updateTime?: string;
  verifyRejectReason?: string;
  /** 审核状态：0->待审核；1->审核通过；2->审核驳回 */
  verifyStatus?: number;
  /** 商品重量 */
  weight?: number;
  /** 宽度 */
  width?: number;
}
