/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CommodityAttrInfoVOValueType } from './commodityAttrInfoVOValueType';

/**
 * 商品属性参数单独封装
 */
export interface CommodityAttrInfoVO {
  /** 属性别名 */
  alias?: string;
  /** 商品属性ID */
  attrId?: string;
  /** 属性值列表 */
  attrList?: string;
  /** 属性名称 */
  attrName?: string;
  /** 属性状态 */
  attrStatus?: string;
  /** 属性类型 */
  attrType?: string;
  /** 商品分类ID */
  categoryId?: string;
  /** 备注 */
  comments?: string;
  /** 创建时间 */
  createTime?: string;
  /** 是否自定义【0：不是；1：是】 */
  isCustom?: number;
  /** 类目是否关联属性 */
  isRelation?: number;
  /** 是否必填 */
  isRequire?: number;
  /** 属性选择类型：0->唯一；1->单选；2->多选 */
  selectType?: number;
  /** 更新时间 */
  updateTime?: string;
  /** 值类型;【枚举：ENUMERATION;文本：TEXT;数字：NUMBER;日期：DATE】,ENUMERATION:枚举,TEXT:文本,NUMBER:数字,DATE:日期 */
  valueType?: CommodityAttrInfoVOValueType;
}
