/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Money } from './money';

/**
 * 商品货物管理分页查询
 */
export interface CommodityCargoDto {
  /** 商品类目id */
  categoryId?: string;
  /** 商品编码 */
  commodityCode?: string;
  /** 创建时间 */
  createTime?: string;
  /** id */
  id?: string;
  /** 上架时间 */
  launchTime?: string;
  /** 市场价 */
  originalPrice?: Money;
  /** 主图片 */
  pic?: string;
  /** 成本价 */
  price?: Money;
  /** 商品分类名称 */
  productCategoryName?: string;
  /** 售价 */
  promotionPrice?: Money;
  /** 非自营|自营 */
  proprietary?: number;
  /** 上下架状态 */
  publishStatus?: number;
  /** 定时上架时间 */
  publishTime?: string;
  /** 商品店铺id */
  shopId?: string;
  /** 店铺名称 */
  shopName?: string;
  /** sku编码 */
  skuCode?: string;
  /** sku商品名称 */
  skuName?: string;
  /** 库存 */
  stock?: number;
  /** 更新时间 */
  updateTime?: string;
}
