/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 供应商直接商品copy
 */
export interface CopyCommodityVO {
  /** 输入店铺id */
  inputShopId?: string;
  /** 输出店铺id */
  outPutShopId?: string;
}
