/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type DetailSysOrganizationParams = { id: number; tokenUserCode?: string; tokenUserName?: string };
