/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 动态查询对象模型
 */
export interface DynamicQuerySqlDto {
  /** 表别名(默认取base,优先级高于默认,传取此;存在多表情况自行传入) */
  alias?: string;
  /** 字段说明注释 */
  columnComment?: string;
  /** 控件字段属性(表对应驼峰规范) */
  columnDefine: string;
  /** 控件字段类型 */
  columnType: string;
  /** 条件{字典配置(code=compent_arithmetic)} */
  conditions?: string;
  /** 字段字典 */
  dataSource?: string;
  /** 值 */
  defaultValue?: string;
  /** 条件连接符{and|or},字典code=compent_and_or,默认and */
  logic?: string;
}
