/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { EnterpriseDtoAccountBossStatus } from './enterpriseDtoAccountBossStatus';
import type { EnterpriseDtoAccountRegType } from './enterpriseDtoAccountRegType';
import type { EnterpriseDtoAccountStatus } from './enterpriseDtoAccountStatus';
import type { EnterpriseDtoBankStatus } from './enterpriseDtoBankStatus';
import type { EnterprisePersonDto } from './enterprisePersonDto';
import type { EnterpriseDtoBenefitIsLegal } from './enterpriseDtoBenefitIsLegal';
import type { EnterpriseDtoBossStatus } from './enterpriseDtoBossStatus';
import type { EnterpriseDtoChannelType } from './enterpriseDtoChannelType';
import type { EnterpriseDtoContractStatus } from './enterpriseDtoContractStatus';
import type { Money } from './money';
import type { EnterpriseDtoDisable } from './enterpriseDtoDisable';
import type { EnterpriseDtoHandlerIsLegal } from './enterpriseDtoHandlerIsLegal';
import type { EnterpriseDtoHoldingIsLegal } from './enterpriseDtoHoldingIsLegal';
import type { EnterpriseDtoIsModify } from './enterpriseDtoIsModify';
import type { EnterpriseDtoPayMethodListItem } from './enterpriseDtoPayMethodListItem';
import type { EnterpriseDtoSelf } from './enterpriseDtoSelf';
import type { EnterpriseDtoSignStatus } from './enterpriseDtoSignStatus';
import type { EnterpriseDtoType } from './enterpriseDtoType';
import type { EnterpriseDtoWhetherInternal } from './enterpriseDtoWhetherInternal';

/**
 * 企业信息
 */
export interface EnterpriseDto {
  /** BOOS企账通审核原因 */
  accountBossReason?: string;
  /** BOOS企账通审核状态,success:成功,failure:失败,processing:处理中 */
  accountBossStatus?: EnterpriseDtoAccountBossStatus;
  /** 企账通审核原因 */
  accountReason?: string;
  /** 企账通注册类型,buyer_reg:企业注册企账通,seller_reg:供应商注册并开通企账通 */
  accountRegType?: EnterpriseDtoAccountRegType;
  /** 企账通审核状态,success:成功,failure:失败,processing:处理中 */
  accountStatus?: EnterpriseDtoAccountStatus;
  /** 企业对公账户 */
  bankCardNo?: string;
  /** 银行编码 */
  bankCode?: string;
  /** 银行审核原因 */
  bankReason?: string;
  /** 银行审核状态,success:成功,failure:失败,processing:处理中 */
  bankStatus?: EnterpriseDtoBankStatus;
  /** 银行联行号 */
  bankUnitNo?: string;
  /** 受益人信息 */
  benefitInfo?: EnterprisePersonDto;
  /** 受益人信息是否为法人,yes:是,no:否 */
  benefitIsLegal?: EnterpriseDtoBenefitIsLegal;
  /** BOSS名称 */
  bossName?: string;
  /** BOSS编号 */
  bossNo?: string;
  /** BOSS审核原因 */
  bossReason?: string;
  /** BOSS审核状态,success:成功,failure:失败,processing:处理中 */
  bossStatus?: EnterpriseDtoBossStatus;
  /** BOSS审核时间 */
  bossTime?: string;
  /** 经营场所照片 */
  businessLocationImageUrl?: string;
  /** 渠道供应商类型,null:null,null:null */
  channelType?: EnterpriseDtoChannelType;
  /** 公司所在市 */
  city?: string;
  /** 公司所在详细地址 */
  comAddress?: string;
  /** 企业名称 */
  comName?: string;
  /** 备注 */
  comments?: string;
  /** 企账通合同状态,success:成功,failure:失败,processing:处理中 */
  contractStatus?: EnterpriseDtoContractStatus;
  /** 创建时间 */
  createTime?: string;
  /** 授信额度 */
  creditLine?: Money;
  /** 是否禁用,enable:正常,disable:禁用 */
  disable?: EnterpriseDtoDisable;
  /** 公司所在区 */
  district?: string;
  /** 接收电子回单邮箱地址 */
  email?: string;
  /** 企业编号 */
  enterpriseNo?: string;
  /** 经办人信息 */
  handlerInfo?: EnterprisePersonDto;
  /** 经办人是否是法人,yes:是,no:否 */
  handlerIsLegal?: EnterpriseDtoHandlerIsLegal;
  /** 最大股东或实际控制人信息 */
  holdingInfo?: EnterprisePersonDto;
  /** 最大股东或实际控制人是否为法人,yes:是,no:否 */
  holdingIsLegal?: EnterpriseDtoHoldingIsLegal;
  /** id */
  id?: string;
  /** 是否修改,yes:是,no:否 */
  isModify?: EnterpriseDtoIsModify;
  /** 法人授权书地址 */
  legalAuthorizationUrl?: string;
  /** 法人信息 */
  legalInfo?: EnterprisePersonDto;
  /** 统一社会信用代码 */
  licenceNo?: string;
  /** 营业执照图片地址 */
  licencePath?: string;
  /** 创建者名称 */
  memberName?: string;
  /** 主要管理员编号 */
  memberNo?: string;
  /** 结算方式 */
  payMethod?: string;
  payMethodList?: EnterpriseDtoPayMethodListItem[];
  /** 公司所在省 */
  prov?: string;
  /** 注册手机号 */
  registMobileNo?: string;
  /** 是否自营,yes:是,no:否 */
  self?: EnterpriseDtoSelf;
  /** 店铺ID */
  shopId?: string;
  /** 电子签审核原因 */
  signReason?: string;
  /** 电子签审核状态,success:成功,failure:失败,processing:处理中 */
  signStatus?: EnterpriseDtoSignStatus;
  /** 类型,buyer:企业,seller:供应商 */
  type?: EnterpriseDtoType;
  /** 更新时间 */
  updateTime?: string;
  /** 是否内部申请,yes:是,no:否 */
  whetherInternal?: EnterpriseDtoWhetherInternal;
}
