/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { EnterpriseTempAccountBossStatus } from './enterpriseTempAccountBossStatus';
import type { EnterpriseTempAccountRegType } from './enterpriseTempAccountRegType';
import type { EnterpriseTempAccountStatus } from './enterpriseTempAccountStatus';
import type { EnterpriseTempBankDisable } from './enterpriseTempBankDisable';
import type { EnterpriseTempBankStatus } from './enterpriseTempBankStatus';
import type { EnterpriseTempBossStatus } from './enterpriseTempBossStatus';
import type { EnterpriseTempChannelType } from './enterpriseTempChannelType';
import type { EnterpriseTempContractStatus } from './enterpriseTempContractStatus';
import type { Money } from './money';
import type { EnterpriseTempDisable } from './enterpriseTempDisable';
import type { EnterpriseTempIsModify } from './enterpriseTempIsModify';
import type { EnterpriseTempPayMethodListItem } from './enterpriseTempPayMethodListItem';
import type { EnterpriseTempSelf } from './enterpriseTempSelf';
import type { EnterpriseTempSignStatus } from './enterpriseTempSignStatus';
import type { EnterpriseTempType } from './enterpriseTempType';
import type { EnterpriseTempWhetherInternal } from './enterpriseTempWhetherInternal';

/**
 * 企业审核信息
 */
export interface EnterpriseTemp {
  /** BOOS企账通审核原因 */
  accountBossReason?: string;
  /** BOOS企账通审核状态,success:成功,failure:失败,processing:处理中 */
  accountBossStatus?: EnterpriseTempAccountBossStatus;
  /** 企账通审核原因 */
  accountReason?: string;
  /** 企账通注册类型,buyer_reg:企业注册企账通,seller_reg:供应商注册并开通企账通 */
  accountRegType?: EnterpriseTempAccountRegType;
  /** 企账通审核状态,success:成功,failure:失败,processing:处理中 */
  accountStatus?: EnterpriseTempAccountStatus;
  /** 企业对公账户 */
  bankCardNo?: string;
  /** 银行编码 */
  bankCode?: string;
  /** 企账通是否禁用,enable:正常,disable:禁用 */
  bankDisable?: EnterpriseTempBankDisable;
  /** 企账通是否禁用原因 */
  bankDisableReason?: string;
  /** 银行审核原因 */
  bankReason?: string;
  /** 银行审核状态,success:成功,failure:失败,processing:处理中 */
  bankStatus?: EnterpriseTempBankStatus;
  /** 银行联行号 */
  bankUnitNo?: string;
  /** 受益人信息NO */
  benefitNo?: string;
  /** BOSS名称 */
  bossName?: string;
  /** BOSS编号 */
  bossNo?: string;
  /** BOSS审核原因 */
  bossReason?: string;
  /** BOSS审核状态,success:成功,failure:失败,processing:处理中 */
  bossStatus?: EnterpriseTempBossStatus;
  /** BOSS审核时间 */
  bossTime?: string;
  /** 经营场所照片 */
  businessLocationImageUrl?: string;
  /** 渠道供应商类型,null:null,null:null */
  channelType?: EnterpriseTempChannelType;
  /** 公司所在市 */
  city?: string;
  /** 公司所在详细地址 */
  comAddress?: string;
  /** 企业名称 */
  comName?: string;
  /** 备注 */
  comments?: string;
  /** 企账通合同状态,success:成功,failure:失败,processing:处理中 */
  contractStatus?: EnterpriseTempContractStatus;
  createTime?: string;
  /** 授信额度 */
  creditLine?: Money;
  /** 冻结授信额度 */
  creditLineFreeze?: Money;
  /** 企业是否禁用,enable:正常,disable:禁用 */
  disable?: EnterpriseTempDisable;
  /** 企业禁用原因 */
  disableReason?: string;
  /** 公司所在区 */
  district?: string;
  /** 接收电子回单邮箱地址 */
  email?: string;
  /** 企业编号 */
  enterpriseNo?: string;
  /** 经办人信息NO */
  handlerNo?: string;
  /** 最大股东或实际控制人信息NO */
  holdingNo?: string;
  id?: string;
  /** 是否修改,yes:是,no:否 */
  isModify?: EnterpriseTempIsModify;
  /** 法人授权书地址 */
  legalAuthorizationUrl?: string;
  /** 法人信息NO */
  legalNo?: string;
  /** 统一社会信用代码 */
  licenceNo?: string;
  /** 营业执照图片地址 */
  licencePath?: string;
  /** 创建者名称 */
  memberName?: string;
  /** 主要管理员编号 */
  memberNo?: string;
  /** 结算方式 */
  payMethod?: string;
  payMethodList?: EnterpriseTempPayMethodListItem[];
  /** 公司所在省 */
  prov?: string;
  /** 注册手机号 */
  registMobileNo?: string;
  /** 是否自营,yes:是,no:否 */
  self?: EnterpriseTempSelf;
  /** 电子签审核原因 */
  signReason?: string;
  /** 电子签审核状态,success:成功,failure:失败,processing:处理中 */
  signStatus?: EnterpriseTempSignStatus;
  /** 类型,buyer:企业,seller:供应商 */
  type?: EnterpriseTempType;
  updateTime?: string;
  /** 是否内部申请,yes:是,no:否 */
  whetherInternal?: EnterpriseTempWhetherInternal;
}
