/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 状态,init:初始,buyer_processing:等待买家签署,seller_processing:等待供应商签署,done:合同生效,fail:合同失效
 */
export type EnterpriseContractPageRequestStatus = typeof EnterpriseContractPageRequestStatus[keyof typeof EnterpriseContractPageRequestStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseContractPageRequestStatus = {
  buyer_processing: 'buyer_processing',
  done: 'done',
  fail: 'fail',
  init: 'init',
  seller_processing: 'seller_processing',
} as const;
