/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 企账通注册类型,buyer_reg:企业注册企账通,seller_reg:供应商注册并开通企账通
 */
export type EnterpriseAccountAuditListVoAccountRegType = typeof EnterpriseAccountAuditListVoAccountRegType[keyof typeof EnterpriseAccountAuditListVoAccountRegType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseAccountAuditListVoAccountRegType = {
  buyer_reg: 'buyer_reg',
  seller_reg: 'seller_reg',
} as const;
