/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 最大股东或实际控制人是否为法人,yes:是,no:否
 */
export type EnterpriseDtoHoldingIsLegal = typeof EnterpriseDtoHoldingIsLegal[keyof typeof EnterpriseDtoHoldingIsLegal];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseDtoHoldingIsLegal = {
  no: 'no',
  yes: 'yes',
} as const;
