/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 法人证件是否长期有效,yes:是,no:否
 */
export type EnterpriseBuyerRegisterRequestCertForever = typeof EnterpriseBuyerRegisterRequestCertForever[keyof typeof EnterpriseBuyerRegisterRequestCertForever];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseBuyerRegisterRequestCertForever = {
  no: 'no',
  yes: 'yes',
} as const;
