/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 渠道供应商类型,null:null,null:null
 */
export type EnterpriseDtoChannelType = typeof EnterpriseDtoChannelType[keyof typeof EnterpriseDtoChannelType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseDtoChannelType = {
  factory: 'factory',
  integrated: 'integrated',
} as const;
