/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { OFileDto } from './oFileDto';
import type { Money } from './money';
import type { EnterpriseContractPageVoPartADealType } from './enterpriseContractPageVoPartADealType';
import type { EnterpriseContractPageVoPartBDealType } from './enterpriseContractPageVoPartBDealType';
import type { EnterpriseContractPageVoStatus } from './enterpriseContractPageVoStatus';
import type { EnterpriseContractPageVoStatusStr } from './enterpriseContractPageVoStatusStr';

/**
 * 点对点合同列表
 */
export interface EnterpriseContractPageVo {
  /** 备注 */
  content?: string;
  /** 合同名称 */
  contractName?: string;
  /** 合同编号 */
  contractNo?: string;
  /** 合同子编号 */
  contractSubNo?: string;
  createTime?: string;
  /** 下载时间 */
  downloadTime?: string;
  /** 附件信息 */
  fileInfo?: OFileDto;
  /** 附件链接 */
  fileUrl?: string;
  id?: string;
  /** 金额 */
  money?: Money;
  /** 订单编号 */
  orderNo?: string;
  /** 甲方处理方式,0:手动签约,1:自动签约 */
  partADealType?: EnterpriseContractPageVoPartADealType;
  /** 乙方处理方式,0:手动签约,1:自动签约 */
  partBDealType?: EnterpriseContractPageVoPartBDealType;
  /** 甲方企业名称 */
  partyAEnterpriseName?: string;
  /** 甲方企业编号(买方企业) */
  partyAEnterpriseNo?: string;
  /** 甲方签约时间 */
  partyAOperateTime?: string;
  /** 乙方企业名称 */
  partyBEnterpriseName?: string;
  /** 乙方企业编号(卖方供应商) */
  partyBEnterpriseNo?: string;
  /** 乙方签约时间 */
  partyBOperateTime?: string;
  /** 生成PDF预览链接 */
  pdfUrl?: string;
  /** 不通过原因 */
  reason?: string;
  /** 合同状态,success:成功,failure:失败,processing:处理中 */
  status?: EnterpriseContractPageVoStatus;
  /** 合同状态,汇总显示,init:初始,buyer_processing:等待买家签署,seller_processing:等待供应商签署,done:合同生效,fail:合同失效 */
  statusStr?: EnterpriseContractPageVoStatusStr;
  /** 模板编号 */
  templateNo?: string;
  updateTime?: string;
}
