/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { EnterpriseAccountDisableRequestStatus } from './enterpriseAccountDisableRequestStatus';

/**
 * 企账通启用禁用
 */
export interface EnterpriseAccountDisableRequest {
  /** id */
  id?: string;
  /** 原因:失败时必传 */
  reason?: string;
  /** 状态,enable:正常,disable:禁用 */
  status?: EnterpriseAccountDisableRequestStatus;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
