/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 受益人信息是否为法人,yes:是,no:否
 */
export type EnterpriseDtoBenefitIsLegal = typeof EnterpriseDtoBenefitIsLegal[keyof typeof EnterpriseDtoBenefitIsLegal];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseDtoBenefitIsLegal = {
  no: 'no',
  yes: 'yes',
} as const;
