/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { EnterpriseTempAuditPageRequestBossStatus } from './enterpriseTempAuditPageRequestBossStatus';

/**
 * 入驻企业列表请求
 */
export interface EnterpriseTempAuditPageRequest {
  /** BOSS审核状态,success:成功,failure:失败,processing:处理中,wait_three_party:待三方校验 */
  bossStatus?: EnterpriseTempAuditPageRequestBossStatus;
  /** 企业名称 */
  comName?: string;
  /** 申请时间结束 */
  createTimeEnd?: string;
  /** 申请时间开始 */
  createTimeStart?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 申请人 */
  memberName?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 申请人电话 */
  registMobileNo?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
