/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 乙方处理方式,0:手动签约,1:自动签约
 */
export type EnterpriseContractPageVoPartBDealType = typeof EnterpriseContractPageVoPartBDealType[keyof typeof EnterpriseContractPageVoPartBDealType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseContractPageVoPartBDealType = {
  automatic: 'automatic',
  manual: 'manual',
} as const;
