/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 是否自营,yes:自营,yes:是,no:否
 */
export type EnterpriseBuyerRegisterRequestSelf = typeof EnterpriseBuyerRegisterRequestSelf[keyof typeof EnterpriseBuyerRegisterRequestSelf];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseBuyerRegisterRequestSelf = {
  no: 'no',
  yes: 'yes',
} as const;
