/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 类型,buyer:企业,seller:供应商
 */
export type EnterpriseType = typeof EnterpriseType[keyof typeof EnterpriseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseType = {
  buyer: 'buyer',
  seller: 'seller',
} as const;
