/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { EnterpriseContractPageRequestStatus } from './enterpriseContractPageRequestStatus';

/**
 * 企账通管理列表
 */
export interface EnterpriseContractPageRequest {
  /** 买家企业名称 */
  comNameBuyer?: string;
  /** 供应商企业名称 */
  comNameSeller?: string;
  /** 订单 合同编码 */
  contractNo?: string;
  /** 时间结束 */
  createTimeEnd?: string;
  /** 时间开始 */
  createTimeStart?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 关联订单编码 */
  orderNo?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 页量(默认值:10) */
  size?: number;
  /** 状态,init:初始,buyer_processing:等待买家签署,seller_processing:等待供应商签署,done:合同生效,fail:合同失效 */
  status?: EnterpriseContractPageRequestStatus;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
