/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type EnterprisePayMethodListItem = typeof EnterprisePayMethodListItem[keyof typeof EnterprisePayMethodListItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterprisePayMethodListItem = {
  payment_after_delivery: 'payment_after_delivery',
  payment_before_delivery: 'payment_before_delivery',
} as const;
