/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 经办人是否是法人,yes:是,no:否
 */
export type EnterpriseShowInfoDtoHandlerIsLegal = typeof EnterpriseShowInfoDtoHandlerIsLegal[keyof typeof EnterpriseShowInfoDtoHandlerIsLegal];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseShowInfoDtoHandlerIsLegal = {
  no: 'no',
  yes: 'yes',
} as const;
