/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 证件是否长期有效,yes:是,no:否
 */
export type EnterprisePersonDtoCertForever = typeof EnterprisePersonDtoCertForever[keyof typeof EnterprisePersonDtoCertForever];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterprisePersonDtoCertForever = {
  no: 'no',
  yes: 'yes',
} as const;
