/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { EnterpriseBuyerRegisterRequestCertForever } from './enterpriseBuyerRegisterRequestCertForever';
import type { EnterpriseBuyerRegisterRequestSelf } from './enterpriseBuyerRegisterRequestSelf';

/**
 * 企业新增
 */
export interface EnterpriseBuyerRegisterRequest {
  /** 法人为no时必填 */
  certDateEnd?: string;
  /** 法人证件签发日 */
  certDateStart?: string;
  /** 法人证件是否长期有效,yes:是,no:否 */
  certForever?: EnterpriseBuyerRegisterRequestCertForever;
  /** 经营场所详细地址 公司所在详细地址 */
  comAddress?: string;
  /** 企业名称 */
  comName?: string;
  /** 备注 */
  comments?: string;
  /** 法人授权书地址 */
  legalAuthorizationUrl?: string;
  /** 法人身份证号码 */
  legalCertNo?: string;
  /** 法人真实姓名 */
  legalRealName?: string;
  /** 统一社会信用代码 */
  licenceNo?: string;
  /** 营业执照本扫描件 */
  licencePath?: string;
  /** 企业超管 编码 */
  memberNo?: string;
  /** 法人手机号 */
  mobileNo?: string;
  /** 是否自营,yes:自营,yes:是,no:否 */
  self?: EnterpriseBuyerRegisterRequestSelf;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
