/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 是否修改,yes:是,no:否
 */
export type EnterpriseShowInfoDtoIsModify = typeof EnterpriseShowInfoDtoIsModify[keyof typeof EnterpriseShowInfoDtoIsModify];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseShowInfoDtoIsModify = {
  no: 'no',
  yes: 'yes',
} as const;
