/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 会员账户开户状态,SAVE_SUCCESS:待认证,SAVE_FAILER:录入失败,NORMAL:正常,AUTH_FAILER:认证拒绝,FREEZE:冻结,CANCEL:作废
 */
export type EnterpriseAccountPageVoAccountOpenStatus = typeof EnterpriseAccountPageVoAccountOpenStatus[keyof typeof EnterpriseAccountPageVoAccountOpenStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseAccountPageVoAccountOpenStatus = {
  AUTH_FAILER: 'AUTH_FAILER',
  CANCEL: 'CANCEL',
  FREEZE: 'FREEZE',
  NORMAL: 'NORMAL',
  SAVE_FAILER: 'SAVE_FAILER',
  SAVE_SUCCESS: 'SAVE_SUCCESS',
} as const;
