/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * BOSS审核状态,success:成功,failure:失败,processing:处理中,wait_three_party:待三方校验
 */
export type EnterpriseShowInfoDtoBossStatusStr = typeof EnterpriseShowInfoDtoBossStatusStr[keyof typeof EnterpriseShowInfoDtoBossStatusStr];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseShowInfoDtoBossStatusStr = {
  failure: 'failure',
  processing: 'processing',
  success: 'success',
  wait_three_party: 'wait_three_party',
} as const;
