/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 是否自营,yes:是,no:否
 */
export type EnterpriseShowInfoDtoSelf = typeof EnterpriseShowInfoDtoSelf[keyof typeof EnterpriseShowInfoDtoSelf];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseShowInfoDtoSelf = {
  no: 'no',
  yes: 'yes',
} as const;
