/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { EnterpriseListRequestAccountStatus } from './enterpriseListRequestAccountStatus';
import type { EnterpriseListRequestDisable } from './enterpriseListRequestDisable';
import type { EnterpriseListRequestSelf } from './enterpriseListRequestSelf';
import type { EnterpriseListRequestSignStatus } from './enterpriseListRequestSignStatus';
import type { EnterpriseListRequestType } from './enterpriseListRequestType';

/**
 * 入驻企业列表
 */
export interface EnterpriseListRequest {
  /** 企账通审核状态,success:成功,failure:失败,processing:处理中 */
  accountStatus?: EnterpriseListRequestAccountStatus;
  /** 企业名称 */
  comName?: string;
  /** 入驻时间结束 */
  createTimeEnd?: string;
  /** 入驻时间开始 */
  createTimeStart?: string;
  /** 状态,enable:正常,disable:禁用 */
  disable?: EnterpriseListRequestDisable;
  /** 企业编号 */
  enterpriseNo?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 页码(默认值:1) */
  page?: number;
  /** 是否自营,yes:是,no:否 */
  self?: EnterpriseListRequestSelf;
  /** 电子签审核状态,success:成功,failure:失败,processing:处理中 */
  signStatus?: EnterpriseListRequestSignStatus;
  /** 页量(默认值:10) */
  size?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** 类型,buyer:企业,seller:供应商 */
  type?: EnterpriseListRequestType;
}
