/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { EnterpriseAccountAuditPageRequestAccountBossStatus } from './enterpriseAccountAuditPageRequestAccountBossStatus';

/**
 * 企账通审核列表请求
 */
export interface EnterpriseAccountAuditPageRequest {
  /** 企账通Boss审核状态,success:开通成功,failure:开通失败,processing:开通中,init:初始 */
  accountBossStatus?: EnterpriseAccountAuditPageRequestAccountBossStatus;
  /** 企业名称 */
  comName?: string;
  /** 创建时间结束 */
  createTimeEnd?: string;
  /** 创建时间开始 */
  createTimeStart?: string;
  /** 企业编号 */
  enterpriseNo?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 页码(默认值:1) */
  page?: number;
  /** 页量(默认值:10) */
  size?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
