/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { EnterpriseAccountPageVoAccountOpenStatus } from './enterpriseAccountPageVoAccountOpenStatus';
import type { Money } from './money';
import type { EnterpriseAccountPageVoBankDisable } from './enterpriseAccountPageVoBankDisable';
import type { EnterpriseAccountPageVoBankStatus } from './enterpriseAccountPageVoBankStatus';
import type { EnterpriseAccountPageVoChannelType } from './enterpriseAccountPageVoChannelType';

/**
 * 企账通账号管理列表数据
 */
export interface EnterpriseAccountPageVo {
  /** 会员账户编码 */
  accountNo?: string;
  /** 会员账户开户状态,SAVE_SUCCESS:待认证,SAVE_FAILER:录入失败,NORMAL:正常,AUTH_FAILER:认证拒绝,FREEZE:冻结,CANCEL:作废 */
  accountOpenStatus?: EnterpriseAccountPageVoAccountOpenStatus;
  /** 余额 */
  balance?: Money;
  /** 可用余额 */
  balanceAble?: Money;
  /** 银行子账户编码 */
  bankAccountCoreNo?: string;
  /** 银行账户编码 */
  bankAccountNo?: string;
  /** 银行卡号 */
  bankCardNo?: string;
  /** 银行编码 */
  bankCode?: string;
  /** 企账通是否禁用,enable:正常,disable:禁用 */
  bankDisable?: EnterpriseAccountPageVoBankDisable;
  /** 开户行名称 */
  bankName?: string;
  /** 企账通开通状态,success:成功,failure:失败,processing:处理中 */
  bankStatus?: EnterpriseAccountPageVoBankStatus;
  /** 渠道供应商类型,null:null,null:null */
  channelType?: EnterpriseAccountPageVoChannelType;
  /** 企业名称 */
  comName?: string;
  /** 创建时间 */
  createTime?: string;
  /** 企业ID */
  eid?: string;
  /** 企业编码 */
  enterpriseNo?: string;
  /** 冻结金额 */
  freezeAmount?: Money;
  /** 备注码 */
  markCode?: string;
  /** 开户链接地址 */
  redirectUrl?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 会员编码 */
  userNo?: string;
}
