/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { EnterpriseDisableRequestDisable } from './enterpriseDisableRequestDisable';

export interface EnterpriseDisableRequest {
  /** 企业是否禁用,enable:正常,disable:禁用 */
  disable?: EnterpriseDisableRequestDisable;
  /** 企业禁用原因(禁用时必填) */
  disableReason?: string;
  /** ID */
  id?: string;
}
