/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 企账通是否禁用,enable:正常,disable:禁用
 */
export type EnterpriseAccountPageVoBankDisable = typeof EnterpriseAccountPageVoBankDisable[keyof typeof EnterpriseAccountPageVoBankDisable];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseAccountPageVoBankDisable = {
  disable: 'disable',
  enable: 'enable',
} as const;
