/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 甲方处理方式,0:手动签约,1:自动签约
 */
export type EnterpriseContractPageVoPartADealType = typeof EnterpriseContractPageVoPartADealType[keyof typeof EnterpriseContractPageVoPartADealType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseContractPageVoPartADealType = {
  automatic: 'automatic',
  manual: 'manual',
} as const;
