/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 是否修改,yes:是,no:否
 */
export type EnterpriseTempIsModify = typeof EnterpriseTempIsModify[keyof typeof EnterpriseTempIsModify];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseTempIsModify = {
  no: 'no',
  yes: 'yes',
} as const;
