/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 企账通审核的状态,success:开通成功,failure:开通失败,processing:开通中,init:初始
 */
export type EnterpriseShowInfoDtoEnterpriseAccountStatus = typeof EnterpriseShowInfoDtoEnterpriseAccountStatus[keyof typeof EnterpriseShowInfoDtoEnterpriseAccountStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseShowInfoDtoEnterpriseAccountStatus = {
  failure: 'failure',
  init: 'init',
  processing: 'processing',
  success: 'success',
} as const;
