/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { EnterpriseShowInfoDtoAccountBossStatus } from './enterpriseShowInfoDtoAccountBossStatus';
import type { EnterpriseShowInfoDtoAccountRegType } from './enterpriseShowInfoDtoAccountRegType';
import type { EnterpriseShowInfoDtoAccountStatus } from './enterpriseShowInfoDtoAccountStatus';
import type { MemberDto } from './memberDto';
import type { EnterpriseShowInfoDtoBankStatus } from './enterpriseShowInfoDtoBankStatus';
import type { EnterprisePersonDto } from './enterprisePersonDto';
import type { EnterpriseShowInfoDtoBenefitIsLegal } from './enterpriseShowInfoDtoBenefitIsLegal';
import type { EnterpriseShowInfoDtoBossStatus } from './enterpriseShowInfoDtoBossStatus';
import type { EnterpriseShowInfoDtoBossStatusStr } from './enterpriseShowInfoDtoBossStatusStr';
import type { EnterpriseShowInfoDtoChannelType } from './enterpriseShowInfoDtoChannelType';
import type { EnterpriseShowInfoDtoContractStatus } from './enterpriseShowInfoDtoContractStatus';
import type { Money } from './money';
import type { EnterpriseShowInfoDtoDisable } from './enterpriseShowInfoDtoDisable';
import type { EnterpriseShowInfoDtoEnterpriseAccountStatus } from './enterpriseShowInfoDtoEnterpriseAccountStatus';
import type { EnterpriseShowInfoDtoHandlerIsLegal } from './enterpriseShowInfoDtoHandlerIsLegal';
import type { EnterpriseShowInfoDtoHoldingIsLegal } from './enterpriseShowInfoDtoHoldingIsLegal';
import type { EnterpriseShowInfoDtoIsModify } from './enterpriseShowInfoDtoIsModify';
import type { EnterpriseShowInfoDtoPayMethodListItem } from './enterpriseShowInfoDtoPayMethodListItem';
import type { EnterpriseShowInfoDtoSelf } from './enterpriseShowInfoDtoSelf';
import type { EnterpriseShowInfoDtoSignStatus } from './enterpriseShowInfoDtoSignStatus';
import type { EnterpriseShowInfoDtoType } from './enterpriseShowInfoDtoType';
import type { EnterpriseShowInfoDtoWhetherInternal } from './enterpriseShowInfoDtoWhetherInternal';

/**
 * 企业信息
 */
export interface EnterpriseShowInfoDto {
  /** BOOS企账通审核原因 */
  accountBossReason?: string;
  /** BOOS企账通审核状态,success:成功,failure:失败,processing:处理中 */
  accountBossStatus?: EnterpriseShowInfoDtoAccountBossStatus;
  /** 企账通审核原因 */
  accountReason?: string;
  /** 企账通注册类型,buyer_reg:企业注册企账通,seller_reg:供应商注册并开通企账通 */
  accountRegType?: EnterpriseShowInfoDtoAccountRegType;
  /** 企账通审核状态,success:成功,failure:失败,processing:处理中 */
  accountStatus?: EnterpriseShowInfoDtoAccountStatus;
  /** 企业超管详情 */
  adminMemberDto?: MemberDto;
  /** 企业对公账户 */
  bankCardNo?: string;
  /** 银行编码 */
  bankCode?: string;
  /** 银行名称 */
  bankCodeName?: string;
  /** 银行审核原因 */
  bankReason?: string;
  /** 银行审核状态,success:成功,failure:失败,processing:处理中 */
  bankStatus?: EnterpriseShowInfoDtoBankStatus;
  /** 银行联行号 */
  bankUnitNo?: string;
  /** 受益人信息 */
  benefitInfo?: EnterprisePersonDto;
  /** 受益人信息是否为法人,yes:是,no:否 */
  benefitIsLegal?: EnterpriseShowInfoDtoBenefitIsLegal;
  /** BOSS名称 */
  bossName?: string;
  /** BOSS编号 */
  bossNo?: string;
  /** BOSS审核原因 */
  bossReason?: string;
  /** BOSS审核状态,success:成功,failure:失败,processing:处理中 */
  bossStatus?: EnterpriseShowInfoDtoBossStatus;
  /** BOSS审核状态,success:成功,failure:失败,processing:处理中,wait_three_party:待三方校验 */
  bossStatusStr?: EnterpriseShowInfoDtoBossStatusStr;
  /** BOSS审核时间 */
  bossTime?: string;
  /** 经营场所照片 */
  businessLocationImageUrl?: string;
  /** 渠道供应商类型,null:null,null:null */
  channelType?: EnterpriseShowInfoDtoChannelType;
  /** 公司所在市 */
  city?: string;
  /** 公司所在详细地址 */
  comAddress?: string;
  /** 企业名称 */
  comName?: string;
  /** 备注 */
  comments?: string;
  /** 企账通合同状态,success:成功,failure:失败,processing:处理中 */
  contractStatus?: EnterpriseShowInfoDtoContractStatus;
  /** 创建时间 */
  createTime?: string;
  /** 授信额度 */
  creditLine?: Money;
  /** 是否禁用,enable:正常,disable:禁用 */
  disable?: EnterpriseShowInfoDtoDisable;
  /** 公司所在区 */
  district?: string;
  /** 接收电子回单邮箱地址 */
  email?: string;
  /** 企账通审核的状态,success:开通成功,failure:开通失败,processing:开通中,init:初始 */
  enterpriseAccountStatus?: EnterpriseShowInfoDtoEnterpriseAccountStatus;
  /** 企业编号 */
  enterpriseNo?: string;
  /** 经办人信息 */
  handlerInfo?: EnterprisePersonDto;
  /** 经办人是否是法人,yes:是,no:否 */
  handlerIsLegal?: EnterpriseShowInfoDtoHandlerIsLegal;
  /** 最大股东或实际控制人信息 */
  holdingInfo?: EnterprisePersonDto;
  /** 最大股东或实际控制人是否为法人,yes:是,no:否 */
  holdingIsLegal?: EnterpriseShowInfoDtoHoldingIsLegal;
  /** id */
  id?: string;
  /** 是否修改,yes:是,no:否 */
  isModify?: EnterpriseShowInfoDtoIsModify;
  /** 法人授权书地址 */
  legalAuthorizationUrl?: string;
  /** 法人信息 */
  legalInfo?: EnterprisePersonDto;
  /** 统一社会信用代码 */
  licenceNo?: string;
  /** 营业执照图片地址 */
  licencePath?: string;
  /** 创建者名称 */
  memberName?: string;
  /** 主要管理员编号 */
  memberNo?: string;
  /** 结算方式 */
  payMethod?: string;
  payMethodList?: EnterpriseShowInfoDtoPayMethodListItem[];
  /** 公司所在省 */
  prov?: string;
  /** 注册手机号 */
  registMobileNo?: string;
  /** 是否自营,yes:是,no:否 */
  self?: EnterpriseShowInfoDtoSelf;
  /** 店铺ID */
  shopId?: string;
  /** 电子签审核原因 */
  signReason?: string;
  /** 电子签审核状态,success:成功,failure:失败,processing:处理中 */
  signStatus?: EnterpriseShowInfoDtoSignStatus;
  /** 类型,buyer:企业,seller:供应商 */
  type?: EnterpriseShowInfoDtoType;
  /** 更新时间 */
  updateTime?: string;
  /** 是否内部申请,yes:是,no:否 */
  whetherInternal?: EnterpriseShowInfoDtoWhetherInternal;
}
