/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 状态,[success:通过,failure:拒绝],success:成功,failure:失败,processing:处理中
 */
export type EnterpriseAccountAuditRequestStatus = typeof EnterpriseAccountAuditRequestStatus[keyof typeof EnterpriseAccountAuditRequestStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EnterpriseAccountAuditRequestStatus = {
  failure: 'failure',
  processing: 'processing',
  success: 'success',
} as const;
