/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type ExportExcel1OrderStatus = typeof ExportExcel1OrderStatus[keyof typeof ExportExcel1OrderStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportExcel1OrderStatus = {
  CANCEL: 'CANCEL',
  FINISH: 'FINISH',
  INIT: 'INIT',
  ISSUED: 'ISSUED',
  PART_ISSUED: 'PART_ISSUED',
  REFUND: 'REFUND',
  REFUND_APPLY_ING: 'REFUND_APPLY_ING',
  REFUND_GOODS: 'REFUND_GOODS',
  REFUND_GOODS_ING: 'REFUND_GOODS_ING',
  REFUND_PART_GOODS: 'REFUND_PART_GOODS',
  WAIT_CONFIRM_AMOUNT: 'WAIT_CONFIRM_AMOUNT',
  WAIT_CONTRACT: 'WAIT_CONTRACT',
  WAIT_PAY: 'WAIT_PAY',
  WAIT_SEND: 'WAIT_SEND',
} as const;
