/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type ExportExcel1SelfStatus = typeof ExportExcel1SelfStatus[keyof typeof ExportExcel1SelfStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportExcel1SelfStatus = {
  no: 'no',
  yes: 'yes',
} as const;
