/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type ExportExcelLogisticsSendType = typeof ExportExcelLogisticsSendType[keyof typeof ExportExcelLogisticsSendType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportExcelLogisticsSendType = {
  MANY: 'MANY',
  ONCE: 'ONCE',
} as const;
