/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type ExportExcel1PayMethod = typeof ExportExcel1PayMethod[keyof typeof ExportExcel1PayMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportExcel1PayMethod = {
  BALANCE_PAY: 'BALANCE_PAY',
  CREDIT_PAY: 'CREDIT_PAY',
  OFFLINE_PAY: 'OFFLINE_PAY',
} as const;
