/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type ExportExcelReceiveStatus = typeof ExportExcelReceiveStatus[keyof typeof ExportExcelReceiveStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportExcelReceiveStatus = {
  RECEIVED: 'RECEIVED',
  REJECT: 'REJECT',
  WAIT_REC: 'WAIT_REC',
} as const;
