/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type ExportExcel1SettleStatus = typeof ExportExcel1SettleStatus[keyof typeof ExportExcel1SettleStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportExcel1SettleStatus = {
  CLOSED: 'CLOSED',
  PART: 'PART',
  SETTED: 'SETTED',
  WAIT: 'WAIT',
} as const;
