/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type ExportInfoSysBusinessLogParams = { appId?: string; btnCode?: string; functionName?: string; gid?: string; isPage?: boolean; logType?: string; moduleCode?: string; page?: number; receiveDateEnd?: string; receiveDateStart?: string; size?: number; tokenUserCode?: string; tokenUserName?: string; userCode?: string; userName?: string };
