/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { InputStream } from './inputStream';
import type { OutputStream } from './outputStream';

export interface FileSystemResource {
  description?: string;
  file?: Blob;
  filename?: string;
  inputStream?: InputStream;
  open?: boolean;
  outputStream?: OutputStream;
  path?: string;
  readable?: boolean;
  uri?: string;
  url?: string;
  writable?: boolean;
}
