/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CategoryDetailVO } from './categoryDetailVO';

export interface HomeCategoryTreeVO {
  /** 背景图 */
  background?: string;
  childrens?: CategoryDetailVO[];
  /** ID */
  id?: string;
  /** remark */
  remark?: string;
  /** 序号 */
  sequence?: number;
  /** 状态 1正常0停用 */
  status?: number;
  /** 次标题 */
  subtitle?: string;
  /** 标题 */
  title?: string;
}
