/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface HomeCategoryCommodityListRequest {
  /** 一级类目编码 */
  categoryId?: string;
  /** 商品编码 */
  commodityId?: string;
  /** 商品名称 */
  commodityName?: string;
  /** 分类详情ID */
  detailId?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** layout_id */
  layoutId?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 分类名称 */
  productCategoryName?: string;
  /** 是否自营 */
  proprietary?: number;
  /** 发布状态 */
  publishStatus?: number;
  /** 商品名称 */
  shopName?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
