/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 状态,init:初始,processing:询价中,closed:已关闭
 */
export type InquiryInfoDtoStatus = typeof InquiryInfoDtoStatus[keyof typeof InquiryInfoDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InquiryInfoDtoStatus = {
  closed: 'closed',
  init: 'init',
  processing: 'processing',
} as const;
