/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Money } from './money';

export interface InquiryGoodsEnterpriseInfo {
  /** 企业名称 */
  comName?: string;
  /** 商品ID */
  commodityId?: string;
  /** 创建时间 */
  createTime?: string;
  /** 供应商ID */
  enterpriseId?: string;
  /** 企业编号 */
  enterpriseNo?: string;
  /** 商品ID */
  goodsId?: string;
  /** 历史报价记录 */
  historyList?: InquiryGoodsEnterpriseInfo[];
  id: string;
  /** 已下单数量 */
  orderQuantity?: number;
  /** 价格 */
  price?: Money;
  /** 报价编码 */
  quotationNo?: string;
  /** 商品sku编码 */
  skuCode?: string;
  /** 商品sku名称 */
  skuName?: string;
  /** 商品sku图片地址 */
  skuPic?: string;
  /** 单位 */
  unit?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 报价有效期 */
  validityPeriod?: string;
}
