/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 供应商范围类型,all:全部,assign:指定
 */
export type InquirySupplierType = typeof InquirySupplierType[keyof typeof InquirySupplierType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InquirySupplierType = {
  all: 'all',
  assign: 'assign',
} as const;
