/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { InquiryGoodsAttributeCreateInfo } from './inquiryGoodsAttributeCreateInfo';
import type { Money } from './money';
import type { InquiryGoodsEnterpriseInfo } from './inquiryGoodsEnterpriseInfo';
import type { CommoditySkuStockInfo } from './commoditySkuStockInfo';

export interface InquiryGoodsInfo {
  /** 类目ID */
  categoryId?: string;
  /** 类目ID列表 */
  categoryIdList?: string[];
  /** 商品ID */
  commodityId?: string;
  /** 关键属性 */
  crucialAttributeList?: InquiryGoodsAttributeCreateInfo[];
  /** 期望单价 */
  expectedPrice?: Money;
  /** 企业报价 */
  goodsEnterpriseInfoList?: InquiryGoodsEnterpriseInfo[];
  id: string;
  /** 询价单编码 */
  inquiryNo?: string;
  /** 标品名称 */
  name?: string;
  /** 数量 */
  quantity?: number;
  /** 销售属性 */
  sellAttributeList?: InquiryGoodsAttributeCreateInfo[];
  /** 商品sku值集合 */
  skuStockInfoList?: CommoditySkuStockInfo[];
  /** 最新价格效期 */
  validityPeriod?: string;
}
