/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { InquiryEnterpriseInfoStatus } from './inquiryEnterpriseInfoStatus';

export interface InquiryEnterpriseInfo {
  /** 企业名称 */
  comName?: string;
  /** 企业编号 */
  enterpriseNo?: string;
  id: string;
  /** 询价单编码 */
  inquiryNo?: string;
  /** 是否报价,yes:是,no:否 */
  status?: InquiryEnterpriseInfoStatus;
}
