/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 是否报价,yes:是,no:否
 */
export type InquiryEnterpriseInfoStatus = typeof InquiryEnterpriseInfoStatus[keyof typeof InquiryEnterpriseInfoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InquiryEnterpriseInfoStatus = {
  no: 'no',
  yes: 'yes',
} as const;
