/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type InquiryPageExportStatus = typeof InquiryPageExportStatus[keyof typeof InquiryPageExportStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InquiryPageExportStatus = {
  closed: 'closed',
  init: 'init',
  processing: 'processing',
} as const;
