/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { InquiryPageExportStatus } from './inquiryPageExportStatus';

export type InquiryPageExportParams = { inquiryNo?: string; goodsName?: string; comName?: string; memberName?: string; status?: InquiryPageExportStatus; createTimeStart?: string; createTimeEnd?: string; page?: number; size?: number };
