/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { InquiryPageRequestStatus } from './inquiryPageRequestStatus';

/**
 * 询价单列表
 */
export interface InquiryPageRequest {
  /** 询价企业名称 */
  comName?: string;
  /** 日期结束 */
  createTimeEnd?: string;
  /** 日期开始 */
  createTimeStart?: string;
  /** 询价商品名称 */
  goodsName?: string;
  /** 询价单编号 */
  inquiryNo?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 询价人姓名 */
  memberName?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 页量(默认值:10) */
  size?: number;
  /** 状态,init:初始,processing:询价中,closed:已关闭 */
  status?: InquiryPageRequestStatus;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
