/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { InquiryStatus } from './inquiryStatus';
import type { InquirySupplierType } from './inquirySupplierType';

/**
 * 询价单
 */
export interface Inquiry {
  /** 地址 */
  address?: string;
  /** 市 */
  city?: string;
  /** 询价企业 */
  comName?: string;
  createTime?: string;
  /** 询价截止日期 */
  dateEnd?: string;
  /** 协议开始时间 */
  dateStart?: string;
  /** 区 */
  district?: string;
  /** 采购方编号 */
  enterpriseNo?: string;
  id?: string;
  /** 询价单编码 */
  inquiryNo?: string;
  /** 创建人 */
  memberName?: string;
  /** 创建人编号 */
  memberNo?: string;
  /** 省 */
  prov?: string;
  /** 备注 */
  remark?: string;
  /** 状态,init:初始,processing:询价中,closed:已关闭 */
  status?: InquiryStatus;
  /** 供应商范围类型,all:全部,assign:指定 */
  supplierType?: InquirySupplierType;
  updateTime?: string;
}
