/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { InquiryEnterpriseInfo } from './inquiryEnterpriseInfo';
import type { InquiryGoodsInfo } from './inquiryGoodsInfo';
import type { InquiryManagerInfoDtoIsQuote } from './inquiryManagerInfoDtoIsQuote';
import type { InquiryManagerInfoDtoStatus } from './inquiryManagerInfoDtoStatus';
import type { InquiryManagerInfoDtoSupplierType } from './inquiryManagerInfoDtoSupplierType';

export interface InquiryManagerInfoDto {
  /** 市 */
  city?: string;
  /** 询价企业 */
  comName?: string;
  /** 创建时间 */
  createTime?: string;
  /** 询价截止日期 */
  dateEnd?: string;
  /** 询价截止日期字符串 */
  dateEndStr?: string;
  /** 协议开始时间 */
  dateStart?: string;
  /** 区 */
  district?: string;
  /** 供应商列表(供应商范围为assign时必传) */
  enterpriseList?: InquiryEnterpriseInfo[];
  /** 采购方编号 */
  enterpriseNo?: string;
  /** 询价商品信息列表 */
  goodsList?: InquiryGoodsInfo[];
  id: string;
  /** 询价单编码 */
  inquiryNo?: string;
  /** 是否报价,yes:是,no:否 */
  isQuote?: InquiryManagerInfoDtoIsQuote;
  /** 创建人 */
  memberName?: string;
  /** 创建人编号 */
  memberNo?: string;
  /** 手机号 */
  mobile?: string;
  /** 省 */
  prov?: string;
  /** 备注 */
  remark?: string;
  /** 状态,init:初始,processing:询价中,closed:已关闭 */
  status?: InquiryManagerInfoDtoStatus;
  /** 供应商范围类型,all:全部,assign:指定 */
  supplierType?: InquiryManagerInfoDtoSupplierType;
  /** 更新时间 */
  updateTime?: string;
}
