/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Money } from './money';
import type { InvoiceRecordContainsLongAgreement } from './invoiceRecordContainsLongAgreement';
import type { OFileDto } from './oFileDto';
import type { InvoiceRecordInvoiceBusinessType } from './invoiceRecordInvoiceBusinessType';
import type { InvoiceRecordInvoiceType } from './invoiceRecordInvoiceType';
import type { InvoiceRecordPromptedPriority } from './invoiceRecordPromptedPriority';
import type { InvoiceRecordStatus } from './invoiceRecordStatus';

/**
 * 发票记录
 */
export interface InvoiceRecord {
  agreementNo?: string;
  /** 开票金额 */
  amount?: Money;
  /** 关联对账单号 */
  billReconciliationOrderNo?: string;
  buyerInvoiceBodyId: string;
  /** 买家名称 */
  buyerName?: string;
  /** 买家编码 */
  buyerNo?: string;
  comments?: string;
  /** 发票确认时间 */
  confirmedTime?: string;
  /** null,yes:是,no:否 */
  containsLongAgreement?: InvoiceRecordContainsLongAgreement;
  createTime?: string;
  /** 发票 */
  fileList?: OFileDto[];
  /** 开票完成时间 */
  finishTime?: string;
  id?: string;
  /** null,GOODS_AMOUNT:货款,PAYEE_SERVICE_CHARGE:收款人手续费,PAYER_SERVICE_CHARGE:付款人手续费 */
  invoiceBusinessType?: InvoiceRecordInvoiceBusinessType;
  /** 发票抬头 */
  invoiceHeader?: string;
  invoiceNo?: string;
  /** 发票记录编码 */
  invoiceRecordNo?: string;
  /** 发票类型,VAT_ORDINARY:增值税普通发票,VAT_SPECIAL:增值税专用发票 */
  invoiceType?: InvoiceRecordInvoiceType;
  /** 发票路径 */
  invoiceUrl?: string;
  /** 发票路径数组格式 */
  invoiceUrlList?: string[];
  invoicingChannel?: string;
  /** 订单号们,分割 */
  orderNos?: string;
  /** 付款单号 */
  paymentOrderNo?: string;
  /** null,yes:是,no:否 */
  promptedPriority?: InvoiceRecordPromptedPriority;
  /** 卖家名称 */
  sellerName?: string;
  /** 卖家编码 */
  sellerNo?: string;
  /** 状态,INIT:初始化,WAIT_CONFIRM:待确认,CONFIRMED:已确认,REJECTED:已驳回,INVOICING:开票中,FAIL:失败,SUCCESS:成功,INVALIDATE:作废,UPLOADED:已上传,CLOSED:已关闭 */
  status?: InvoiceRecordStatus;
  taxNumber?: string;
  taxPoint?: string;
  updateTime?: string;
}
