/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { InvoiceRecordPageQueryRequestSearchEQInvoiceType } from './invoiceRecordPageQueryRequestSearchEQInvoiceType';
import type { InvoiceRecordPageQueryRequestSearchEQStatus } from './invoiceRecordPageQueryRequestSearchEQStatus';

/**
 * 发票记录分页查询入参
 */
export interface InvoiceRecordPageQueryRequest {
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 页码(默认值:1) */
  page?: number;
  /** 对账单号 */
  search_EQ_billReconciliationOrderNo?: string;
  /** 开票信息单号 */
  search_EQ_invoiceRecordNo?: string;
  /** 类型,VAT_ORDINARY:增值税普通发票,VAT_SPECIAL:增值税专用发票 */
  search_EQ_invoiceType?: InvoiceRecordPageQueryRequestSearchEQInvoiceType;
  /** 子订单号 */
  search_EQ_orderNo?: string;
  /** 付款单号 */
  search_EQ_paymentOrderNo?: string;
  /** 状态,INIT:初始化,WAIT_CONFIRM:待确认,CONFIRMED:已确认,REJECTED:已驳回,INVOICING:开票中,FAIL:失败,SUCCESS:成功,INVALIDATE:作废,UPLOADED:已上传,CLOSED:已关闭 */
  search_EQ_status?: InvoiceRecordPageQueryRequestSearchEQStatus;
  /** 开始生成时间，请严格按照提供的示例时间格式传入精确到秒！！ */
  search_GTE_createTime?: string;
  /** 结束生成时间，请严格按照提供的示例时间格式传入精确到秒！！ */
  search_LTE_createTime?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
