/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 类型,VAT_ORDINARY:增值税普通发票,VAT_SPECIAL:增值税专用发票
 */
export type InvoiceRecordPageQueryRequestSearchEQInvoiceType = typeof InvoiceRecordPageQueryRequestSearchEQInvoiceType[keyof typeof InvoiceRecordPageQueryRequestSearchEQInvoiceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceRecordPageQueryRequestSearchEQInvoiceType = {
  VAT_ORDINARY: 'VAT_ORDINARY',
  VAT_SPECIAL: 'VAT_SPECIAL',
} as const;
