/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * null,yes:是,no:否
 */
export type InvoiceRecordContainsLongAgreement = typeof InvoiceRecordContainsLongAgreement[keyof typeof InvoiceRecordContainsLongAgreement];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceRecordContainsLongAgreement = {
  no: 'no',
  yes: 'yes',
} as const;
