/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * null,GOODS_AMOUNT:货款,PAYEE_SERVICE_CHARGE:收款人手续费,PAYER_SERVICE_CHARGE:付款人手续费
 */
export type InvoiceRecordInvoiceBusinessType = typeof InvoiceRecordInvoiceBusinessType[keyof typeof InvoiceRecordInvoiceBusinessType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceRecordInvoiceBusinessType = {
  GOODS_AMOUNT: 'GOODS_AMOUNT',
  PAYEE_SERVICE_CHARGE: 'PAYEE_SERVICE_CHARGE',
  PAYER_SERVICE_CHARGE: 'PAYER_SERVICE_CHARGE',
} as const;
