/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { InvoiceBodyInfoVOInvoiceType } from './invoiceBodyInfoVOInvoiceType';

/**
 * 订单详情发票实体
 */
export interface InvoiceBodyInfoVO {
  /** 发票抬头 */
  invoiceHeader?: string;
  /** 发票类型,VAT_ORDINARY:增值税普通发票,VAT_SPECIAL:增值税专用发票 */
  invoiceType?: InvoiceBodyInfoVOInvoiceType;
}
