/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SettleOrder } from './settleOrder';

export interface IwubidaPageResultSettleOrder {
  /** 当前页码 */
  current?: number;
  /** 列表数据 */
  results?: SettleOrder[];
  /** 列表数据大小 */
  resultsSize?: number;
  /** 每页条数 */
  size?: number;
  /** 总记录条数 */
  totalCount?: number;
  totalPage?: number;
}
