/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Cms内容拓展实体 } from './cms内容拓展实体';

export interface IwubidaPageResultCMS内容拓展实体 {
  /** 当前页码 */
  current?: number;
  /** 列表数据 */
  results?: Cms内容拓展实体[];
  /** 列表数据大小 */
  resultsSize?: number;
  /** 每页条数 */
  size?: number;
  /** 总记录条数 */
  totalCount?: number;
  totalPage?: number;
}
