/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { JsonListResultCategoryLayoutExtVOData } from './jsonListResultCategoryLayoutExtVOData';
import type { CategoryLayoutExtVO } from './categoryLayoutExtVO';

export interface JsonListResultCategoryLayoutExtVO {
  code?: string;
  data?: JsonListResultCategoryLayoutExtVOData;
  hasNext?: boolean;
  message?: string;
  pageNo?: number;
  pageSize?: number;
  rows?: CategoryLayoutExtVO[];
  success?: boolean;
  total?: number;
}
