/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { JsonListResultCategoryDetailExtDtoData } from './jsonListResultCategoryDetailExtDtoData';
import type { CategoryDetailExtDto } from './categoryDetailExtDto';

export interface JsonListResultCategoryDetailExtDto {
  code?: string;
  data?: JsonListResultCategoryDetailExtDtoData;
  hasNext?: boolean;
  message?: string;
  pageNo?: number;
  pageSize?: number;
  rows?: CategoryDetailExtDto[];
  success?: boolean;
  total?: number;
}
