/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { JsonListResultCommodityData } from './jsonListResultCommodityData';
import type { Commodity } from './commodity';

export interface JsonListResultCommodity {
  code?: string;
  data?: JsonListResultCommodityData;
  hasNext?: boolean;
  message?: string;
  pageNo?: number;
  pageSize?: number;
  rows?: Commodity[];
  success?: boolean;
  total?: number;
}
