/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { JsonListResultStoreApplyInfoData } from './jsonListResultStoreApplyInfoData';
import type { StoreApplyInfo } from './storeApplyInfo';

export interface JsonListResultStoreApplyInfo {
  code?: string;
  data?: JsonListResultStoreApplyInfoData;
  hasNext?: boolean;
  message?: string;
  pageNo?: number;
  pageSize?: number;
  rows?: StoreApplyInfo[];
  success?: boolean;
  total?: number;
}
