/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { JsonListResultCategoryCommodityVOData } from './jsonListResultCategoryCommodityVOData';
import type { CategoryCommodityVO } from './categoryCommodityVO';

export interface JsonListResultCategoryCommodityVO {
  code?: string;
  data?: JsonListResultCategoryCommodityVOData;
  hasNext?: boolean;
  message?: string;
  pageNo?: number;
  pageSize?: number;
  rows?: CategoryCommodityVO[];
  success?: boolean;
  total?: number;
}
