/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { JsonListResultStoreInfoData } from './jsonListResultStoreInfoData';
import type { StoreInfo } from './storeInfo';

export interface JsonListResultStoreInfo {
  code?: string;
  data?: JsonListResultStoreInfoData;
  hasNext?: boolean;
  message?: string;
  pageNo?: number;
  pageSize?: number;
  rows?: StoreInfo[];
  success?: boolean;
  total?: number;
}
