/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { JsonListResultStoreResultInfoData } from './jsonListResultStoreResultInfoData';
import type { StoreResultInfo } from './storeResultInfo';

export interface JsonListResultStoreResultInfo {
  code?: string;
  data?: JsonListResultStoreResultInfoData;
  hasNext?: boolean;
  message?: string;
  pageNo?: number;
  pageSize?: number;
  rows?: StoreResultInfo[];
  success?: boolean;
  total?: number;
}
