/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { JsonResultData } from './jsonResultData';

export interface JsonResult {
  code?: string;
  data?: JsonResultData;
  message?: string;
  success?: boolean;
}
