/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface KapCommodityInfo {
  commodityCode?: string;
  commodityId?: string;
  commodityName?: string;
  createTime?: string;
  detailHtml?: string;
  forwardRanking?: number;
  id: string;
  isDeleted?: number;
  pv?: number;
  showStatus?: number;
  skuCode?: string;
  updateTime?: string;
  uv?: number;
  zfl?: number;
}
