/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type ListSysMenuTreeParams = { system?: string; tokenUserCode?: string; tokenUserName?: string; type?: string; menuType?: string; isAttributeSet?: string };
