/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { LogisticsSendListRequestLogisticsSendType } from './logisticsSendListRequestLogisticsSendType';
import type { LogisticsSendListRequestReceiveStatus } from './logisticsSendListRequestReceiveStatus';

/**
 * 发货列表分页查询
 */
export interface LogisticsSendListRequest {
  /** 卖家企业编号 */
  buyEnterpriseNo?: string;
  /** 创建时间结算时间 */
  endTime?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 发货单号 */
  logistSendNo?: string;
  /** 物流公司 */
  logisticsName?: string;
  /** 发货类型,ONCE:一次性发货,MANY:多次发货 */
  logisticsSendType?: LogisticsSendListRequestLogisticsSendType;
  /** 订单编号 */
  orderNo?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 发货状态,WAIT_REC:待收货,REJECT:拒绝收货,RECEIVED:已收货 */
  receiveStatus?: LogisticsSendListRequestReceiveStatus;
  /** 卖家企业编号 */
  sellerEnterpriseNo?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 创建时间开始时间 */
  startTime?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
