/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 发货状态,WAIT_REC:待收货,REJECT:拒绝收货,RECEIVED:已收货
 */
export type LogisticsSendListRequestReceiveStatus = typeof LogisticsSendListRequestReceiveStatus[keyof typeof LogisticsSendListRequestReceiveStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LogisticsSendListRequestReceiveStatus = {
  RECEIVED: 'RECEIVED',
  REJECT: 'REJECT',
  WAIT_REC: 'WAIT_REC',
} as const;
