/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 登录响应信息
 */
export interface LoginInfoResponse {
  /** 是否第一登录;{是：true，否：false} */
  isFirstLogin?: boolean;
  /** 登录成功状态;{登录成功：true,登录失败：false} */
  loginStatus?: boolean;
  /** 手机号 */
  mobile?: string;
  /** 刷新token */
  refreshToken?: string;
  /** 登录成功返回会话信息 */
  sessionInfo?: string;
}
