/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 收发货方式,seller_distribution:卖方配送
 */
export type LongAgreementDtoReceiptDeliveryType = typeof LongAgreementDtoReceiptDeliveryType[keyof typeof LongAgreementDtoReceiptDeliveryType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LongAgreementDtoReceiptDeliveryType = {
  seller_distribution: 'seller_distribution',
} as const;
