/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 货款顺序,payment_before_delivery:先款后货,payment_after_delivery:先货后款
 */
export type LongAgreementDtoGoodsType = typeof LongAgreementDtoGoodsType[keyof typeof LongAgreementDtoGoodsType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LongAgreementDtoGoodsType = {
  payment_after_delivery: 'payment_after_delivery',
  payment_before_delivery: 'payment_before_delivery',
} as const;
