/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 最后操作方(甲方,乙方),party_a:甲方,party_b:乙方
 */
export type LongAgreementLastOperator = typeof LongAgreementLastOperator[keyof typeof LongAgreementLastOperator];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LongAgreementLastOperator = {
  party_a: 'party_a',
  party_b: 'party_b',
} as const;
