/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 开票节点,after_payment_completed:付款完成后,after_order_effective:订单生效后,after_reconciliation_completed:对账完成后
 */
export type LongAgreementInvoiceNode = typeof LongAgreementInvoiceNode[keyof typeof LongAgreementInvoiceNode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LongAgreementInvoiceNode = {
  after_order_effective: 'after_order_effective',
  after_payment_completed: 'after_payment_completed',
  after_reconciliation_completed: 'after_reconciliation_completed',
} as const;
