/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 支付方式,unlimited:不限,balance_payment:余额支付,offline_payment:线下支付
 */
export type LongAgreementPaymentMethod = typeof LongAgreementPaymentMethod[keyof typeof LongAgreementPaymentMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LongAgreementPaymentMethod = {
  balance_payment: 'balance_payment',
  offline_payment: 'offline_payment',
  unlimited: 'unlimited',
} as const;
