/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 付款节点,after_invoicing_completed:开票完成后,after_reconciliation_completed:对账完成后
 */
export type LongAgreementPayNode = typeof LongAgreementPayNode[keyof typeof LongAgreementPayNode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LongAgreementPayNode = {
  after_invoicing_completed: 'after_invoicing_completed',
  after_reconciliation_completed: 'after_reconciliation_completed',
} as const;
