/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { OFileDto } from './oFileDto';
import type { LongAgreementVoBossStatus } from './longAgreementVoBossStatus';
import type { LongAgreementVoCommodityPriceMechanism } from './longAgreementVoCommodityPriceMechanism';
import type { LongAgreementGoodsDto } from './longAgreementGoodsDto';
import type { LongAgreementVoGoodsType } from './longAgreementVoGoodsType';
import type { LongAgreementVoInvoiceNode } from './longAgreementVoInvoiceNode';
import type { LongAgreementVoLastOperator } from './longAgreementVoLastOperator';
import type { LongAgreementVoPayNode } from './longAgreementVoPayNode';
import type { LongAgreementVoPaymentMethod } from './longAgreementVoPaymentMethod';
import type { LongAgreementVoPriceModel } from './longAgreementVoPriceModel';
import type { LongAgreementVoReceiptDeliveryType } from './longAgreementVoReceiptDeliveryType';
import type { LongAgreementVoReconciliationNode } from './longAgreementVoReconciliationNode';
import type { LongAgreementVoStatus } from './longAgreementVoStatus';
import type { LongAgreementVoType } from './longAgreementVoType';

/**
 * 长期合作
 */
export interface LongAgreementVo {
  /** 长协编号 */
  agreementNo?: string;
  /** 附件列表 */
  attachmentFileList?: OFileDto[];
  /** 附件,多个英文逗号分隔 */
  attachmentUrl?: string;
  attachmentUrlList?: string[];
  /** BOSS名称 */
  bossName?: string;
  /** BOSS编号 */
  bossNo?: string;
  /** BOSS审核原因 */
  bossReason?: string;
  /** BOSS审核状态,success:成功,failure:失败,processing:处理中 */
  bossStatus?: LongAgreementVoBossStatus;
  /** BOSS审核时间 */
  bossTime?: string;
  /** 商品价格机制,unification:供应商所有商品统一调价,custom:自定义商品调价 */
  commodityPriceMechanism?: LongAgreementVoCommodityPriceMechanism;
  createTime?: string;
  /** 协议结束时间 */
  dateEnd?: string;
  /** 协议开始时间 */
  dateStart?: string;
  /** 删除时间 */
  deleteTime?: string;
  /** 调价参数 */
  downRatio?: number;
  /** 合作创建企业编号 */
  enterpriseNo?: string;
  /** 长协商品列表 */
  goods?: LongAgreementGoodsDto[];
  /** 货款顺序,payment_before_delivery:先款后货,payment_after_delivery:先货后款 */
  goodsType?: LongAgreementVoGoodsType;
  id?: string;
  /** 开票节点,after_payment_completed:付款完成后,after_order_effective:订单生效后,after_reconciliation_completed:对账完成后 */
  invoiceNode?: LongAgreementVoInvoiceNode;
  /** 开票期限 */
  invoicePeriod?: number;
  /** 最后操作方(甲方,乙方),party_a:甲方,party_b:乙方 */
  lastOperator?: LongAgreementVoLastOperator;
  /** 发货物流公司名称 */
  logisticsCompanyName?: string;
  /** 发货物流公司编号 */
  logisticsCompanyNo?: string;
  /** 合作创建人 */
  memberName?: string;
  /** 合作创建人编号 */
  memberNo?: string;
  /** 甲方企业名称 */
  partyAEnterpriseName?: string;
  /** 甲方企业编号 */
  partyAEnterpriseNo?: string;
  /** 甲方发票统一信用代码 */
  partyAInvoiceLicenceNo?: string;
  /** 甲方发票抬头名称 */
  partyAInvoiceName?: string;
  /** 甲方发票抬头编号 */
  partyAInvoiceNo?: string;
  /** 甲方发票类型 */
  partyAInvoiceType?: string;
  /** 甲方操作时间 */
  partyAOperateTime?: string;
  /** 乙方企业名称 */
  partyBEnterpriseName?: string;
  /** 乙方企业编号 */
  partyBEnterpriseNo?: string;
  /** 乙方操作时间 */
  partyBOperateTime?: string;
  /** 付款节点,after_invoicing_completed:开票完成后,after_reconciliation_completed:对账完成后 */
  payNode?: LongAgreementVoPayNode;
  /** 付款期限 */
  payPeriod?: number;
  /** 支付方式,unlimited:不限,balance_payment:余额支付,offline_payment:线下支付 */
  paymentMethod?: LongAgreementVoPaymentMethod;
  /** 价格模式,proportion:销售价比例调整,absolute:销售价绝对值调整,fixed:固定价格 */
  priceModel?: LongAgreementVoPriceModel;
  /** 驳回原因 */
  reason?: string;
  /** 收发货方式,seller_distribution:卖方配送 */
  receiptDeliveryType?: LongAgreementVoReceiptDeliveryType;
  /** 对账节点,automatic:自动完成对账,after_confirm:确认收货后 */
  reconciliationNode?: LongAgreementVoReconciliationNode;
  /** 对账期限 */
  reconciliationPeriod?: number;
  /** 状态,init:初始,wait_confirm:待确认,rejected:已驳回,wait_effective:待生效,valid:已生效,wait_canceled:待取消,invalid:已失效 */
  status?: LongAgreementVoStatus;
  /** 纳税人识别号 */
  taxNumber?: string;
  /** 合作类型,purchase:采购合作,sale:销售合作 */
  type?: LongAgreementVoType;
  updateTime?: string;
}
