/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Money } from './money';
import type { LongAgreementGoodsDtoGoodsType } from './longAgreementGoodsDtoGoodsType';
import type { LongAgreementGoodsDtoPriceModel } from './longAgreementGoodsDtoPriceModel';

export interface LongAgreementGoodsDto {
  agreementNo?: string;
  commodityId: string;
  downRatio: number;
  finalPrice?: Money;
  goodsName: string;
  goodsSku: string;
  /** null,payment_before_delivery:先款后货,payment_after_delivery:先货后款 */
  goodsType?: LongAgreementGoodsDtoGoodsType;
  /** null,proportion:销售价比例调整,absolute:销售价绝对值调整,fixed:固定价格 */
  priceModel: LongAgreementGoodsDtoPriceModel;
  unit: string;
}
