/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 对账节点,automatic:自动完成对账,after_confirm:确认收货后
 */
export type LongAgreementDtoReconciliationNode = typeof LongAgreementDtoReconciliationNode[keyof typeof LongAgreementDtoReconciliationNode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LongAgreementDtoReconciliationNode = {
  after_confirm: 'after_confirm',
  automatic: 'automatic',
} as const;
