/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 合作类型,purchase:采购合作,sale:销售合作
 */
export type LongAgreementDtoType = typeof LongAgreementDtoType[keyof typeof LongAgreementDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LongAgreementDtoType = {
  purchase: 'purchase',
  sale: 'sale',
} as const;
