/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 状态,init:初始,wait_confirm:待确认,rejected:已驳回,wait_effective:待生效,valid:已生效,wait_canceled:待取消,invalid:已失效
 */
export type LongAgreementPageRequestStatus = typeof LongAgreementPageRequestStatus[keyof typeof LongAgreementPageRequestStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LongAgreementPageRequestStatus = {
  init: 'init',
  invalid: 'invalid',
  rejected: 'rejected',
  valid: 'valid',
  wait_canceled: 'wait_canceled',
  wait_confirm: 'wait_confirm',
  wait_effective: 'wait_effective',
} as const;
