/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { LongAgreementAuditRequestStatus } from './longAgreementAuditRequestStatus';

/**
 * 企业/供应商审核请求
 */
export interface LongAgreementAuditRequest {
  /** id */
  id?: string;
  /** 原因:失败时必传 */
  reason?: string;
  /** 状态;success:通过,failure:拒绝,success:成功,failure:失败,processing:处理中 */
  status?: LongAgreementAuditRequestStatus;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
