/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * null,proportion:销售价比例调整,absolute:销售价绝对值调整,fixed:固定价格
 */
export type LongAgreementGoodsDtoPriceModel = typeof LongAgreementGoodsDtoPriceModel[keyof typeof LongAgreementGoodsDtoPriceModel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LongAgreementGoodsDtoPriceModel = {
  absolute: 'absolute',
  fixed: 'fixed',
  proportion: 'proportion',
} as const;
