/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 用户状态,enable:启用,disable:停用
 */
export type MemberListRequestDisable = typeof MemberListRequestDisable[keyof typeof MemberListRequestDisable];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberListRequestDisable = {
  disable: 'disable',
  enable: 'enable',
} as const;
