/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface MemberEmployeeAssociateRequest {
  /** 企业编码 */
  enterpriseNo?: string;
  /** 会员编码 */
  memberNo?: string;
  /** 角色(多个英文逗号,分隔), 'manager':'管理员';'operator':'运营人员';'finance':'财务' */
  roles?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
