/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface MemberRoleTypeRequest {
  /** 企业编码 */
  enterpriseNo?: string;
  /** 角色编码 */
  name?: string;
  /** 角色名称 */
  title?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
