/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 企业员人新增请求参数
 */
export interface MemberEmployeeAddRequest {
  /** 身份证号 */
  certNo?: string;
  /** 企业编码 */
  enterpriseNo?: string;
  /** 手机号 */
  mobile?: string;
  /** 密码 */
  password?: string;
  /** 真实姓名 */
  realName?: string;
  /** 角色(多个英文逗号,分隔), 'manager':'管理员';'operator':'运营人员';'finance':'财务' */
  roles?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
