/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { MemberListRequestDisable } from './memberListRequestDisable';

/**
 * 会员列表请求参数
 */
export interface MemberListRequest {
  /** 所属企业名称 */
  comName?: string;
  /** 日期结束 */
  createTimeEnd?: string;
  /** 日期开始 */
  createTimeStart?: string;
  /** 用户状态,enable:启用,disable:停用 */
  disable?: MemberListRequestDisable;
  /** 所属企业编码 */
  enterpriseNo?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 会员编码 */
  memberNo?: string;
  /** 手机号 */
  mobile?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 姓名 */
  realName?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
