/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 是否禁用,enable:启用,disable:停用
 */
export type MemberListVoDisable = typeof MemberListVoDisable[keyof typeof MemberListVoDisable];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberListVoDisable = {
  disable: 'disable',
  enable: 'enable',
} as const;
