/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { MemberDisable } from './memberDisable';
import type { MemberEnterpriseCreator } from './memberEnterpriseCreator';
import type { MemberEnterpriseStatus } from './memberEnterpriseStatus';
import type { MemberStatus } from './memberStatus';

/**
 * 会员
 */
export interface Member {
  /** 身份证号 */
  certNo?: string;
  /** 备注 */
  comments?: string;
  createTime?: string;
  /** 是否禁用,enable:启用,disable:停用 */
  disable?: MemberDisable;
  enterpriseAuditTime?: string;
  /** null,yes:是,no:否 */
  enterpriseCreator?: MemberEnterpriseCreator;
  /** 企业编号 */
  enterpriseNo?: string;
  /** null,success:成功,failure:失败,processing:处理中 */
  enterpriseStatus?: MemberEnterpriseStatus;
  id?: string;
  /** 会员编码 */
  memberNo?: string;
  /** 手机号 */
  mobile?: string;
  nickname?: string;
  /** 操作员编码 */
  operatorNo?: string;
  /** 真实姓名 */
  realName?: string;
  /** 原因 */
  reason?: string;
  /** 账号状态,success:成功,failure:失败,processing:处理中 */
  status?: MemberStatus;
  /** 账号类型 */
  type?: string;
  typeList?: string[];
  updateTime?: string;
}
