/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * null,enable:启用,disable:停用
 */
export type MemberDtoDisable = typeof MemberDtoDisable[keyof typeof MemberDtoDisable];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberDtoDisable = {
  disable: 'disable',
  enable: 'enable',
} as const;
