/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { MemberDtoAccountBossStatus } from './memberDtoAccountBossStatus';
import type { MemberDtoAccountStatus } from './memberDtoAccountStatus';
import type { MemberDtoBankStatus } from './memberDtoBankStatus';
import type { MemberDtoBossStatus } from './memberDtoBossStatus';
import type { MemberDtoContractStatus } from './memberDtoContractStatus';
import type { MemberDtoDisable } from './memberDtoDisable';
import type { MemberDtoEnterpriseCreator } from './memberDtoEnterpriseCreator';
import type { MemberDtoEnterpriseStatus } from './memberDtoEnterpriseStatus';
import type { MemberDtoEnterpriseType } from './memberDtoEnterpriseType';
import type { MemberDtoIsCustomer } from './memberDtoIsCustomer';
import type { MemberDtoSelf } from './memberDtoSelf';
import type { MemberDtoSignStatus } from './memberDtoSignStatus';

export interface MemberDto {
  accountBossReason?: string;
  /** null,success:成功,failure:失败,processing:处理中 */
  accountBossStatus?: MemberDtoAccountBossStatus;
  accountReason?: string;
  /** null,success:成功,failure:失败,processing:处理中 */
  accountStatus?: MemberDtoAccountStatus;
  bankReason?: string;
  /** null,success:成功,failure:失败,processing:处理中 */
  bankStatus?: MemberDtoBankStatus;
  bossReason?: string;
  /** null,success:成功,failure:失败,processing:处理中 */
  bossStatus?: MemberDtoBossStatus;
  bossTime?: string;
  certNo: string;
  comments?: string;
  /** null,success:成功,failure:失败,processing:处理中 */
  contractStatus?: MemberDtoContractStatus;
  createTime?: string;
  /** null,enable:启用,disable:停用 */
  disable: MemberDtoDisable;
  enterpriseAuditTime?: string;
  /** null,yes:是,no:否 */
  enterpriseCreator?: MemberDtoEnterpriseCreator;
  enterpriseName?: string;
  enterpriseNo?: string;
  /** null,success:成功,failure:失败,processing:处理中 */
  enterpriseStatus?: MemberDtoEnterpriseStatus;
  /** null,buyer:企业,seller:供应商 */
  enterpriseType?: MemberDtoEnterpriseType;
  id?: string;
  /** null,yes:是,no:否 */
  isCustomer?: MemberDtoIsCustomer;
  memberNo: string;
  mobile: string;
  nickname?: string;
  operatorNo?: string;
  payMethod: string;
  realName: string;
  reason?: string;
  /** null,yes:是,no:否 */
  self: MemberDtoSelf;
  signReason?: string;
  /** null,success:成功,failure:失败,processing:处理中 */
  signStatus?: MemberDtoSignStatus;
  type: string;
  typeList?: string[];
  updateTime?: string;
}
