/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type MemberTypeListItem = typeof MemberTypeListItem[keyof typeof MemberTypeListItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberTypeListItem = {
  finance: 'finance',
  manager: 'manager',
  operator: 'operator',
} as const;
