/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * null,buyer:企业,seller:供应商
 */
export type MemberDtoEnterpriseType = typeof MemberDtoEnterpriseType[keyof typeof MemberDtoEnterpriseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberDtoEnterpriseType = {
  buyer: 'buyer',
  seller: 'seller',
} as const;
