/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { MemberListVoDisable } from './memberListVoDisable';
import type { MemberListVoEnterpriseCreator } from './memberListVoEnterpriseCreator';
import type { MemberListVoEnterpriseStatus } from './memberListVoEnterpriseStatus';
import type { MemberListVoStatus } from './memberListVoStatus';

export interface MemberListVo {
  /** 身份证号 */
  certNo?: string;
  /** 企业名称 */
  comName?: string;
  /** 备注 */
  comments?: string;
  createTime?: string;
  /** 是否禁用,enable:启用,disable:停用 */
  disable?: MemberListVoDisable;
  enterpriseAuditTime?: string;
  /** null,yes:是,no:否 */
  enterpriseCreator?: MemberListVoEnterpriseCreator;
  /** 企业编号 */
  enterpriseNo?: string;
  /** null,success:成功,failure:失败,processing:处理中 */
  enterpriseStatus?: MemberListVoEnterpriseStatus;
  id?: string;
  /** 会员编码 */
  memberNo?: string;
  /** 手机号 */
  mobile?: string;
  nickname?: string;
  /** 操作员编码 */
  operatorNo?: string;
  /** 真实姓名 */
  realName?: string;
  /** 原因 */
  reason?: string;
  /** 角色名称列表 */
  roleList?: string[];
  /** 账号状态,success:成功,failure:失败,processing:处理中 */
  status?: MemberListVoStatus;
  /** 账号类型 */
  type?: string;
  typeList?: string[];
  updateTime?: string;
}
