/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface OFileDto {
  /** 附件名称 */
  name?: string;
  /** 附件大小 */
  size?: number;
  /** 附件链接 */
  url?: string;
}
