/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 订单状态,INIT:初始化,WAIT_CONTRACT:待签署,WAIT_PAY:待付款,WAIT_CONFIRM_AMOUNT:待确认付款,WAIT_SEND:待发货,PART_ISSUED:部分发货,ISSUED:发货完成,FINISH:已完成,CANCEL:已取消,REFUND_APPLY_ING:退单申请中,REFUND:已退单,REFUND_GOODS_ING:退货申请中,REFUND_PART_GOODS:部分退货,REFUND_GOODS:已退货
 */
export type OrderListQueryRequestOrderStatus = typeof OrderListQueryRequestOrderStatus[keyof typeof OrderListQueryRequestOrderStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderListQueryRequestOrderStatus = {
  CANCEL: 'CANCEL',
  FINISH: 'FINISH',
  INIT: 'INIT',
  ISSUED: 'ISSUED',
  PART_ISSUED: 'PART_ISSUED',
  REFUND: 'REFUND',
  REFUND_APPLY_ING: 'REFUND_APPLY_ING',
  REFUND_GOODS: 'REFUND_GOODS',
  REFUND_GOODS_ING: 'REFUND_GOODS_ING',
  REFUND_PART_GOODS: 'REFUND_PART_GOODS',
  WAIT_CONFIRM_AMOUNT: 'WAIT_CONFIRM_AMOUNT',
  WAIT_CONTRACT: 'WAIT_CONTRACT',
  WAIT_PAY: 'WAIT_PAY',
  WAIT_SEND: 'WAIT_SEND',
} as const;
