/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { OrderListQueryRequestOrderStatus } from './orderListQueryRequestOrderStatus';
import type { OrderListQueryRequestPayMethod } from './orderListQueryRequestPayMethod';
import type { OrderListQueryRequestSelfStatus } from './orderListQueryRequestSelfStatus';
import type { OrderListQueryRequestSettleStatus } from './orderListQueryRequestSettleStatus';

/**
 * 订单分页查询
 */
export interface OrderListQueryRequest {
  /** 活动编码 */
  activityCode?: string;
  /** 买家名称 */
  buyEnterpriseName?: string;
  /** 买家编码 */
  buyEnterpriseNo?: string;
  /** 下单会员编码 */
  buyUserId?: string;
  /** 下单会员手机 */
  buyUserPhone?: string;
  /** 结束时间 */
  endTime?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 订单号 */
  orderNo?: string;
  /** 订单状态,INIT:初始化,WAIT_CONTRACT:待签署,WAIT_PAY:待付款,WAIT_CONFIRM_AMOUNT:待确认付款,WAIT_SEND:待发货,PART_ISSUED:部分发货,ISSUED:发货完成,FINISH:已完成,CANCEL:已取消,REFUND_APPLY_ING:退单申请中,REFUND:已退单,REFUND_GOODS_ING:退货申请中,REFUND_PART_GOODS:部分退货,REFUND_GOODS:已退货 */
  orderStatus?: OrderListQueryRequestOrderStatus;
  /** 页码(默认值:1) */
  page?: number;
  /** 支付方式,OFFLINE_PAY:线下支付,BALANCE_PAY:余额支付,CREDIT_PAY:授信支付 */
  payMethod?: OrderListQueryRequestPayMethod;
  /** 商品名称 */
  productName?: string;
  /** 是否自营,yes:是,no:否 */
  selfStatus?: OrderListQueryRequestSelfStatus;
  /** 卖家名称 */
  sellerEnterpriseName?: string;
  /** 结算状态,WAIT:待结算,PART:部分结算,SETTED:已结算,CLOSED:已关闭 */
  settleStatus?: OrderListQueryRequestSettleStatus;
  /** 店铺名称 */
  shopName?: string;
  /** 店铺编码 */
  shopNo?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 开始时间 */
  startTime?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
