/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { QualificationCategoryDto } from './qualificationCategoryDto';

export interface PageInfoQualificationCategoryDto {
  countOfCurrentPage?: number;
  currentPage?: number;
  next?: boolean;
  pageResults?: QualificationCategoryDto[];
  previous?: boolean;
  totalCount?: number;
  totalPage?: number;
}
