/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { StoreInfo0 } from './storeInfo0';

export interface PageInfoStoreInfo {
  countOfCurrentPage?: number;
  currentPage?: number;
  next?: boolean;
  pageResults?: StoreInfo0[];
  previous?: boolean;
  totalCount?: number;
  totalPage?: number;
}
