/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CommodityInfo } from './commodityInfo';

export interface PageInfoCommodityInfo {
  countOfCurrentPage?: number;
  currentPage?: number;
  next?: boolean;
  pageResults?: CommodityInfo[];
  previous?: boolean;
  totalCount?: number;
  totalPage?: number;
}
