/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CategoryQualificationResultInfo } from './categoryQualificationResultInfo';

export interface PageInfoCategoryQualificationResultInfo {
  countOfCurrentPage?: number;
  currentPage?: number;
  next?: boolean;
  pageResults?: CategoryQualificationResultInfo[];
  previous?: boolean;
  totalCount?: number;
  totalPage?: number;
}
