/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { StoreQualificationAuditPageResultDto } from './storeQualificationAuditPageResultDto';

export interface PageInfoStoreQualificationAuditPageResultDto {
  countOfCurrentPage?: number;
  currentPage?: number;
  next?: boolean;
  pageResults?: StoreQualificationAuditPageResultDto[];
  previous?: boolean;
  totalCount?: number;
  totalPage?: number;
}
