/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Money } from './money';
import type { PaymentOrderContainsLongAgreement } from './paymentOrderContainsLongAgreement';
import type { PaymentOrderInvoiced } from './paymentOrderInvoiced';
import type { PaymentOrderPayScene } from './paymentOrderPayScene';
import type { PaymentOrderPayedUnfreeze } from './paymentOrderPayedUnfreeze';
import type { PaymentOrderPayeeAccountType } from './paymentOrderPayeeAccountType';
import type { PaymentOrderPayerAccountType } from './paymentOrderPayerAccountType';
import type { PaymentOrderPaymentDirection } from './paymentOrderPaymentDirection';
import type { PaymentOrderPaymentOrderStatus } from './paymentOrderPaymentOrderStatus';
import type { PaymentOrderProductSettleMethod } from './paymentOrderProductSettleMethod';

/**
 * 付款单
 */
export interface PaymentOrder {
  agreementNo?: string;
  /** 金额 */
  amount?: Money;
  attachmentPath?: string;
  /** 对账单编码 */
  billReconciliationNo?: string;
  /** 买家名称 */
  buyerName?: string;
  /** 买家编码 */
  buyerNo?: string;
  comments?: string;
  /** null,yes:是,no:否 */
  containsLongAgreement?: PaymentOrderContainsLongAgreement;
  createTime?: string;
  /** 支付完成时间 */
  finishTime?: string;
  gid: string;
  id?: string;
  invoiceBodyId?: string;
  invoiceId?: string;
  /** null,yes:是,no:否 */
  invoiced?: PaymentOrderInvoiced;
  orderNos?: string;
  /** 支付场景,ONLINE:线上,OFFLINE:线下 */
  payScene?: PaymentOrderPayScene;
  /** null,yes:是,no:否 */
  payedUnfreeze?: PaymentOrderPayedUnfreeze;
  /** 收款人账户编码 */
  payeeAccountNo?: string;
  /** 收款人账户类型,QZT:企账通,BANK:银行 */
  payeeAccountType?: PaymentOrderPayeeAccountType;
  /** 收款人企账通银行账号 */
  payeeBankAccountCoreNo?: string;
  payeeBankAccountName?: string;
  payeeBankCardNo?: string;
  /** 收款人开户行名称 */
  payeeBankName?: string;
  payeeFeeAmount?: Money;
  /** 收款人名称 */
  payeeName?: string;
  /** 收款人编码 */
  payeeNo?: string;
  /** 付款账号 */
  payerAccountNo?: string;
  /** 付款账户类型,QZT:企账通,BANK:银行 */
  payerAccountType?: PaymentOrderPayerAccountType;
  payerBankAccountCoreNo?: string;
  payerBankAccountName?: string;
  payerBankCardNo?: string;
  payerBankName?: string;
  payerFeeAmount?: Money;
  /** 付款人名称 */
  payerName?: string;
  /** 付款人编码 */
  payerNo?: string;
  /** 付款方向,FORWARD:正向,REVERSE:逆向 */
  paymentDirection?: PaymentOrderPaymentDirection;
  /** 付款单号 */
  paymentOrderNo?: string;
  /** 状态,INIT:初始化,WAIT_BUYER_CONFIRM:待买家确认,WAIT_SELLER_CONFIRM:待卖家确认,WAIT_CONFIRM_INVOICING_INFO:待确认开票信息,COMPLETED:已完成,BILL_REJECTED:对账驳回,DELETD:已删除,WAIT_PAY:待支付,PROCESSING:支付中,PAY_PART:部分支付,PAY_FAIL:支付失败,PAID:已支付,WAIT_SELLER_CONFIRM_BILL:待卖家确认对账单,CLOSED:已关闭 */
  paymentOrderStatus?: PaymentOrderPaymentOrderStatus;
  /** 商品结算方式,BEFORE_PRODUCT:先货后款,BEFORE_PAY:先款后货 */
  productSettleMethod?: PaymentOrderProductSettleMethod;
  /** 卖家名称 */
  sellerName?: string;
  /** 卖家编码 */
  sellerNo?: string;
  unfrozenAmount?: Money;
  unpaidBillNos?: string;
  upAttachmentDate?: string;
  updateTime?: string;
}
