/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 支付方式,OFFLINE_PAY:线下支付,BALANCE_PAY:余额支付,CREDIT_PAY:授信支付
 */
export type PaymentRecordInfoVOPayMethodEnum = typeof PaymentRecordInfoVOPayMethodEnum[keyof typeof PaymentRecordInfoVOPayMethodEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentRecordInfoVOPayMethodEnum = {
  BALANCE_PAY: 'BALANCE_PAY',
  CREDIT_PAY: 'CREDIT_PAY',
  OFFLINE_PAY: 'OFFLINE_PAY',
} as const;
