/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 付款账户类型,QZT:企账通,BANK:银行
 */
export type PaymentOrderPayerAccountType = typeof PaymentOrderPayerAccountType[keyof typeof PaymentOrderPayerAccountType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentOrderPayerAccountType = {
  BANK: 'BANK',
  QZT: 'QZT',
} as const;
