/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 付款方向,FORWARD:正向,REVERSE:逆向
 */
export type PaymentOrderPaymentDirection = typeof PaymentOrderPaymentDirection[keyof typeof PaymentOrderPaymentDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentOrderPaymentDirection = {
  FORWARD: 'FORWARD',
  REVERSE: 'REVERSE',
} as const;
