/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 收款人账户类型,QZT:企账通,BANK:银行
 */
export type PaymentOrderPayeeAccountType = typeof PaymentOrderPayeeAccountType[keyof typeof PaymentOrderPayeeAccountType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentOrderPayeeAccountType = {
  BANK: 'BANK',
  QZT: 'QZT',
} as const;
