/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Money } from './money';
import type { PaymentRecordInfoVOPayMethodEnum } from './paymentRecordInfoVOPayMethodEnum';
import type { PaymentRecordInfoVOPaymentOrderStatus } from './paymentRecordInfoVOPaymentOrderStatus';

/**
 * 订单详情支付记录实体
 */
export interface PaymentRecordInfoVO {
  /** 支付金额 */
  amount?: Money;
  /** 流水号 */
  channelOrderNo?: string;
  /** 认款时间 */
  confirmTime?: string;
  /** 支付方式,OFFLINE_PAY:线下支付,BALANCE_PAY:余额支付,CREDIT_PAY:授信支付 */
  payMethodEnum?: PaymentRecordInfoVOPayMethodEnum;
  /** 支付时间 */
  payTime?: string;
  /** 对手方银行名称 */
  payerBankName?: string;
  /** 对手方银行账号 */
  payerBankNo?: string;
  /** 对手方账户名称 */
  payerMemberName?: string;
  /** 付款单号 */
  paymentOrderNo?: string;
  /** 支付状态,INIT:初始化,WAIT_BUYER_CONFIRM:待买家确认,WAIT_SELLER_CONFIRM:待卖家确认,WAIT_CONFIRM_INVOICING_INFO:待确认开票信息,COMPLETED:已完成,BILL_REJECTED:对账驳回,DELETD:已删除,WAIT_PAY:待支付,PROCESSING:支付中,PAY_PART:部分支付,PAY_FAIL:支付失败,PAID:已支付,WAIT_SELLER_CONFIRM_BILL:待卖家确认对账单,CLOSED:已关闭 */
  paymentOrderStatus?: PaymentRecordInfoVOPaymentOrderStatus;
}
