/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 支付场景,ONLINE:线上,OFFLINE:线下
 */
export type PaymentOrderPayScene = typeof PaymentOrderPayScene[keyof typeof PaymentOrderPayScene];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentOrderPayScene = {
  OFFLINE: 'OFFLINE',
  ONLINE: 'ONLINE',
} as const;
