/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { PaymentOrderPageQueryRequestSearchEQPaymentOrderStatus } from './paymentOrderPageQueryRequestSearchEQPaymentOrderStatus';

/**
 * 付款单分页查询
 */
export interface PaymentOrderPageQueryRequest {
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 页码(默认值:1) */
  page?: number;
  /** 对账单号 */
  search_EQ_billReconciliationNo?: string;
  /** 子订单号 */
  search_EQ_orderNo?: string;
  /** 付款单号 */
  search_EQ_paymentOrderNo?: string;
  /** 状态,INIT:初始化,WAIT_BUYER_CONFIRM:待买家确认,WAIT_SELLER_CONFIRM:待卖家确认,WAIT_CONFIRM_INVOICING_INFO:待确认开票信息,COMPLETED:已完成,BILL_REJECTED:对账驳回,DELETD:已删除,WAIT_PAY:待支付,PROCESSING:支付中,PAY_PART:部分支付,PAY_FAIL:支付失败,PAID:已支付,WAIT_SELLER_CONFIRM_BILL:待卖家确认对账单,CLOSED:已关闭 */
  search_EQ_paymentOrderStatus?: PaymentOrderPageQueryRequestSearchEQPaymentOrderStatus;
  /** 开始生成时间，请严格按照提供的示例时间格式传入精确到秒！！ */
  search_GTE_createTime?: string;
  /** 结束生成时间，请严格按照提供的示例时间格式传入精确到秒！！ */
  search_LTE_createTime?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
