/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface PriceQuotation {
  /** 市编码 */
  cityCode?: string;
  /** 市名称 */
  cityName?: string;
  /** 创建人 */
  createBy?: string;
  createTime?: string;
  /** 日期 */
  dateTime?: string;
  /** 商品编码 */
  goodsCode?: string;
  /** 商品名称 */
  goodsName?: string;
  /** 商品价格 */
  goodsPrice?: number;
  /** 商品价格变动 */
  goodsPriceChange?: number;
  /** 商品类型 */
  goodsType?: string;
  /** 商品类型名称 */
  goodsTypeName?: string;
  id?: string;
  /** 省编码 */
  provinceCode?: string;
  /** 省名称 */
  provinceName?: string;
  /** 更新人 */
  updateBy?: string;
  updateTime?: string;
}
