/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface PriceQuotationUpdateReq {
  /** 日期 */
  dateTime?: string;
  /** 商品价格 */
  goodsPrice?: string;
  /** id */
  id?: string;
}
