/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface QualificationDto {
  /** 资质编码 */
  code?: string;
  /** 创建时间 */
  createTime?: string;
  /** 创建人编码 */
  creatorCode?: string;
  /** 示例图 */
  diagram?: string;
  /** 过期时间 */
  expirationTime?: string;
  /** ID */
  id?: string;
  /** 证照名称 */
  name?: string;
  /** 资质分类编码 */
  qualificationCategoryCode?: number;
  /** 资质分类名称 */
  qualificationCategoryName?: string;
  /** 备注 */
  remark?: string;
  /** 状态 1正常 0已删除 */
  status?: number;
  /** 更新时间 */
  updateTime?: string;
}
