/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { QualificationDto } from './qualificationDto';

export interface QualificationCategoryDto {
  /** 特殊资质列表 */
  children?: QualificationDto[];
  /** 资质分类编码 */
  code?: string;
  /** 创建时间 */
  createTime?: string;
  /** 创建人 */
  creatorCode?: string;
  /** icon */
  icon?: string;
  /** Id */
  id?: string;
  /** 资质分类名称 */
  name?: string;
  /** 备注 */
  remark?: string;
  /** 状态 1正常 0已删除 */
  status?: number;
  /** 更新时间 */
  updateTime?: string;
}
