/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export type RefundApplyExportRefundApplyStatus = typeof RefundApplyExportRefundApplyStatus[keyof typeof RefundApplyExportRefundApplyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RefundApplyExportRefundApplyStatus = {
  APPROVED: 'APPROVED',
  CONFIRM_REFUND: 'CONFIRM_REFUND',
  FINISH: 'FINISH',
  NO_APPROVED: 'NO_APPROVED',
  REFUND_FAIL: 'REFUND_FAIL',
  REFUND_ING: 'REFUND_ING',
  WAIT_APPROVED: 'WAIT_APPROVED',
  WAIT_REFUND: 'WAIT_REFUND',
} as const;
