/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { RefundListQueryRequestRefundApplyStatus } from './refundListQueryRequestRefundApplyStatus';
import type { RefundListQueryRequestSelfStatus } from './refundListQueryRequestSelfStatus';

/**
 * 退单列表分页查询
 */
export interface RefundListQueryRequest {
  /** 买家企业名称 */
  buyEnterpriseName?: string;
  /** 买家企业编号 */
  buyEnterpriseNo?: string;
  /** 创建时间结算时间 */
  endTime?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 订单号 */
  orderNo?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 退单状态,WAIT_APPROVED:待审核,APPROVED:审核通过,NO_APPROVED:审核不通过,WAIT_REFUND:待退款,CONFIRM_REFUND:待确认退款,REFUND_ING:退款中,REFUND_FAIL:退款失败,FINISH:已退单 */
  refundApplyStatus?: RefundListQueryRequestRefundApplyStatus;
  /** 退单编号 */
  refundNo?: string;
  /** 退单原因 */
  refundReason?: string;
  /** 是否自营,yes:是,no:否 */
  selfStatus?: RefundListQueryRequestSelfStatus;
  /** 卖家企业名称 */
  sellerEnterpriseName?: string;
  /** 卖家企业编号 */
  sellerEnterpriseNo?: string;
  /** 店铺名称 */
  shopName?: string;
  /** 店铺编码 */
  shopNo?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 创建时间开始时间 */
  startTime?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
