/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { RefundApplyExportRefundApplyStatus } from './refundApplyExportRefundApplyStatus';
import type { RefundApplyExportSelfStatus } from './refundApplyExportSelfStatus';

export type RefundApplyExportParams = { buyEnterpriseName?: string; buyEnterpriseNo?: string; endTime?: string; isPage?: boolean; orderNo?: string; page?: number; refundApplyStatus?: RefundApplyExportRefundApplyStatus; refundNo?: string; refundReason?: string; selfStatus?: RefundApplyExportSelfStatus; sellerEnterpriseName?: string; sellerEnterpriseNo?: string; shopName?: string; shopNo?: string; size?: number; startTime?: string; tokenUserCode?: string; tokenUserName?: string };
