/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 第一次登陆重置密码
 */
export interface ResetLoginPwdRequest {
  /** 登录账户 */
  account: string;
  /** 手机验证码 */
  code: string;
  /** 确认密码 */
  confirmPassword: string;
  /** 手机号码 */
  mobile: string;
  /** 新密码 */
  password: string;
}
