/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 返回数据
 */
export type ResultSysDynamicFormInstanceV2DetailResponseData = { [key: string]: any };
