/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { IwubidaPageResultCMS内容拓展实体 } from './iwubidaPageResultCMS内容拓展实体';

export interface ResultIwubidaPageResultCMS内容拓展实体 {
  /** 业务码->200:处理成功,500-业务逻辑错误,1005-服务端全局错误统一提示语;其他业务码视接口返回定义 */
  code?: string;
  /** 返回数据 */
  data?: IwubidaPageResultCMS内容拓展实体;
  /** 技术异常信息 */
  exceptionMsg?: string;
  /** 提示语言(用户视图语言) */
  message?: string;
  /** 是否成功(code=200,为true;code多值时刻体现作用方便判断):true=200-成功,false-失败结合code处理相应逻辑 */
  success?: boolean;
}
