/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Resource } from './resource';

export interface Role {
  createTime?: string;
  descn: string;
  id?: string;
  name: string;
  orgId?: string;
  rescs?: Resource[];
  updateTime?: string;
}
