/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 登录入参
 */
export interface SessionCreateRequest {
  /** 登录账户 */
  account: string;
  /** 验证码标识符 */
  captchaKey: string;
  /** 验证码 */
  code: string;
  /** 账户密码 */
  password: string;
}
