/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SettleOrderPageQueryRequestSearchEQSettleStatus } from './settleOrderPageQueryRequestSearchEQSettleStatus';
import type { SettleOrderPageQueryRequestSearchEQStatus } from './settleOrderPageQueryRequestSearchEQStatus';

/**
 * 结算单列表
 */
export interface SettleOrderPageQueryRequest {
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 页码(默认值:1) */
  page?: number;
  /** 精准查询关联订单号 */
  search_EQ_orderNo?: string;
  /** 结算单号 */
  search_EQ_settleNo?: string;
  /** 结算状态,WAIT:待结算,PART:部分结算,SETTED:已结算,CLOSED:已关闭 */
  search_EQ_settleStatus?: SettleOrderPageQueryRequestSearchEQSettleStatus;
  /** 结算状态-前端值传错了兼容写法,WAIT:待结算,PART:部分结算,SETTED:已结算,CLOSED:已关闭 */
  search_EQ_status?: SettleOrderPageQueryRequestSearchEQStatus;
  /** 买家企业 */
  search_LIKE_buyerName?: string;
  /** 模糊查询关联订单号 */
  search_LIKE_orderNo?: string;
  /** 卖家企业 */
  search_LIKE_sellerName?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
