/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 货物管理分页查询
 */
export interface SkuListQueryRequest {
  /** 商品编码 */
  commodityCode?: string;
  /** 创建开始时间 */
  gteCreateTime?: string;
  /** id */
  id?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 创建结束时间 */
  lteCreateTime?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 是否自营【1自营 0非自营】 */
  proprietary?: string;
  /** 上下架状态【0->下架；1->上架；2->待上架；3->违规下架；】 */
  publishStatus?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** sku编码 */
  skuCode?: string;
  /** 创建日期开始 */
  skuGteCreateTime?: string;
  /** 更新日期开始 */
  skuGteUpdateTime?: string;
  /** 创建日期结束 */
  skuLteCreateTime?: string;
  /** 更新日期结束 */
  skuLteUpdateTime?: string;
  /** sku名称 */
  skuName?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
