/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 验证码获取
 */
export interface SmsSendCodeRequest {
  /** 手机号码 */
  mobile: string;
  /** 验证码类型{login:登录,reset_pwd:重置密码} */
  type: string;
}
