/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 短信功能表单对象模型
 */
export interface SmsUpdatePasswordEditRequest {
  /** 接收人手机号 */
  mobile: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** 接收人收到得验证码（验证码验证得时候 传参） */
  verifyCode?: string;
}
