/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 标品列表分页查询
 */
export interface StandardStockQueryRequest {
  /** 平台类目 */
  categoryName?: string;
  /** 创建人 */
  createdBy?: string;
  /** 删除状态 */
  deleteStatus?: string;
  /** 创建开始时间 */
  gteCreateTime?: string;
  /** id */
  id?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 创建结束时间 */
  lteCreateTime?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 页量(默认值:10) */
  size?: number;
  /** 标准商品编码 */
  standardCommodityCode?: string;
  /** 标准商品名称 */
  standardCommodityName?: string;
  /** 状态 */
  status?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
