/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { StorePopularProduct } from './storePopularProduct';

export interface StorePopularDetail {
  /** 店铺商品 */
  products: StorePopularProduct[];
  /** 店铺序列 */
  sequence: number;
  /** 店铺Id */
  storeId: string;
}
