/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { StorePopularDetail } from './storePopularDetail';

/**
 * 热门店铺编辑入参
 */
export interface StorePopularRequest {
  /** 店铺信息 */
  stores: StorePopularDetail[];
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
