/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface StoreQualificationAuditViewResultDto {
  /** 申请类型 1新增 0更新 */
  applyType?: number;
  /** 状态 待审核0 审核通过1 审核驳回-1 */
  auditStatus?: number;
  /** 审核人编码 */
  auditorCode?: string;
  /** 审核人名称 */
  auditorName?: string;
  /** 有效期起 有效期为null为长期有效 */
  begExpireTime?: string;
  /** 企业名称 */
  comName?: string;
  /** 创建时间 */
  createTime?: string;
  /** 申请人会员编码 */
  creatorCode?: string;
  /** 申请人会员名称 */
  creatorName?: string;
  /** 示例图 */
  diagram?: string;
  /** 有效期止 有效期为null为长期有效 */
  endExpireTime?: string;
  /** 企业编码 */
  enterpriseNo?: string;
  /** 0表示已过期，1表示未过期 */
  expiredStatus?: number;
  /** ID */
  id?: string;
  /** 资质编码 */
  qualificationCode?: string;
  /** 证照名称 */
  qualificationName?: string;
  /** 驳回原因 */
  rejectReason?: string;
  /** snapshot */
  snapshot?: string;
  /** 更新时间 */
  updateTime?: string;
  /** 证照图片 */
  url?: string;
}
