/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface StoreQualificationInfoRequest {
  auditStatus?: number;
  begCreateTime?: string;
  comName?: string;
  endCreateTime?: string;
  enterpriseNo?: string;
  page?: number;
  qualificationCode?: string;
  qualificationName?: string;
  size?: number;
  /** 现在时刻 */
  time?: string;
}
