/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface StorePopularProduct {
  /** 商品id */
  commodityId: string;
  /** 商品序列 */
  sequence: number;
  /** 店铺Id */
  storeId: string;
}
