/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 店铺列表查询请请求
 */
export interface StoreListRequest {
  /** 创建时间开始 */
  begTime?: string;
  /** 创建时间结束 */
  endTime?: string;
  /** 企业编码 */
  enterpriseId?: string;
  /** 企业名称 */
  enterpriseName?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 页码(默认值:1) */
  page?: number;
  /** 是否热门店铺 0非热门 1热门 */
  popular?: number;
  /** 页量(默认值:10) */
  size?: number;
  /** 店铺编码 */
  storeId?: string;
  /** 店铺名称 */
  storeName?: string;
  /** 是否自营 0非自营 1自营 */
  storetype?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
