/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { CommodityCategoryInfo } from './commodityCategoryInfo';
import type { CommodityInfo } from './commodityInfo';

/**
 * 店铺详情
 */
export interface StoreInfo {
  /** 开始营业时间 */
  beginTime?: string;
  /** 分类 */
  categories?: CommodityCategoryInfo[];
  /** 分类id,以逗号分隔 */
  categorys?: string;
  /** 自定义配置商品 */
  commodityInfos?: CommodityInfo[];
  /** 联系人 */
  contactName?: string;
  /** 联系电话 */
  contactPhone?: string;
  /** 创建时间 */
  createTime?: string;
  /** 店铺描述 */
  description?: string;
  /** 结束营业时间 */
  endTime?: string;
  /** 企业编码 */
  enterpriseId?: string;
  /** 关注数量 */
  focusAmount?: number;
  /** 店铺id */
  id?: string;
  /** 店铺logo */
  logo?: string;
  /** 店铺名称 */
  name?: string;
  /** 热门店铺 1热门店铺 */
  popular?: number;
  /** 原因 */
  reason?: string;
  /** 排序 */
  sequence?: number;
  /** 状态 0禁用1启用 */
  status?: number;
  /** 店铺类型 自营1、第三方0 */
  type?: number;
  /** 更新时间 */
  updateTime?: string;
  /** 工作日,多选，1-7逗号隔开 */
  workday?: number[];
}
