/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * app客户端版本升级管理
 */
export interface SysAppVersionResponse {
  /** app端口标识 */
  appId?: string;
  /** 客户端名称 */
  appName?: string;
  /** 文件大小(单位M) */
  appSize?: number;
  /** 更新地址 */
  appUrl?: string;
  /** 内部版本号(升级判断使用,如1.0.0-返回->100即可) */
  appVersion?: number;
  /** 版本账号展示使用(v1.0.0) */
  appVersionShow?: string;
  /** 客户端类型ios/android */
  client?: string;
  /** 客户端类型ios/android */
  clientDesc?: string;
  /** 创建时间 */
  createTime?: string;
  id?: string;
  /** 状态;StatusDeFultEnum{init:初始化,enable:启用,disable:禁用,lock:锁定,cancel:注销|删除} */
  status?: string;
  /** 状态;StatusDeFultEnum{init:初始化,enable:启用,disable:禁用,lock:锁定,cancel:注销|删除} */
  statusDesc?: string;
  /** 更新方式(0-无版本(数据不存在),1-普通升级，2-强制升级) */
  updateMode?: number;
  /** 修改时间 */
  updateTime?: string;
  /** 升级提示语 */
  upgradePrompt?: string;
}
