/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 员工帐户信息表,返回对象模型
 */
export interface SysAccountResponse {
  /** 创建时间 */
  createTime?: string;
  /** 数据来源编号 */
  dataCode?: string;
  /** 数据来源ID */
  dataId?: string;
  /** 数据来源姓名 */
  dataName?: string;
  /** 组织机构 */
  departmentName?: string;
  /** 员工Id */
  employeeId?: string;
  /** id */
  id?: string;
  /** lastLoginTime */
  lastLoginTime?: string;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 电话 */
  phone?: string;
  /** 主岗位 */
  postName?: string;
  /** 备注 */
  remark?: string;
  /** 状态;{init:初始化,processing:进行中,success:成功,fail:失败,over_time:认证过期,enable:启用,disable:禁用,lock:锁定,cancel:注销|删除} */
  status?: string;
  /** 状态中文翻译 */
  statusDesc?: string;
  /** 账户来源,{employee: 职员 ,customer: 客户 ,other： 其他} */
  type?: string;
  /** 修改时间 */
  updateTime?: string;
  /** 帐户code */
  userCode?: string;
  /** 帐户ID */
  userId?: string;
  /** 帐户name */
  userName?: string;
}
