/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 员工帐户信息表,查询对象模型
 */
export interface SysAccountQueryRequest {
  /** 数据id */
  dataId?: string;
  /** 员工Id */
  employeeId?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 账户/编号/姓名/电话 */
  keyWord?: string;
  /** 组织机构 */
  orgIds?: string[];
  /** 页码(默认值:1) */
  page?: number;
  /** 账户 */
  phone?: string;
  /** 岗位 */
  postIds?: string[];
  /** 页量(默认值:10) */
  size?: number;
  /** 状态 */
  status?: string[];
  /** 状态 */
  statusone?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** userId */
  userId?: string;
  /** 登录名称 */
  userName?: string;
}
