/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 系统_城市编码,添加、编辑表单模型
 */
export interface SysAreaAddOrEditRequest {
  /** 行政区域编码 */
  code: string;
  /** id,编辑时必填 */
  id?: string;
  /** 行政区域名称 */
  name: string;
  /** 上级ID，省级可不填 */
  parentId?: string;
  /** 拼音全称 */
  pinyin: string;
  /** 拼音简称 */
  py: string;
  /** 备注 */
  remark?: string;
  /** 排序 */
  sort: number;
  /** 状态 */
  status?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
