/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 员工账户角色关联表-角色集合,编辑表单对象模型
 */
export interface SysAccountRoleBeanEditRequest {
  /** 角色编码 */
  roleCode?: string;
  /** 角色ID */
  roleId?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
