/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { DynamicQuerySqlDto } from './dynamicQuerySqlDto';

/**
 * app客户端版本升级管理
 */
export interface SysAppVersionQueryRequest {
  /** 客户端类型(ios,android) */
  client?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 页码(默认值:1) */
  page?: number;
  /** 页量(默认值:10) */
  size?: number;
  /** 动态查询 */
  sqlConfigs: DynamicQuerySqlDto[];
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
