/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysAmapAreaCodeTreeResponse } from './sysAmapAreaCodeTreeResponse';

/**
 * 行政大区区域信息表,返回对象模型
 */
export interface SysAreaRegionResponse {
  /** 大区编码 */
  areaCode?: string;
  /** 省、市、区树列表 */
  areaCodeTreeResponseList?: SysAmapAreaCodeTreeResponse[];
  /** 大区名称 */
  areaName?: string;
}
