/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * app客户端版本升级管理,编辑表单对象模型
 */
export interface SysAppVersionEditRequest {
  /** app端口标识 */
  appId?: string;
  /** 客户端名称（厂商/经销商） */
  appName?: string;
  /** 文件大小(单位M) */
  appSize?: number;
  /** 更新地址 */
  appUrl?: string;
  /** 内部版本号(升级判断使用,如1.0.0-返回->100即可) */
  appVersion?: number;
  /** 版本账号展示使用(v1.0.0) */
  appVersionShow?: string;
  /** 客户端类型ios/android */
  client?: string;
  /** id */
  id?: string;
  /** product */
  product?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** 更新方式(1-普通升级，2-强制升级) */
  updateMode?: number;
  /** 升级提示语 */
  upgradePrompt?: string;
  /** 版本 */
  version?: number;
}
