/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface SysAreaResponse {
  /** 区号 */
  areaCode?: string;
  /** 区名称 */
  areaName?: string;
  /** 市编码 */
  cityCode?: string;
  /** 市 */
  cityName?: string;
  /** 创建时间 */
  createTime?: string;
  /** 县/区 编码 */
  districtCode?: string;
  /** 县/区 */
  districtName?: string;
  /** ID */
  id?: string;
  /** 级别 province 省  city 市  district 区 street 街道 */
  level?: string;
  /** 级别 province 省  city 市  district 区 street 街道 */
  levelCn?: string;
  /** 父级code */
  parentCode?: string;
  /** 全拼 */
  pinyin?: string;
  /** 省编码 */
  provinceCode?: string;
  /** 省 */
  provinceName?: string;
  /** 简拼 */
  py?: string;
  /** 备注 */
  remark?: string;
  /** 排序 */
  sort?: number;
  /** 状态英文 */
  status?: string;
  /** 状态中文 */
  statusCn?: string;
  /** 街道编码 */
  streetCode?: string;
  /** 街道名称 */
  streetName?: string;
  /** 更新时间 */
  updateTime?: string;
}
