/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface SysAmapAreaCodeResponse {
  /** 区号 */
  areaCode?: string;
  /** 市编码 */
  cityCode?: string;
  /** 市 */
  cityName?: string;
  /** 县/区 编码 */
  districtCode?: string;
  /** 县/区 */
  districtName?: string;
  /** 级别 province 省  city 市  district 区 street 街道 */
  level?: string;
  /** 省编码 */
  provinceCode?: string;
  /** 省 */
  provinceName?: string;
  /** 街道编码 */
  streetCode?: string;
  /** 街道名称 */
  streetName?: string;
}
