/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface SysBaseIdsRequest {
  /** 按钮code */
  btnCode?: string;
  /** ids集合 */
  ids?: string[];
  /** 模块code(子表模块单独删除可用) */
  moduleCode?: string;
  /** 操作状态 */
  status?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
