/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 系统业务操作日志表
 */
export interface SysBusinessLogResponse {
  /** 所属端口(系统分配 ) */
  appId?: string;
  /** 所属端口名称 */
  appName?: string;
  /** 创建时间 */
  createTime?: string;
  /** 系统功能 */
  functionName?: string;
  /** gid */
  gid?: string;
  /** id */
  id?: string;
  /** IP地址 */
  ip?: string;
  /** login:登陆日志 oper：操作日志 exception：异常日志 */
  logType?: string;
  /** 日志类型 */
  logTypeDesc?: string;
  /** 登录名称 */
  loginName?: string;
  /** 手机号码(支持手机号登录，不同系统区别) */
  mobile?: string;
  /** 信息 */
  msg?: string;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 所属产品 {retail:摩配配;lxt:零售通;payment:支付系统;member:会员系统;cyclone:赛科龙;dmp:江苏宗申;common:公共;devOps:devOps;flow:工作流系统;boss:boss系统} */
  product?: string;
  /** 所属产品desc */
  productDesc?: string;
  /** 日期 */
  receiveDate?: string;
  /** 接收时间 */
  receiveTime?: string;
  /** 备注 */
  remark?: string;
  /** 请求方法 get post */
  requestMethod?: string;
  /** 请求参数 */
  requestParam?: string;
  /** 请求地址 */
  requestUrl?: string;
  /** 响应间隔时间 单位毫秒 */
  responseInterval?: number;
  /** 响应时间 */
  responseTime?: string;
  /** {init:初始化,processing:进行中,success:成功,fail:失败,over_time:认证过期,enable:启用,disable:禁用,lock:锁定,cancel:注销|删除} */
  status?: string;
  /** 修改时间 */
  updateTime?: string;
  /** 用户设备信息 */
  userAgent?: string;
  /** 操作人编码 */
  userCode?: string;
  /** 操作人id */
  userId?: string;
  /** 操作人名称 */
  userName?: string;
}
