/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 单据编码,批量更改状态表单模型
 */
export interface SysBillCodeBatchUpdateStatusRequest {
  /** 单据编码批量删除 */
  billCodeIds?: string[];
  /** 状态 {enable:启用,disable:禁用,delete:注销|删除} */
  status: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
