/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 系统业务操作日志表,查询表单模型
 */
export interface SysBusinessLogQueryRequest {
  /** appId */
  appId?: string;
  /** 按钮code */
  btnCode?: string;
  /** 系统功能 */
  functionName?: string;
  /** gid */
  gid?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** login:登陆日志 oper：操作日志 */
  logType?: string;
  /** 模块code(子表模块单独删除可用) */
  moduleCode?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 接收时间结束 */
  receiveDateEnd?: string;
  /** 接收时间开始 */
  receiveDateStart?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** 操作人编码 */
  userCode?: string;
  /** 操作人名称 */
  userName?: string;
}
