/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 单据编码详细配置,编辑表单模型
 */
export interface SysBillCodeDetailEditRequest {
  /** 初始值 */
  curFlowNo?: number;
  /** 格式 */
  prefixStrFmt?: string;
  /** selfDfine 自定义,date 日期,flowNo 流水号,company 公司,dept 部门,user 员工 */
  prefixStrType: string;
  /** 备注 */
  remark?: string;
  /** 状态 {enable:启用,disable:禁用} */
  status?: string;
  /** 步长 */
  stepSize?: number;
}
