/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysBillCodeDetailInfoResponse } from './sysBillCodeDetailInfoResponse';
import type { SysBillCodeInfoResponseCreateTime } from './sysBillCodeInfoResponseCreateTime';
import type { SysBillCodeInfoResponseId } from './sysBillCodeInfoResponseId';
import type { SysBillCodeInfoResponseUpdateTime } from './sysBillCodeInfoResponseUpdateTime';

/**
 * 单据编码主配置
 */
export interface SysBillCodeInfoResponse {
  /** 业务编码 */
  busCode?: string;
  /** 业务描述 */
  busDesc?: string;
  /** 业务名称 */
  busName?: string;
  /** 详细配置 */
  configs?: SysBillCodeDetailInfoResponse[];
  /** 创建时间 */
  createTime?: SysBillCodeInfoResponseCreateTime;
  /** 当前编码 */
  curNo?: string;
  /** id */
  id?: SysBillCodeInfoResponseId;
  /** 机构编码 */
  orgCode?: string;
  /** 机构id */
  orgId?: string;
  /** 机构名称 */
  orgName?: string;
  /** 备注 */
  remark?: string;
  /** 状态 {enable:启用,disable:禁用,lock:锁定,delete:注销|删除} */
  status?: string;
  /** 状态 {enable:启用,disable:禁用,lock:锁定,delete:注销|删除} */
  statusCn?: string;
  /** 修改时间 */
  updateTime?: SysBillCodeInfoResponseUpdateTime;
}
