/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysBillCodeDetailEditRequest } from './sysBillCodeDetailEditRequest';

/**
 * 单据编码主配置,添加、编辑表单模型
 */
export interface SysBillCodeAddOrEditRequest {
  /** 业务编码 */
  busCode: string;
  /** 业务描述 */
  busDesc?: string;
  /** 业务名称 */
  busName: string;
  /** 详细配置 */
  configs?: SysBillCodeDetailEditRequest[];
  /** id */
  id?: string;
  /** 所属机构编码（配置机构专用的话必填） */
  orgCode?: string;
  /** 机构id */
  orgId?: string;
  /** 机构名称 */
  orgName?: string;
  /** 备注 */
  remark?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
