/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 单据编码详细配置
 */
export interface SysBillCodeDetailInfoResponse {
  /** 当前流水号 */
  curFlowNo?: number;
  /** 流水号最大值 */
  maxFlowNo?: number;
  /** 1：要左补0  0：不要左补0 */
  paddingLeft?: boolean;
  /** 格式 */
  prefixStrFmt?: string;
  /** selfDfine 自定义,date 日期,flowNo 流水号,company 公司,dept 部门,user 员工 */
  prefixStrType?: string;
  /** selfDfine 自定义,date 日期,flowNo 流水号,company 公司,dept 部门,user 员工 */
  prefixStrTypeCn?: string;
  /** 备注 */
  remark?: string;
  /** 排序 */
  sort?: number;
  /** 状态 {init:初始化,processing:进行中,success:成功,fail:失败,over_time:认证过期,enable:启用,disable:禁用,lock:锁定,cancel:注销|删除} */
  status?: string;
  /** 状态 {init:初始化,processing:进行中,success:成功,fail:失败,over_time:认证过期,enable:启用,disable:禁用,lock:锁定,cancel:注销|删除} */
  statusCn?: string;
  /** 步长 */
  stepSize?: number;
}
