/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface SysCodeSonGeninfoEditRequest {
  /** 生成模版 true:表单 false：列表 */
  isForm: boolean;
  /** 子表单布局格栅ID */
  sonLayoutGridId?: string;
  /** 子表单标题 */
  sonTitle?: string;
}
