/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 子表按钮信息
 */
export interface SysCodeSonBtnResponse {
  /** 按钮图标 */
  icon?: string;
  /** 是否内置 true：是 false：否 */
  isBuiltIn?: boolean;
  /** onclick名称 */
  sonBtnClickName?: string;
  /** 按钮唯一标识 */
  sonBtnKey?: string;
  /** 按钮名称 */
  sonBtnName?: string;
  /** 子表名 */
  tableSonName?: string;
}
