/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 主表菜单表,编辑表单模型
 */
export interface SysCodeMainMenuAddOrEditRequest {
  /** 菜单英文别名(用于生成编号前缀) */
  alias?: string;
  /** 菜单图标 */
  icon?: string;
  /** 是否属性维护 true：是 false：否 */
  isMaintain?: boolean;
  /** 菜单名称 */
  name?: string;
  /** 父级菜单id */
  parentId?: string;
  /** 请求地址 */
  path?: string;
  /** 地址类型{route:路由地址,url:外部url} */
  pathType?: string;
  /** 备注 */
  remark?: string;
  /** 所属系统 */
  system?: string;
  /** 目标{addTabPage:页签栏,_blank:新开窗口} */
  target?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** 菜单类型{menu:菜单,button:按钮} */
  type?: string;
}
