/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface SysCodeMainBtnEditRequest {
  /** 按钮图标 */
  icon?: string;
  /** 是否内置 true：是 false：否 */
  isBuiltIn?: boolean;
  /** onclick名称 */
  mainBtnClickName?: string;
  /** 按钮唯一标识 */
  mainBtnKey?: string;
  /** 按钮名称 */
  mainBtnName?: string;
}
