/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface SysCodeMainGeninfoResponse {
  /** 可编辑状态字段 */
  editStatusCol?: string;
  /** 可编辑状态数据源 */
  editStatusSource?: string;
  /** 可编辑状态值 */
  editStatusValue?: string;
  /** 网关路由路径 */
  gatewayRoute?: string;
  /** 生成模版ID */
  genTemplateId?: string;
  /** 后端core包路径 */
  mainBackPackagePath?: string;
  /** 是否生成sql 1：是 0：否 */
  mainIsCreateSql?: boolean;
  /** 主列表是否分页 1：是 0：否 */
  mainIsPage?: boolean;
  /** 主表单布局格栅ID */
  mainLayoutGridId?: string;
  /** 模块名称 */
  mainModuleName?: string;
  /** 主表与树关联字段 */
  mainRelationCol?: string;
  /** 生成源码 前端、后端 逗号拼接 back,front */
  mainSourceCodes?: string;
  /** 主表单标题 */
  mainTitle?: string;
  /** 查询布局方式：popout  弹框，list   查询列输入框 */
  queryLayout?: string;
  /** 树与主表关联字段 */
  treeRelationCol?: string;
  /** 树列表展示字段 */
  treeShowCol?: string;
  /** 树形列表来源表 */
  treeSourceTable?: string;
}
