/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface SysCodeMainFlowResponse {
  /** 审批终止值 */
  flowAbortColumnVal?: string;
  /** 流程审批回调地址 */
  flowCallBackUrl?: string;
  /** userDefined:自定义算法 modifyColumn：修改字段值 */
  flowCallBackWay?: string;
  /** 审批取消值 */
  flowCancleColumnVal?: string;
  /** 流程表单key */
  flowFormKey?: string;
  /** 审批通过值 */
  flowPassColumnVal?: string;
  /** 审批拒绝值 */
  flowRefuseColumnVal?: string;
  /** 审批驳回值 */
  flowRejectColumnVal?: string;
  /** 状态数据源 */
  flowStatusValue?: string;
  /** 工作流是否关联 true：是 false：否 */
  isFlowRelated?: boolean;
  /** 修改字段 */
  modifyColumn?: string;
}
