/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysCodeMainColumnsResponse } from './sysCodeMainColumnsResponse';
import type { SysCodeSonBasicInfoResponse } from './sysCodeSonBasicInfoResponse';

/**
 * 主从表分页信息
 */
export interface SysCodeGenPageResponse {
  /** 代码生成分类 */
  codeGenerationKey?: string;
  /** 创建时间 */
  createTime?: string;
  /** 数据库连接ID */
  dbConnectionId?: string;
  /** 实体类名 */
  entityName?: string;
  /** 功能作者 */
  functionActor?: string;
  /** 功能描述 */
  functionDesc?: string;
  /** id */
  id?: string;
  /** 主表字段配置 */
  mainColumns?: SysCodeMainColumnsResponse[];
  /** 菜单CODE */
  menuCode?: string;
  /** 菜单ID */
  menuId?: string;
  /** 主从表关联信息 */
  relationInfo?: SysCodeSonBasicInfoResponse[];
  /** 表说明 */
  tableMainComment?: string;
  /** 表名 */
  tableMainName?: string;
  /** 子表数 */
  tableSonCount?: number;
  /** 更新时间 */
  updateTime?: string;
}
