/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysCodeMainBasicInfoEditRequest } from './sysCodeMainBasicInfoEditRequest';
import type { SysCodeMainBtnEditRequest } from './sysCodeMainBtnEditRequest';
import type { SysCodeMainColumnsEditRequest } from './sysCodeMainColumnsEditRequest';
import type { SysCodeMainFlowEditRequest } from './sysCodeMainFlowEditRequest';
import type { SysCodeMainGeninfoEditRequest } from './sysCodeMainGeninfoEditRequest';
import type { SysCodeMainMenuAddOrEditRequest } from './sysCodeMainMenuAddOrEditRequest';

/**
 * 代码生成器，主表添加、编辑表单模型
 */
export interface SysCodeGenMainAddOrEditRequest {
  /** 分页列表的ID */
  codeMainId: string;
  /** 主表基础信息配置 */
  mainBasicinfo?: SysCodeMainBasicInfoEditRequest;
  /** 主按钮配置 */
  mainBtns?: SysCodeMainBtnEditRequest[];
  /** 主字段配置 */
  mainColumns?: SysCodeMainColumnsEditRequest[];
  /** 流程信息配置 */
  mainFlow?: SysCodeMainFlowEditRequest;
  /** 主表生成信息配置 */
  mainGeninfo?: SysCodeMainGeninfoEditRequest;
  /** 菜单配置 */
  menu?: SysCodeMainMenuAddOrEditRequest;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
