/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface SysCodeMainBasicInfoEditRequest {
  /** 实体类名称 */
  entityName?: string;
  /** 前端作者 */
  frontendActor?: string;
  /** 后端作者 */
  functionActor?: string;
  /** 功能描述 */
  functionDesc?: string;
  /** 表说明 */
  tableMainComment?: string;
}
