/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface SysCodeSonBasicInfoEditRequest {
  /** 实体类名称 */
  entityName: string;
  /** 备注 */
  remark: string;
  /** 子表说明 */
  tableSonComment?: string;
}
