/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysCodeMainBasicInfoResponse } from './sysCodeMainBasicInfoResponse';
import type { SysCodeMainBtnResponse } from './sysCodeMainBtnResponse';
import type { SysCodeMainColumnsResponse } from './sysCodeMainColumnsResponse';
import type { SysCodeMainFlowResponse } from './sysCodeMainFlowResponse';
import type { SysCodeMainGeninfoResponse } from './sysCodeMainGeninfoResponse';
import type { SysCodeMainMenuResponse } from './sysCodeMainMenuResponse';

/**
 * 主表信息
 */
export interface SysCodeGenMainResponse {
  /** 主表基础信息配置 */
  mainBasicinfo?: SysCodeMainBasicInfoResponse;
  /** 主表按钮配置 */
  mainBtns?: SysCodeMainBtnResponse[];
  /** 主表字段配置 */
  mainColumns?: SysCodeMainColumnsResponse[];
  /** 主表流程信息配置 */
  mainFlow?: SysCodeMainFlowResponse;
  /** 主表生成信息配置 */
  mainGeninfo?: SysCodeMainGeninfoResponse;
  /** 主表菜单配置 */
  menu?: SysCodeMainMenuResponse;
}
