/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysCodeMainBasicInfoResponseCreateTime } from './sysCodeMainBasicInfoResponseCreateTime';
import type { SysCodeMainBasicInfoResponseUpdateTime } from './sysCodeMainBasicInfoResponseUpdateTime';

/**
 * 主表基础信息
 */
export interface SysCodeMainBasicInfoResponse {
  /** 代码生成分类 */
  codeGenerationKey?: string;
  /** 创建时间 */
  createTime?: SysCodeMainBasicInfoResponseCreateTime;
  /** 数据库连接信息ID */
  dbConnectionId?: string;
  /** 实体类名 */
  entityName?: string;
  /** 前端作者 */
  frontendActor?: string;
  /** 后端作者 */
  functionActor?: string;
  /** 功能描述 */
  functionDesc?: string;
  /** 菜单编码 */
  menuCode?: string;
  /** 菜单ID */
  menuId?: string;
  /** 表说明 */
  tableMainComment?: string;
  /** 表名 */
  tableMainName?: string;
  /** 修改时间 */
  updateTime?: SysCodeMainBasicInfoResponseUpdateTime;
}
