/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 主表菜单表
 */
export interface SysCodeMainMenuResponse {
  /** 菜单英文别名(用于生成编号前缀) */
  alias?: string;
  /** 菜单编号(编号规则生成) */
  code?: string;
  /** 菜单图标 */
  icon?: string;
  /** 是否属性维护 true：是 false：否 */
  isMaintain?: boolean;
  /** 菜单名称 */
  name?: string;
  /** 父级菜单编号 */
  parentCode?: string;
  /** 父级菜单id */
  parentId?: string;
  /** 父级菜单 */
  parentName?: string;
  /** 父级菜单Path */
  parentPath?: string;
  /** 请求地址 */
  path?: string;
  /** 地址类型{route:路由地址,url:外部url} */
  pathType?: string;
  /** 地址类型{route:路由地址,url:外部url} */
  pathTypeCn?: string;
  /** 备注 */
  remark?: string;
  /** 排序 */
  sort?: number;
  /** 状态StatusDeFultEnum{init:初始化,enable:启用,disable:禁用,lock:锁定,cancel:注销|删除} */
  status?: string;
  system?: string;
  /** 目标{addTabPage:页签栏,_blank:新开窗口} */
  target?: string;
  /** 目标{addTabPage:页签栏,_blank:新开窗口} */
  targetCn?: string;
  /** 菜单类型{menu:菜单,button:按钮} */
  type?: string;
  /** 菜单类型{menu:菜单,button:按钮} */
  typeCn?: string;
}
