/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface SysCodeMainColumnsResponse {
  /** 居中对齐：center 左对齐：left 右对齐：right */
  alineType?: string;
  /** 属性名称 */
  columnAttrName?: string;
  /** 列说明 */
  columnComment?: string;
  /** 字段类型 */
  columnDbType?: string;
  /** 列定义字段 英文 */
  columnDefine?: string;
  /** 属性类型 */
  columnType?: string;
  /** 字段验证 */
  columnValid?: string;
  /** 控件类型 */
  compentType?: string;
  /** 数据源 */
  dataSource?: string;
  /** 是否禁用 true：是 false：否 */
  disabled?: boolean;
  /** 展示字段 */
  displayColumn?: string;
  /** 是否提交字段 true：是 false：否 */
  isCommit?: boolean;
  /** 是否通用查询 true：是 false：否 */
  isCommon?: boolean;
  /** 查看详情是否显示 true：是 false：否 */
  isDetailShow?: boolean;
  /** 是否隐藏 true：是 false：否 */
  isHide?: boolean;
  /** 是否属性维护 true：是 false：否 */
  isMaintain?: boolean;
  /** 是否新行 true：是 false：否 */
  isNewLine?: boolean;
  /** 是否显示 true：是 false：否 */
  isShow?: boolean;
  /** 是否合计 true：是 false：否 */
  isSum?: boolean;
  /** 匹配方式 左like， = */
  matchWay?: string;
  /** 是否只读 true：是 false：否 */
  readOnly?: boolean;
  /** 是否必填 true：是 false：否 */
  required?: boolean;
}
