/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysCodeSonBasicInfoResponseCreateTime } from './sysCodeSonBasicInfoResponseCreateTime';
import type { SysCodeSonColumnsResponse } from './sysCodeSonColumnsResponse';
import type { SysCodeSonBasicInfoResponseUpdateTime } from './sysCodeSonBasicInfoResponseUpdateTime';

/**
 * 子表基础信息
 */
export interface SysCodeSonBasicInfoResponse {
  /** 创建时间 */
  createTime?: SysCodeSonBasicInfoResponseCreateTime;
  /** 实体类名称 */
  entityName?: string;
  /** ID */
  id?: string;
  /** 主表关联字段 */
  relationMainColumn?: string;
  /** 子表关联字段 */
  relationSonColumn?: string;
  /** 备注 */
  remark?: string;
  /** 从字段配置 */
  sonColumns?: SysCodeSonColumnsResponse[];
  /** 主表说明 */
  tableMainComment?: string;
  /** 主表名称 */
  tableMainName?: string;
  /** 子表说明 */
  tableSonComment?: string;
  /** 子表名称 */
  tableSonName?: string;
  /** 修改时间 */
  updateTime?: SysCodeSonBasicInfoResponseUpdateTime;
}
