/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysCodeSonBasicInfoEditRequest } from './sysCodeSonBasicInfoEditRequest';
import type { SysCodeSonBtnEditRequest } from './sysCodeSonBtnEditRequest';
import type { SysCodeSonColumnsEditRequest } from './sysCodeSonColumnsEditRequest';
import type { SysCodeSonGeninfoEditRequest } from './sysCodeSonGeninfoEditRequest';

/**
 * 代码生成器，从表添加、编辑表单模型
 */
export interface SysCodeGenSonAddOrEditRequest {
  /** 分页列表的ID */
  codeMainId: string;
  /** 从表基础信息配置 */
  sonBasicinfo?: SysCodeSonBasicInfoEditRequest;
  /** 从表按钮配置 */
  sonBtns?: SysCodeSonBtnEditRequest[];
  /** 从表字段配置 */
  sonColumns?: SysCodeSonColumnsEditRequest[];
  /** 从表生成信息配置 */
  sonGeninfo?: SysCodeSonGeninfoEditRequest;
  /** 子表名 */
  tableSonName: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
