/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysCodeSonBasicInfoResponse } from './sysCodeSonBasicInfoResponse';
import type { SysCodeSonBtnResponse } from './sysCodeSonBtnResponse';
import type { SysCodeSonColumnsResponse } from './sysCodeSonColumnsResponse';
import type { SysCodeSonGeninfoResponse } from './sysCodeSonGeninfoResponse';

export interface SysCodeGenChildrenResponse {
  /** 主从表关联信息 */
  relationInfo?: SysCodeSonBasicInfoResponse;
  /** 从按钮配置 */
  sonBtns?: SysCodeSonBtnResponse[];
  /** 从字段配置 */
  sonColumns?: SysCodeSonColumnsResponse[];
  /** 子表生成信息配置 */
  sonGeninfo?: SysCodeSonGeninfoResponse;
}
