/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 动态表格列信息,编辑表单模型
 */
export interface SysDynamicExcelRowEditRequest {
  /** 列编码 */
  itemCode?: string;
  /** 列名称 */
  itemName?: string;
  /** 备注 */
  remark?: string;
}
