/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysDynamicFormModelFieldResponse } from './sysDynamicFormModelFieldResponse';
import type { SysDynamicFormSonModelResponse } from './sysDynamicFormSonModelResponse';

/**
 * 动态表单模型-模块,返回对象模型
 */
export interface SysDynamicFormModelModuleResponse {
  /** 模块名称 */
  code?: string;
  /** 表单字段信息 */
  fields?: SysDynamicFormModelFieldResponse[];
  /** 是否在业务表单显示 1：是  0：否 */
  isShow?: boolean;
  /** 模块代码 表名 */
  name?: string;
  /** 备注 */
  remark?: string;
  /** 子模版信息(excel) */
  sonModel?: SysDynamicFormSonModelResponse;
  /** 模块顺序 */
  sort?: number;
  /** 模版类型{excel:纯表格,form:表单(含组合单表单+表格)} */
  templateType?: string;
  /** 模版类型desc */
  templateTypeDesc?: string;
}
