/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysDynamicFormV2ValueResponse } from './sysDynamicFormV2ValueResponse';

/**
 * 形象店建店申请示例,返回对象模型
 */
export interface SysDynamicDemoFormValueResponse {
  /** 创建时间 */
  createTime?: string;
  /** 动态表单 */
  dynamicFormData?: SysDynamicFormV2ValueResponse;
  /** id */
  id?: string;
  /** 零售商详细地址 */
  merchantAddress?: string;
  /** 零售商名称 */
  merchantName?: string;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 备注 */
  remark?: string;
  /** 状态 {enable:启用,disable:禁用,lock:锁定,delete:删除,cancle:注销} */
  status?: string;
  /** 修改时间 */
  updateTime?: string;
}
