/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysDictSonResponseCreateTime } from './sysDictSonResponseCreateTime';
import type { SysDictSonResponseUpdateTime } from './sysDictSonResponseUpdateTime';

/**
 * 字典表
 */
export interface SysDictSonResponse {
  /** 分类 compent：组件类 service：业务类 */
  classify?: string;
  /** 分类 compent：组件类 service：业务类 */
  classifyCn?: string;
  /** 分类标识 */
  code?: string;
  /** 创建时间 */
  createTime?: SysDictSonResponseCreateTime;
  /** 字典值 */
  dictKey?: string;
  /** 字典名称 */
  dictName?: string;
  /** id */
  id?: string;
  /** 上级分类 */
  parentDictName?: string;
  /** 父级ID */
  parentId?: string;
  /** 备注 */
  remark?: string;
  /** 排序 */
  sort?: number;
  /** 状态 {init:初始化,processing:进行中,success:成功,fail:失败,over_time:认证过期,enable:启用,disable:禁用,lock:锁定,cancel:注销|删除} */
  status?: string;
  /** 状态 {init:初始化,processing:进行中,success:成功,fail:失败,over_time:认证过期,enable:启用,disable:禁用,lock:锁定,cancel:注销|删除} */
  statusCn?: string;
  /** 所属系统 */
  system?: string;
  /** 所属系统 */
  systemCn?: string;
  /** 修改时间 */
  updateTime?: SysDictSonResponseUpdateTime;
}
