/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 动态表单保存值
 */
export interface SysDynamicFormFieldsValueEditRequest {
  /** 字段定义 */
  columnDefine?: string;
  /** 字段值 */
  columnValue?: string;
}
