/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysDynamicFormModelModuleResponse } from './sysDynamicFormModelModuleResponse';

/**
 * 动态表单模型,返回对象模型
 */
export interface SysDynamicFormModelDetailResponse {
  /** 表单分类数据字典key */
  classfiyDataKey?: string;
  /** 表单分类数据字典名 */
  classfiyDataName?: string;
  /** 模型编码 */
  code?: string;
  /** 创建时间 */
  createTime?: string;
  /** id */
  id?: string;
  /** json模块方式存储 */
  jsonTemplate?: string;
  /** 模块 */
  modules?: SysDynamicFormModelModuleResponse[];
  /** 模型名称 */
  name?: string;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 备注 */
  remark?: string;
  /** 状态 {enable:启用,disable:禁用,lock:锁定,delete:删除,cancle:注销} */
  status?: string;
  /** 模版类型 */
  templateType?: string;
  /** 模版desc */
  templateTypeDesc?: string;
  /** 修改时间 */
  updateTime?: string;
}
