/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 动态表格行信息,编辑表单模型
 */
export interface SysDynamicExcelLineEditRequest {
  /** 行分类code */
  classfiyCode?: string;
  /** 行分类名称 */
  classfiyName?: string;
  /** 行code */
  itemCode?: string;
  /** 行名称 */
  itemName?: string;
  /** 备注 */
  remark?: string;
}
