/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { INodeDto } from './iNodeDto';

/**
 * 系统字典表:list与tree模型
 */
export interface SysDictComponentResponse {
  /** 子孙节点 */
  children?: INodeDto[];
  /** 字典码 */
  code?: string;
  /** 字典值 */
  dictKey?: string;
  /** 字典名称 */
  dictName?: string;
  /** id */
  id?: string;
  /** 父类id */
  pid?: string;
  /** 排序 */
  sort?: number;
}
