/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysDynamicFormModelModuleEditRequest } from './sysDynamicFormModelModuleEditRequest';

/**
 * 动态表单模型,编辑表单对象模型
 */
export interface SysDynamicFormModelEditRequest {
  /** 表单分类数据字典key */
  classfiyDataKey?: string;
  /** 表单分类数据字典名 */
  classfiyDataName?: string;
  /** 模型标识 */
  code?: string;
  /** id */
  id?: string;
  /** json模块方式存储 */
  jsonTemplate?: string;
  /** 模块 */
  modules?: SysDynamicFormModelModuleEditRequest[];
  /** 模型名称 */
  name?: string;
  /** 备注 */
  remark?: string;
  /** 模版类型{excel:纯表格,form:表单,table:表格,} */
  templateType?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
