/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 动态表格行信息
 */
export interface SysDynamicExcelRowResponse {
  /** 列编码 */
  itemCode?: string;
  /** 列名称 */
  itemName?: string;
  /** 备注 */
  remark?: string;
  /** 排序 */
  sort?: number;
}
