/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 动态表单-子模版(嵌套子模版),请求对象模型
 */
export interface SysDynamicFormModelSonModelRequest {
  /** 子模块Id(表单选表格必传) */
  sonModelId?: string;
  /** 子模块json模版(前端自定义json格式,方便渲染) */
  sonTemplate?: string;
}
