/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 动态表单:-v2子模块-值
 */
export interface SysDynamicFormV2SonModuleValueResponse {
  /** 子模块json值(excel) */
  sonModelValue?: string;
}
