/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 动态表单-子模版(嵌套子模版),返回对象模型
 */
export interface SysDynamicFormSonModelResponse {
  /** 子模块编码 */
  sonModelCode?: string;
  /** 子模型id(excel,嵌套子模版)Id */
  sonModelId?: string;
  /** 子模块名称 */
  sonModelName?: string;
}
