/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysDynamicFormV2FieldValueResponse } from './sysDynamicFormV2FieldValueResponse';
import type { SysDynamicFormV2SonModuleValueResponse } from './sysDynamicFormV2SonModuleValueResponse';

/**
 * 动态表格值信息-v2
 */
export interface SysDynamicFormV2ModuleValueResponse {
  /** 字段信息 */
  fieldValue?: SysDynamicFormV2FieldValueResponse[];
  /** 模块编码(=moduleCode) */
  moduleCode?: string;
  /** 模块名称 */
  moduleName?: string;
  /** 子模版信息(excel) */
  sonModel?: SysDynamicFormV2SonModuleValueResponse;
  /** 模版类型{excel:纯表格,form:表单(含组合单表单+表格)} */
  templateType?: string;
}
