/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysDynamicFormV2ModuleValueResponse } from './sysDynamicFormV2ModuleValueResponse';

/**
 * 动态表格值信息-v2
 */
export interface SysDynamicFormV2ValueResponse {
  /** 业务数据记录ID */
  dataId?: string;
  /** 动态表单json_value值 */
  jsonValue?: string;
  /** 模型code */
  modelCode?: string;
  /** 模型名称 */
  modelName?: string;
  /** 模型版本 */
  modelVersion?: string;
  /** 动态表格模块信息 */
  moduleValue?: SysDynamicFormV2ModuleValueResponse[];
  /** 模版类型{excel:纯表格,form:表单(含组合单表单+表格)} */
  templateType?: string;
}
