/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 动态表单模型发布实例,编辑表单对象模型
 */
export interface SysDynamicFormInstanceEditRequest {
  /** id */
  id?: string;
  /** 版本号 */
  modelVersion?: string;
  /** 实例名称 */
  name?: string;
  /** 备注 */
  remark?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
