/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysDynamicFormInstanceFieldResponse } from './sysDynamicFormInstanceFieldResponse';
import type { SysDynamicFormInstanceSonModelResponse } from './sysDynamicFormInstanceSonModelResponse';

/**
 * 动态表单模型-模块,返回对象模型
 */
export interface SysDynamicFormInstanceModuleResponse {
  /** 字段信息 */
  fields?: SysDynamicFormInstanceFieldResponse[];
  /** 是否在基础信息表单显示 1：是  0：否 */
  isShow?: boolean;
  /** 表单模型模块编码 */
  moduleCode?: string;
  /** 表单模型模块ID */
  moduleId?: string;
  /** 表单模型模块名称 */
  moduleName?: string;
  /** 备注 */
  remark?: string;
  /** 子模版信息(excel) */
  sonModel?: SysDynamicFormInstanceSonModelResponse;
  /** 模块顺序 */
  sort?: number;
  /** 模版类型{excel:纯表格,form:表单(含组合单表单+表格)} */
  templateType?: string;
  /** 模版类型desc */
  templateTypeDesc?: string;
}
