/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 数据库连接,编辑表单模型
 */
export interface SysDbConnectionEditRequest {
  /** 数据库别名 */
  dbAlias: string;
  /** 数据库IP */
  dbIp: string;
  /** 数据库名称 */
  dbName: string;
  /** 数据库端口 */
  dbPort: number;
  /** 用户登录密码 */
  dbPwd: string;
  /** 数据库类型，例如：mysql,mariadb,oracle,db2 */
  dbType: string;
  /** 数据库用户 */
  dbUser: string;
  /** id,编辑操作时必填 */
  id?: string;
  /** 备注 */
  remark?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
