/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysDynamicFormModelFieldEditRequest } from './sysDynamicFormModelFieldEditRequest';
import type { SysDynamicFormModelSonModelRequest } from './sysDynamicFormModelSonModelRequest';

/**
 * 动态表单模型-模块,编辑表单对象模型
 */
export interface SysDynamicFormModelModuleEditRequest {
  /** 表单字段信息 */
  fields?: SysDynamicFormModelFieldEditRequest[];
  /** 是否在业务表单显示 1：是  0：否 */
  isShow?: boolean;
  /** 模块名称 */
  name?: string;
  /** 备注 */
  remark?: string;
  /** 子模版信息(excel) */
  sonModel?: SysDynamicFormModelSonModelRequest;
  /** 模块顺序 */
  sort?: number;
  /** 模版类型{excel:纯表格,form:表单(含组合单表单+表格)} */
  templateType?: string;
}
