/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 字典表,查询表单模型
 */
export interface SysDictQueryRequest {
  /** 字典表code */
  code?: string;
  /** 获取子集 */
  dictKeySon?: string;
  /** 字典表key */
  key?: string;
  /** 字典表name */
  name?: string;
  /** 字典表状态 */
  status?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
