/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysDynamicFormV2ValueEditRequest } from './sysDynamicFormV2ValueEditRequest';

/**
 * 形象店建店申请示例,编辑表单对象模型
 */
export interface SysDynamicDemoFormValueEditRequest {
  /** 动态表单 */
  dynamicFormData?: SysDynamicFormV2ValueEditRequest;
  /** id */
  id?: string;
  /** 零售商详细地址 */
  merchantAddress?: string;
  /** 零售商名称 */
  merchantName?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
