/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysDynamicFormFieldsValueEditRequest } from './sysDynamicFormFieldsValueEditRequest';
import type { SysDynamicFormV2SonModuleValueEditRequest } from './sysDynamicFormV2SonModuleValueEditRequest';

/**
 * 动态表单-v2保存值
 */
export interface SysDynamicFormV2ModuleValueEditRequest {
  /** 字段值 */
  fieldsValue?: SysDynamicFormFieldsValueEditRequest[];
  /** 模块编码(=moduleCode) */
  moduleCode?: string;
  /** 子模版信息(excel) */
  sonModel?: SysDynamicFormV2SonModuleValueEditRequest;
}
