/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 字典表
 */
export interface SysDictAddOrEditRequest {
  /** 分类用途 compent：组件类 service：业务类 */
  classify: string;
  /** 分类标识 */
  code: string;
  /** 字典值 */
  dictKey: string;
  /** 字典名称 */
  dictName: string;
  /** id */
  id?: string;
  /** 上级字典 */
  parentId?: string;
  /** 备注 */
  remark?: string;
  /** 排序 */
  sort?: number;
  /** 所属系统 */
  system: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
