/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 字典表
 */
export interface SysDictResponse {
  /** 字典分类 */
  classify?: string;
  /** 字典码 */
  code?: string;
  /** 字典值 */
  dictKey?: string;
  /** 字典名称 */
  dictName?: string;
  /** id */
  id?: string;
  /** 父类id */
  parentId?: string;
  /** 备注 */
  remark?: string;
  /** 排序 */
  sort?: number;
}
