/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysDynamicExcelLineResponse } from './sysDynamicExcelLineResponse';
import type { SysDynamicExcelRowResponse } from './sysDynamicExcelRowResponse';

/**
 * 动态表格
 */
export interface SysDynamicExcelResponse {
  /** 编码 */
  code?: string;
  /** 创建时间 */
  createTime?: string;
  /** id */
  id?: string;
  /** 动态表格行信息 */
  lineList?: SysDynamicExcelLineResponse[];
  /** 名字 */
  name?: string;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 备注 */
  remark?: string;
  /** 动态表格列信息 */
  rowList?: SysDynamicExcelRowResponse[];
  /** 状态 */
  status?: string;
  /** 修改时间 */
  updateTime?: string;
}
