/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysDynamicFormModelRegularEditRequest } from './sysDynamicFormModelRegularEditRequest';

/**
 * 动态表单模型-字段,编辑表单对象模型
 */
export interface SysDynamicFormModelFieldEditRequest {
  /** 居中对齐：center 左对齐：left 右对齐：right */
  alineType?: string;
  /** 能否清空  1：是 0：否 */
  allowClear?: boolean;
  /** 列注释标题 */
  columnComment?: string;
  /** 列定义字段 英文 */
  columnDefine?: string;
  /** 组件类型 */
  columnType?: string;
  /** 组件宽度 */
  compentWidth?: number;
  /** 数据字典 */
  dataSource?: string;
  /** 默认值 */
  defaultValue?: string;
  /** 是否禁用 1：是 0：否 */
  disabled?: boolean;
  /** 上传组件 按钮文字 */
  fileButtonName?: string;
  /** 上传组件 文件大小 */
  fileMaxSize?: number;
  /** 表单栅格 */
  formColumn?: number;
  /** 是否高亮 */
  isHighlight?: boolean;
  /** 是否显示 1：是  0：否 */
  isShow?: boolean;
  /** 是否显示标签 1：是 0：否 */
  isShowLabel?: boolean;
  /** 是否合计 1：是 0：否 */
  isSum?: boolean;
  /** 标签宽度 */
  labelWidth?: number;
  /** 多行文本组件 最多输入多少个字符 */
  maxLength?: number;
  /** 占位提示 */
  placeholder?: string;
  /** 是否只读 1：是 0：否 */
  readOnly?: boolean;
  /** 正则详细配置 */
  regexs?: SysDynamicFormModelRegularEditRequest[];
  /** 备注 */
  remark?: string;
  /** 是否必填 1：是  0：否 */
  required?: boolean;
  /** 是否输入统计 1：是 0：否 */
  showCount?: boolean;
  /** 排序 */
  sort?: number;
}
