/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * Excel模板导入配置表,编辑表单模型
 */
export interface SysExcelTemplateImportEditRequest {
  /** 列注释说明 */
  columnComment: string;
  /** 列定义 */
  columnDefine: string;
  /** Excel列名 */
  excelColumnTitle?: string;
  /** 关联类型 无关联、GUID、数据字典、固定值、登陆人code、登陆人id，登陆人name、登录组织id、登录组织code、登录组织名称、导入时间 */
  excelRelationType: string;
  /** 关联数据字典 */
  relationDataSource?: string;
  /** 关联固定值 */
  relationFixedValue?: string;
  /** 备注 */
  remark?: string;
}
