/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysExcelTemplateImportResponse } from './sysExcelTemplateImportResponse';

/**
 * Excel模板配置表
 */
export interface SysExcelTemplateResponse {
  /** 按钮code，多个按钮以，分割 */
  btnCode?: string;
  /** 按钮名称 */
  btnName?: string;
  /** 当是导入配置时的详细配置 */
  configs?: SysExcelTemplateImportResponse[];
  /** 创建时间 */
  createTime?: string;
  /** 配置数据源，多个以，分割 */
  excelModuleCode?: string;
  /** 模板资源ID */
  excelResourceId?: string;
  /** 模板类型：placeholder ：占位符 columnMatch：列匹配 */
  exportTemplateType?: string;
  /** 模板资源ID(OSS) */
  fileId?: string;
  /** 模板名称 */
  fileName?: string;
  /** 模板资源Url */
  fileUrl?: string;
  /** id */
  id?: string;
  /** 导入错误机制 ：skip：跳过 abort：终止 */
  importErrorHandle?: string;
  /** 菜单code */
  menuCode?: string;
  /** 菜单ID */
  menuId?: string;
  /** 菜单名称 */
  menuName?: string;
  /** 模块code */
  moduleCode?: string;
  /** 模块名称 */
  moduleName?: string;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 备注 */
  remark?: string;
  /** 状态 {enable:启用,disable:禁用,cancel:注销|删除} */
  status?: string;
  /** 状态 {enable:启用,disable:禁用,cancel:注销|删除} */
  statusCn?: string;
  /** 模版名称 */
  templateName?: string;
  /** 修改时间 */
  updateTime?: string;
}
