/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 员工表,查询对象模型
 */
export interface SysEmployeeListQueryRequest {
  /** 员工code */
  code?: string;
  /** 关键字查询 */
  keyWords?: string;
  /** 组织id */
  orgId?: string;
  /** 员工所属{admin厂商,service_provide渠道商,retailer零售商} */
  type?: string;
}
