/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * Excel模板配置表,编辑表单模型
 */
export interface SysExcelTemplateExportAddOrEditRequest {
  /** 按钮code，多个按钮以，分割 */
  btnCode: string;
  /** 配置数据源，多个以，分割 */
  excelModuleCode?: string;
  /** 模板类型：placeholder ：占位符 columnMatch：列匹配 */
  exportTemplateType?: string;
  /** 导出模板资源ID */
  fileId: string;
  /** 类型,import：导入 export：导出 print：打印 */
  functionType: string;
  /** id */
  id?: string;
  /** 菜单ID */
  menuId: string;
  /** 模块code */
  moduleCode?: string;
  /** 模块名称 */
  moduleName?: string;
  /** 备注 */
  remark?: string;
  /** 模版名称 */
  templateName: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
