/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 账户类型:{AccountTypeEnum}
 */
export type SysEmployeeEditRequestAccountTypeEnum = typeof SysEmployeeEditRequestAccountTypeEnum[keyof typeof SysEmployeeEditRequestAccountTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SysEmployeeEditRequestAccountTypeEnum = {
  EMPLOYEE: 'EMPLOYEE',
  MERCHANT: 'MERCHANT',
  MERCHANT_ADMIN: 'MERCHANT_ADMIN',
  OTHER: 'OTHER',
  RETAIL_ADMIN: 'RETAIL_ADMIN',
  STORE_ADMIN: 'STORE_ADMIN',
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
} as const;
