/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 用户自定义查询方案入库配置
 */
export interface SysFunAttributeQueryUserConfigsInDbRequest {
  /** 列注释 */
  columnComment: string;
  /** 列名 */
  columnDefine: string;
  /** 字段类型 */
  columnType?: string;
  /** 条件 > .=  包含 */
  conditions?: string;
  /** 字段字典 */
  dataSource?: string;
  /** 默认值 */
  defaultValue?: string;
  /** 逻辑 and or */
  logic?: string;
}
