/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * ,编辑表单模型
 */
export interface SysFunAttributeMainColorEditRequest {
  /** 高亮颜色 */
  highlightColor?: string;
  /** 高亮匹配条件 >、<、包含、不包含、＝等 */
  highlightCondition?: string;
  /** 高亮匹配值 */
  highlightValue?: string;
}
