/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 用户查询方案明细配置,查询表单模型
 */
export interface SysFunAttributeQueryUserQueryRequest {
  /** 菜单编码 */
  menuCode: string;
  /** 查询方案ID,查询系统默认时 传-1 */
  queryId: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
