/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysFunAttributeMainColorEditRequest } from './sysFunAttributeMainColorEditRequest';

/**
 * 主子表列表配置，添加表单模型
 */
export interface SysFunAttributeListInDbRequest {
  /** 居中对齐：center 左对齐：left 右对齐：right，这里返回英文 */
  alineType: string;
  /** 列名 */
  columnComment: string;
  /** 列定义字段 */
  columnDefine: string;
  /** 列宽 */
  columnWidth?: number;
  /** 高亮颜色条件配置 */
  highlightConfigs?: SysFunAttributeMainColorEditRequest[];
  /** true：高亮  false： 不高亮 */
  highlightIsRow: boolean;
  /** true：高亮  false： 不高亮 */
  isHighlight: boolean;
  /** true: 显示  false：不显示 */
  isShow: boolean;
  /** true：需要合计  false： 不需要合计 */
  isSum: boolean;
}
