/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysFunAttributeDetailInDbRequest } from './sysFunAttributeDetailInDbRequest';

/**
 * 主子表明细配置，添加、编辑表单模型
 */
export interface SysFunAttributeDetailAddOrEditRequest {
  /** 详细配置 */
  children?: SysFunAttributeDetailInDbRequest[];
  /** 主配置 */
  main?: SysFunAttributeDetailInDbRequest;
  /** 菜单编码 */
  menuCode: string;
  /** 菜单名称 */
  menuName: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
