/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysFunAttributeDetailColorResponse } from './sysFunAttributeDetailColorResponse';
import type { SysFunAttributeDetailRegularResponse } from './sysFunAttributeDetailRegularResponse';

/**
 * 明细配置
 */
export interface SysFunAttributeDetailConfigResponse {
  /** 居中对齐：center 左对齐：left 右对齐：right */
  alineType?: string;
  /** 能否清空  true：是 false：否 */
  allowClear?: boolean;
  /** 列注释标题 */
  columnComment?: string;
  /** 列定义字段 英文 */
  columnDefine?: string;
  /** 组件类型 */
  columnType?: string;
  /** 组件宽度 */
  compentWidth?: number;
  /** 数据字典 */
  dataSource?: string;
  /** 日期组件 时间格式 yyyy-MM */
  dateFormat?: string;
  /** 日期组件 时间类型 datetimerange  datetime  date  week month year */
  datePicker?: string;
  /** 日期组件 分隔符 */
  dateSplit?: string;
  /** 默认值 */
  defaultValue?: string;
  /** 是否禁用 true：是 false：否 */
  disabled?: boolean;
  /** 上传组件 按钮文字 */
  fileButtonName?: string;
  /** 上传组件 文件大小 */
  fileMaxSize?: number;
  /** 上传组件 文件类型 以逗号分隔 */
  fileType?: string;
  /** 表单栅格 */
  formColumn?: number;
  /** 高亮颜色配置 */
  highlightConfigs?: SysFunAttributeDetailColorResponse[];
  /** 是否支持行级：1：是  0：否 */
  highlightIsRow?: boolean;
  /** 是否高亮 */
  isHighlight?: boolean;
  /** 是否显示 true：是  false：否 */
  isShow?: boolean;
  /** 是否显示标签 true：是 false：否 */
  isShowLabel?: boolean;
  /** true：需要合计  false： 不需要合计 */
  isSum?: boolean;
  /** 标签宽度 */
  labelWidth?: number;
  /** 多行文本组件 最多输入多少个字符 */
  maxLength?: number;
  /** 多行文本组件 最大行数 */
  maxRows?: number;
  /** 数字允许最大值 */
  maxValue?: number;
  /** 多行文本组件 最小行数 */
  minRows?: number;
  /** 数字允许最小值 */
  minValue?: number;
  /** true：多选 false：不多选 */
  multiple?: boolean;
  /** 占位提示 */
  placeholder?: string;
  /** 小数位数 */
  precisions?: number;
  /** 是否只读 true：是 false：否 */
  readOnly?: boolean;
  /** 正则详细配置 */
  regexs?: SysFunAttributeDetailRegularResponse[];
  /** 是否必填 true：是  false：否 */
  required?: boolean;
  /** 是否输入统计 true：是 false：否 */
  showCount?: boolean;
  /** true:能搜索  false：不能搜索 */
  showSearch?: boolean;
  /** 排序 */
  sort?: number;
}
