/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 列表字段配置
 */
export interface SysFunAttributeMainQueryConfigsResponse {
  /** 列注释 */
  columnComment?: string;
  /** 列名 */
  columnDefine?: string;
  /** 字段类型 */
  columnType?: string;
  /** 字段字典 */
  dataSource?: string;
  /** 默认值 */
  defaultValue?: string;
  /** 是否禁用  true：是 false：否 */
  disabled?: boolean;
  /** 是否通用查询 true：是  false：否 */
  isCommon?: boolean;
  /** 排序 */
  sort?: number;
}
