/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysFunAttributeQueryUserConfigsInDbRequest } from './sysFunAttributeQueryUserConfigsInDbRequest';

/**
 * 用户自定义查询方案添加、编辑表单模型
 */
export interface SysFunAttributeQueryUserAddOrEditRequest {
  /** 详细配置 */
  configs?: SysFunAttributeQueryUserConfigsInDbRequest[];
  /** 是否保持在最前 */
  isKeepFirst?: boolean;
  /** 菜单编码 */
  menuCode: string;
  /** 菜单名称 */
  menuName: string;
  /** queryId */
  queryId?: string;
  /** 查询方案名称 */
  queryName?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
