/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysFunAttributeMainQueryConfigsResponse } from './sysFunAttributeMainQueryConfigsResponse';

/**
 * 列表字段配置
 */
export interface SysFunAttributeMainQueryResponse {
  /** 详细配置 */
  configs?: SysFunAttributeMainQueryConfigsResponse[];
}
