/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysFunAttributeListInDbRequest } from './sysFunAttributeListInDbRequest';

/**
 * 主子表列表配置，添加、编辑表单模型
 */
export interface SysFunAttributeAddOrEditRequest {
  /** 列表数据 */
  configs: SysFunAttributeListInDbRequest[];
  /** 是否分页（true:分页，false：不分页） */
  isPage: boolean;
  /** 菜单编码 */
  menuCode: string;
  /** 菜单名称 */
  menuName: string;
  /** 查询布局方式：popout  弹框，list   查询列输入框 */
  queryLayout?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
