/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 主表明细字段正则校验入库配置
 */
export interface SysFunAttributeDetailRegularEditRequest {
  /** 错误提示 */
  message?: string;
  /** 正则校验  规则表达式 */
  rule?: string;
}
