/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 从表基础配置，添加、编辑表单模型
 */
export interface SysGenSonBasicInfoEditRequest {
  /** 主表关联字段 */
  relationMainColumn: string;
  /** 子表关联字段 */
  relationSonColumn: string;
  /** 主表说明 */
  tableMainComment?: string;
  /** 主表名称 */
  tableMainName: string;
  /** 子表说明 */
  tableSonComment?: string;
  /** 子表名称 */
  tableSonName: string;
}
