/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 主表基础配置，添加、编辑表单模型
 */
export interface SysGenMainBasicInfoEditRequest {
  /** 表说明 */
  tableMainComment: string;
  /** 表名 */
  tableMainName: string;
}
