/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 系统日志表
 */
export interface SysLogResponse {
  /** 浏览器 */
  browseName?: string;
  /** 创建时间 */
  createTime?: string;
  /** 设备名称 */
  deviceName?: string;
  /** 错误信息 */
  errorMsg?: string;
  /** 系统功能 */
  functionName?: string;
  /** gid */
  gid?: string;
  /** id */
  id?: string;
  /** IP地址 */
  ip?: string;
  /** login:登陆日志 oper：操作日志 exception：异常日志 */
  logType?: string;
  /** 公司code */
  operCompanyCode?: string;
  /** 部门code */
  operDeptCode?: string;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 接收时间 */
  receiveTime?: string;
  /** 备注 */
  remark?: string;
  /** 请求方法 get post */
  requestMethod?: string;
  /** 请求参数 */
  requestParams?: string;
  /** 请求地址 */
  requestUrl?: string;
  /** 响应间隔时间 单位毫秒 */
  responseInterval?: number;
  /** 响应时间 */
  responseTime?: string;
  /** {init:初始化,processing:进行中,success:成功,fail:失败,over_time:认证过期,enable:启用,disable:禁用,lock:锁定,cancel:注销|删除} */
  status?: string;
  /** 修改时间 */
  updateTime?: string;
  /** 用户代理 */
  userAgent?: string;
}
