/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 系统菜单表,查询表单模型
 */
export interface SysMenuQuerySonRequest {
  /** 关键字 */
  keyWord?: string;
  /** 父级菜单ID */
  parentId?: string;
  /** 所属系统 */
  system?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** 菜单类型{menu:菜单,button:按钮} */
  type?: string;
}
