/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 系统菜单表,查询表单模型
 */
export interface SysMenuQueryPageRequest {
  /** 别名 */
  alias?: string;
  /** 编码 */
  code?: string;
  /** codes */
  codes?: string[];
  /** id */
  id?: string;
  /** 属性维护;{0否，1是} */
  isAttributeSet?: string;
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 关键字 */
  keyWord?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 父级菜单id */
  parentId?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 状态 */
  status?: string;
  /** 所属系统,不传则查所有 */
  system?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** 菜单类型 */
  type?: string;
}
