/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 系统菜单表
 */
export interface SysMenuResponse {
  /** 菜单英文别名(用于生成编号前缀) */
  alias?: string;
  /** 菜单编号(编号规则生成) */
  code?: string;
  /** 创建时间 */
  createTime?: string;
  /** 菜单图标 */
  icon?: string;
  /** id */
  id?: string;
  /** 属性是否可维护 true：是 false：否 */
  isAttributeSet?: boolean;
  /** 菜单名称(类型是按钮时则是按钮名称，类型是模块时存放module_name) */
  name?: string;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 父级菜单编号 */
  parentCode?: string;
  /** 父级菜单id */
  parentId?: string;
  /** 父级菜单 */
  parentName?: string;
  /** 父级菜单Path */
  parentPath?: string;
  /** 请求地址（当类型是模块时存放module_code） */
  path?: string;
  /** 地址类型{route:路由地址,url:外部url,button:按钮,module_code:按钮所属模块} */
  pathType?: string;
  /** 地址类型{route:路由地址,url:外部url,button:按钮,module_code:按钮所属模块} */
  pathTypeCn?: string;
  /** 备注 */
  remark?: string;
  /** 显示位置{不显示noshow，顶部top，左边left，顶部左边topleft} */
  showPosition?: string;
  /** 排序 */
  sort?: number;
  /** 状态StatusDeFultEnum{init:初始化,enable:启用,disable:禁用,lock:锁定,cancel:注销|删除} */
  status?: string;
  system?: string;
  /** 目标{addTabPage:页签栏,_blank:新开窗口} */
  target?: string;
  /** 目标{addTabPage:页签栏,_blank:新开窗口} */
  targetCn?: string;
  /** 菜单类型{menu:菜单,button:按钮,module_code:按钮所属模块} */
  type?: string;
  /** 菜单类型{menu:菜单,button:按钮,module_code:按钮所属模块} */
  typeCn?: string;
  /** 修改时间 */
  updateTime?: string;
}
