/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 组织架构表,返回对象模型
 */
export interface SysOrganizationResponse {
  /** 组织生效时间 */
  beginDate?: string;
  /** 组织建立时间 */
  builderDate?: string;
  /** 机构编码 */
  code?: string;
  /** 创建时间 */
  createTime?: string;
  /** 数据来源 */
  dataSource?: string;
  /** 数据来源（中文翻译） */
  dataSourceDesc?: string;
  /** 组织失效日期 */
  destroyDate?: string;
  /** id */
  id?: string;
  /** 机构全称 */
  name?: string;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 父级编号 */
  parentCode?: string;
  /** 父级ID */
  parentId?: string;
  /** 父级名称 */
  parentName?: string;
  /** 父级类型 */
  parentType?: string;
  /** 拼音全称 */
  pinyin?: string;
  /** 拼音简称 */
  py?: string;
  /** 备注 */
  remark?: string;
  /** SAP组织机构类型;{公司:company,部门:dept,销售组织:salesOrg,销售大区:salesRegion,岗位:post} */
  sapType?: string;
  /** 状态中文翻译 */
  sapTypeDesc?: string;
  /** 机构简称 */
  shortName?: string;
  /** 本级排序号（升序） */
  sort?: number;
  /** 状态;{init:初始化,processing:进行中,success:成功,fail:失败,over_time:认证过期,enable:启用,disable:禁用,lock:锁定,cancel:注销|delete删除} */
  status?: string;
  /** 状态中文翻译 */
  statusDesc?: string;
  /** 组织类型;{公司:company,部门:dept,销售组织:salesOrg,销售大区:salesRegion,岗位:post} */
  type?: string;
  /** 状态中文翻译 */
  typeDesc?: string;
  /** 修改时间 */
  updateTime?: string;
}
