/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 组织架构表,查询对象模型
 */
export interface SysOrganizationQueryRequest {
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 是否查询父级数据 */
  isQueryParent?: boolean;
  /** 名称 */
  name?: string;
  /** 排除类 */
  notType?: string;
  /** 父级id */
  orgId?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 父级id */
  parentId?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 状态 */
  status?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** 组织类型;枚举SysOrganizationTypeEnum{公司:company,部门:dept,销售组织:salesOrg,销售大区:salesRegion,经销商:merchant} */
  type?: string;
}
