/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysPostResponse } from './sysPostResponse';
import type { SysOrganizationTreeResponseId } from './sysOrganizationTreeResponseId';

/**
 * 组织机构表
 */
export interface SysOrganizationTreeResponse {
  /** 岗位集合 */
  children?: SysPostResponse[];
  /** 机构编码 */
  code?: string;
  /** id */
  id?: SysOrganizationTreeResponseId;
  /** 机构全称 */
  name?: string;
  /** 父级ID */
  parentId?: string;
  /** 拼音全称 */
  pinyin?: string;
  /** 拼音简称 */
  py?: string;
  /** 组织类型;{公司:company,部门:dept,销售组织:salesOrg,销售大区:salesRegion,经销商:merchant} */
  type?: string;
}
