/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 组织架构表,编辑表单对象模型
 */
export interface SysOrganizationEditRequest {
  /** 来源（自定义=营销平台）{SAP:SAP,营销平台:MMS} */
  dataSource?: string;
  /** id */
  id?: string;
  /** 机构全称 */
  name?: string;
  /** 父级ID */
  parentId?: string;
  /** sap节点id(主键id) */
  sapOrgId?: string;
  /** 机构简称 */
  shortName?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** 组织类型;{集团group,公司:company,部门:dept,销售组织:salesOrg,销售大区:salesRegion,经销商:merchant} */
  type?: string;
}
