/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 岗位表_职位,返回对象模型
 */
export interface SysPostResponse {
  /** 岗位编码 */
  code?: string;
  /** 创建时间 */
  createTime?: string;
  /** id */
  id?: string;
  /** 岗位名称 */
  name?: string;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 组织机构编码 */
  orgCode?: string;
  /** 组织机构ID */
  orgId?: string;
  /** 组织机构名称 */
  orgName?: string;
  /** 父级岗位编码 */
  parentCode?: string;
  /** 父级岗位ID */
  parentId?: string;
  /** 父级岗位名称 */
  parentName?: string;
  /** 备注 */
  remark?: string;
  /** 状态;{init:初始化,processing:进行中,success:成功,fail:失败,over_time:认证过期,enable:启用,disable:禁用,lock:锁定,cancel:注销|删除} */
  status?: string;
  /** 状态中文翻译 */
  statusDesc?: string;
  /** 修改时间 */
  updateTime?: string;
}
