/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 岗位表_职位,编辑表单对象模型
 */
export interface SysPostEditRequest {
  /** 岗位编码 */
  code?: string;
  /** id */
  id?: string;
  /** 岗位名称 */
  name?: string;
  /** 组织机构ID */
  orgId?: string;
  /** 父级岗位ID */
  parentId?: string;
  /** 备注 */
  remark?: string;
  /** 状态;{init:初始化,processing:进行中,success:成功,fail:失败,over_time:认证过期,enable:启用,disable:禁用,lock:锁定,cancel:注销|删除} */
  status?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
