/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysRoleDataScopeDetailEditRequest } from './sysRoleDataScopeDetailEditRequest';

/**
 * 角色数据_权限_数据_关联表,编辑表单模型
 */
export interface SysRoleDataScopeEditRequest {
  /** 数据权限code */
  dataCode?: string;
  /** 数据权限id */
  dataId?: string;
  /** 数据权限name */
  dataName?: string;
  /** 数据权限明细详情 */
  roleDataScopeDetails?: SysRoleDataScopeDetailEditRequest[];
  /** 类型{字典dic，大区salesRegion，业务助理assistant} */
  type?: string;
}
