/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 系统角色功能权限,详情表单模型
 */
export interface SysRoleMenuDetailResponse {
  /** 菜单英文别名(用于生成编号前缀) */
  alias?: string;
  /** 菜单图标 */
  icon?: string;
  /** 属性是否可维护 true：是 false：否 */
  isAttributeSet?: boolean;
  /** 菜单编码 */
  menuCode: string;
  /** 菜单ID */
  menuId: string;
  /** 菜单名称 */
  menuName: string;
  /** 菜单类型;{菜单：menu,按钮：button} */
  menuType: string;
  /** 父级菜单编号 */
  parentCode?: string;
  /** 父级id */
  parentId?: string;
  /** 请求地址（当类型是模块时存放module_code） */
  path?: string;
  /** 地址类型{route:路由地址,url:外部url,button:按钮,module_code:按钮所属模块} */
  pathType?: string;
  /** 地址类型{route:路由地址,url:外部url,button:按钮,module_code:按钮所属模块} */
  pathTypeCn?: string;
  /** 显示位置{不显示noshow，顶部top，左边left，顶部左边topleft} */
  showPosition?: string;
  /** sort */
  sort?: number;
  /** 所属系统 */
  system?: string;
  /** 目标{addTabPage:页签栏,_blank:新开窗口} */
  target?: string;
}
