/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 数据权限配置详情,编辑表单对象模型
 */
export interface SysRoleDataScopeDetailEditRequest {
  /** id */
  id?: string;
  /** 是否可见价格,true可见，false不可见 */
  isShowPrice?: boolean;
  /** 产品code */
  productCode?: string;
  /** 产品名称 */
  productName?: string;
  /** 备注 */
  remark?: string;
  /** 角色id */
  roleId?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** 数据类型(门店store、仓库warehouse、销售组织salesOrg) */
  type?: string;
  /** 对应数据类型code(门店code，仓库code，销售组织code) */
  typeDataCode?: string;
  /** 对应数据类型id(门店id，仓库id，销售组织id) */
  typeDataId?: string;
  /** 对应数据类型名称(XX门店，XX仓库，XX组织) */
  typeDataName?: string;
}
