/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysRoleColumnDetailResponse } from './sysRoleColumnDetailResponse';

/**
 * 员工组织表,返回对象模型
 */
export interface SysRoleColumnMenuResponse {
  /** 创建时间 */
  createTime?: string;
  /** 系统账户id */
  datas?: SysRoleColumnDetailResponse[];
  /** id */
  id?: string;
  /** 是否为超管 */
  isAmin?: boolean;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 修改时间 */
  updateTime?: string;
}
