/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 系统角色表,查询表单模型
 */
export interface SysRoleQueryRequest {
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 经销商code */
  merchantCode?: string;
  /** 角色名称 */
  name?: string;
  /** 页码(默认值:1) */
  page?: number;
  /** 岗位ID */
  postId?: string;
  /** 角色分类ID */
  roleClassfiyId?: string;
  /** 角色类型 */
  roleType?: string;
  /** 页量(默认值:10) */
  size?: number;
  /** 状态 */
  status?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
