/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 角色数据_权限_数据_关联表,详情表单模型
 */
export interface SysRoleDataScopeResponse {
  /** 父级id */
  children?: SysRoleDataScopeResponse[];
  /** 创建时间 */
  createTime?: string;
  /** 数据权限code */
  dataCode?: string;
  /** 数据权限id */
  dataId?: string;
  /** 数据权限name */
  dataName?: string;
  /** 数据权限key */
  dataScopeKey?: string;
  /** 数据权限name */
  dataScopeName?: string;
  /** id */
  id?: string;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 类型{字典dic，大区salesRegion，业务助理assistant} */
  type?: string;
  /** 修改时间 */
  updateTime?: string;
}
