/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 数据权限配置详情,返回对象模型
 */
export interface SysRoleDataScopeDetailResponse {
  /** 创建时间 */
  createTime?: string;
  /** id */
  id?: string;
  /** 是否可见价格,true可见，false不可见 */
  isShowPrice?: boolean;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 产品code */
  productCode?: string;
  /** 产品id */
  productId?: string;
  /** 产品名称 */
  productName?: string;
  /** 备注 */
  remark?: string;
  /** 角色id */
  roleId?: string;
  /** 销售组织编码 */
  saleOrgCode?: string;
  /** 销售组织ID */
  saleOrgId?: string;
  /** 销售组织名称 */
  saleOrgName?: string;
  /** 数据类型(门店store、仓库warehouse、销售组织salesOrg) */
  type?: string;
  /** 对应数据类型id(门店id，仓库id，销售组织id) */
  typeDataCode?: string;
  /** 对应数据类型id(门店id，仓库id，销售组织id) */
  typeDataId?: string;
  /** 对应数据类型名称(XX门店，XX仓库，XX组织) */
  typeDataName?: string;
  /** 修改时间 */
  updateTime?: string;
}
