/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 系统角色表
 */
export interface SysRoleResponse {
  /** 角色编码 */
  code?: string;
  /** 创建时间 */
  createTime?: string;
  /** 创建途径(系统默认/手动创建) */
  createType?: string;
  /** 角色 关联的 员工code */
  empCodes?: string[];
  /** id */
  id?: string;
  /** 角色名称 */
  name?: string;
  /** 人数 */
  num?: number;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 角色所属机构code */
  orgCode?: string;
  /** 角色所属机构id */
  orgId?: string;
  /** 岗位编码 */
  postCode?: string;
  /** 岗位ID */
  postId?: string;
  /** 岗位名称 */
  postName?: string;
  /** 备注 */
  remark?: string;
  /** 角色分类ID */
  roleClassfiyId?: string;
  /** 角色分类名称 */
  roleClassfiyName?: string;
  /** 角色分类备注 */
  roleClassfiyRemark?: string;
  /** 角色类型;{超级管理员:superAdmin、内置角色:inner、普通角色:common} */
  roleType?: string;
  /** 角色类型中文翻译 */
  roleTypeDesc?: string;
  /** 修改时间 */
  updateTime?: string;
}
