/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 系统角色表-删除响应模型
 */
export interface SysRoleDeleteResponse {
  /** 创建时间 */
  createTime?: string;
  /** 是否删除成功(true成功，false失败) */
  flag?: boolean;
  /** id */
  id?: string;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 角色名称 */
  roleNames?: string[];
  /** 修改时间 */
  updateTime?: string;
}
