/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysRoleColumnEditRequest } from './sysRoleColumnEditRequest';
import type { SysRoleDataScopeEditRequest } from './sysRoleDataScopeEditRequest';
import type { SysRoleMenuEditRequest } from './sysRoleMenuEditRequest';

/**
 * 系统角色权限 ,编辑表单模型
 */
export interface SysRolePermissTreeEditRequest {
  /** 角色code,必填 */
  roleCode: string;
  /** 字段权限集合 */
  roleColumns?: SysRoleColumnEditRequest[];
  /** 数据权限集合 */
  roleDataScopes?: SysRoleDataScopeEditRequest[];
  /** 角色id,必填 */
  roleId: string;
  /** 功能权限集合 */
  roleMenus?: SysRoleMenuEditRequest[];
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
