/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 角色分类表
 */
export interface SysRoleClassfiyResponse {
  /** 角色分类code */
  code?: string;
  /** 创建时间 */
  createTime?: string;
  /** id */
  id?: string;
  /** 角色分类名称 */
  name?: string;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 备注 */
  remark?: string;
  /** 修改时间 */
  updateTime?: string;
}
