/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysRoleColumnDetailResponse } from './sysRoleColumnDetailResponse';
import type { SysRoleDataScopeDetailResponse } from './sysRoleDataScopeDetailResponse';
import type { SysRoleDataScopeResponse } from './sysRoleDataScopeResponse';
import type { SysRoleMenuDetailResponse } from './sysRoleMenuDetailResponse';

/**
 * 系统角色表,详情表单模型
 */
export interface SysRoleDetailResponse {
  /** 角色生效时间 */
  beginDate?: string;
  /** 角色失效时间 */
  endDate?: string;
  /** id,编辑时必填 */
  id?: string;
  /** 角色名称 */
  name: string;
  /** 角色所属机构编码(SAP) */
  orgCode?: string;
  /** 角色所属机构ID */
  orgId?: string;
  /** 岗位编码 */
  postCode?: string;
  /** 岗位ID */
  postId?: string;
  /** 岗位名称 */
  postName?: string;
  /** 备注 */
  remark?: string;
  /** 角色分类ID */
  roleClassfiyId?: string;
  /** 角色分类名称 */
  roleClassfiyName?: string;
  /** 角色分类备注 */
  roleClassfiyRemark?: string;
  /** 字段权限集合 */
  roleColumns?: SysRoleColumnDetailResponse[];
  /** 数据权限集合-精细权限 */
  roleDataDetailScopes?: SysRoleDataScopeDetailResponse[];
  /** 数据权限集合 */
  roleDataScopes?: SysRoleDataScopeResponse[];
  roleDesc?: string;
  /** 功能权限集合 */
  roleMenus?: SysRoleMenuDetailResponse[];
  /** 角色类型;,这里传递英文 */
  roleType?: string;
  /** 角色类型;,这里传递英文 */
  roleTypeDesc?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
