/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 角色菜单字段_权限关联表,编辑表单模型
 */
export interface SysRoleColumnEditRequest {
  /** 列描述 */
  columnComment?: string;
  /** 列定义 */
  columnDefine?: string;
  /** 菜单编码 */
  menuCode?: string;
  /** 菜单ID */
  menuId?: string;
  /** 模块编码 */
  moduleCode?: string;
  /** 模块名称 */
  moduleName?: string;
}
