/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 系统角色功能权限,编辑表单模型
 */
export interface SysRoleMenuEditRequest {
  /** 菜单编码 */
  menuCode: string;
  /** 菜单ID */
  menuId: string;
  /** 菜单名称 */
  menuName: string;
  /** 菜单类型;{菜单：menu,按钮：button} */
  menuType: string;
}
