/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 角色分类表,编辑表单模型
 */
export interface SysRoleClassfiyEditRequest {
  /** 角色分类code， 编辑时必填 */
  code?: string;
  /** id，编辑时必填 */
  id?: string;
  /** 角色分类名称 */
  name: string;
  /** 备注 */
  remark?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
