/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 系统角色表,编辑表单模型
 */
export interface SysRoleEditRequest {
  /** 角色生效时间 */
  beginDate?: string;
  /** 角色失效时间 */
  endDate?: string;
  /** id,编辑时必填 */
  id?: string;
  /** 角色名称 */
  name: string;
  /** 岗位ID */
  postId?: string;
  /** 备注 */
  remark?: string;
  /** 角色分类ID */
  roleClassfiyId?: string;
  /** 角色类型;{内置角色:inner、普通角色:common},这里传递英文 */
  roleType?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
