/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 角色分类表
 */
export interface SysRoleClassfiyDeleteResponse {
  /** 创建时间 */
  createTime?: string;
  /** 是否删除成功 */
  flag?: boolean;
  /** id */
  id?: string;
  /** 不能删除的数据id集合 */
  ids?: string[];
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 修改时间 */
  updateTime?: string;
}
