/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * SAP组织架构表,返回对象模型
 */
export interface SysSapOrganizationPullResponse {
  /** 编码 */
  orgCode?: string;
  /** 名称 */
  orgName?: string;
  /** 组织类型;{公司:company,部门:dept,销售组织:salesOrg,销售大区:salesRegion} */
  orgType?: string;
}
