/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { SysTableColumnInfoResponse } from './sysTableColumnInfoResponse';

/**
 * 数据库表信息
 */
export interface SysTableInfoResponse {
  /** 表字段信息 */
  columns?: SysTableColumnInfoResponse[];
  /** 默认Controller雷鸣 */
  controllerName?: string;
  /** 默认实体类名称 */
  entityName?: string;
  /** 默认Mapper类名 */
  mapperName?: string;
  /** 默认服务接口实现类命名 */
  serviceImplName?: string;
  /** 默认服务接口名 */
  serviceName?: string;
  /** 表注释 */
  tableComment?: string;
  /** 表名 */
  tableName?: string;
  /** 默认Xml文件名 */
  xmlName?: string;
}
