/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 数据库表字段信息
 */
export interface SysTableColumnInfoResponse {
  /** 列注释标题 */
  columnComment?: string;
  /** 数据库中字段类型 */
  columnDbType?: string;
  /** 列定义字段 英文 */
  columnDefine?: string;
  /** 组件类型 */
  columnType?: string;
  /** 属性名字 */
  propertyDefine?: string;
}
