/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface TemplateSonTableResponse {
  /** 代垫运费 */
  advancePayment?: number;
  /** 车型 */
  carModel?: string;
  /** 创建时间 */
  createTime?: string;
  /** 离岸价 */
  fobPrice?: number;
  /** 运费 */
  freight?: number;
  /** id */
  id?: string;
  /** 主表ID */
  masterTableId?: string;
  /** 物料编码 */
  materialCode?: string;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 数量 */
  quantity?: number;
  /** 备注 */
  remark?: string;
  /** 结算金额 */
  settleAmount?: number;
  /** 规格 */
  spec?: string;
  /** 1：正常 0：删除 */
  state?: boolean;
  /** 修改时间 */
  updateTime?: string;
}
