/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { TemplateSonSaveRequest } from './templateSonSaveRequest';

/**
 * 主子表数据保存
 */
export interface TemplateDataSaveRequest {
  /** 行政区域 */
  areaCode?: number;
  /** 账单时间 */
  billDate: string;
  /** 账单编号 */
  billNo: string;
  /** cancle 取消 enable 正常 */
  billStatus: string;
  /** 部门code */
  departmentId?: string;
  /** 部门名称 */
  departmentName?: string;
  /** 预计支付金额 */
  expectPayment: number;
  /** 文件资源id */
  fileResourceId?: string;
  /** id */
  id?: string;
  /** 期初金额 */
  initBalance: number;
  /** 物流费用 */
  logisticsFee: number;
  /** 操作日期 */
  operTime?: string;
  /** 操作人 */
  operUser?: string;
  /** 单据编码 */
  orderCode: string;
  /** 公司code */
  orgId?: string;
  /** 公司名称 */
  orgName?: string;
  /** 其他费用 */
  otherFee: number;
  /** 图片资源id */
  picResourceId?: string;
  /** 备注 */
  remark?: string;
  /** 明细表（子表数据） */
  sonSaveRequestList: TemplateSonSaveRequest[];
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
  /** 人员 */
  userId?: string;
  /** 用户名称 */
  userName?: string;
}
