/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * ,查询表单模型
 */
export interface TemplateMasterQuerySqlRequest {
  /** 列注释 */
  columnComment: string;
  /** 列名 */
  columnDefine: string;
  /** 字段类型 */
  columnType?: string;
  /** 值 */
  columnValue?: string;
  /** 条件 > .=  包含 */
  conditions?: string;
  /** 字段字典 */
  dataSource?: string;
  /** 逻辑 and or */
  logic?: string;
}
