/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface TemplateMasterTableResponse {
  /** 行政区域 */
  areaCode?: number;
  /** 账单时间 */
  billDate?: string;
  /** 账单编号 */
  billNo?: string;
  /** cancle 取消 enable 正常 */
  billStatus?: string;
  /** 创建时间 */
  createTime?: string;
  /** 部门code */
  departmentId?: string;
  /** 部门名称 */
  departmentName?: string;
  /** 预计支付金额 */
  expectPayment?: number;
  /** 文件资源id */
  fileResourceId?: string;
  /** id */
  id?: string;
  /** 期初金额 */
  initBalance?: number;
  /** 物流费用 */
  logisticsFee?: number;
  /** 操作人所在公司编码 */
  operCompanyCode?: string;
  /** 操作人所在部门编码 */
  operDeptCode?: string;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 单据编码 */
  orderCode: string;
  /** 公司code */
  orgId?: string;
  /** 公司名称 */
  orgName?: string;
  /** 其他费用 */
  otherFee?: number;
  /** 图片资源id */
  picResourceId?: string;
  /** 备注 */
  remark?: string;
  /** 1：正常 0：删除 */
  state?: boolean;
  /** 修改时间 */
  updateTime?: string;
  /** 人员 */
  userId?: string;
  /** 用户名称 */
  userName?: string;
}
