/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 子表保存模型
 */
export interface TemplateSonSaveRequest {
  /** 代垫运费 */
  advancePayment?: number;
  /** 车型 */
  carModel: string;
  /** 离岸价 */
  fobPrice: number;
  /** 运费 */
  freight: number;
  /** 物料编码 */
  materialCode?: string;
  /** 数量 */
  quantity: number;
  /** 结算金额 */
  settleAmount: number;
  /** 规格 */
  spec: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
