/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface TemplateSonOperationResponse {
  /** 创建时间 */
  createTime?: string;
  /** id */
  id?: string;
  /** 创建人员 */
  operIdCreate?: string;
  /** 修改人员 */
  operIdMod?: string;
  /** 创建人员 姓名 */
  operNameCreate?: string;
  /** 修改人员姓名 */
  operNameMod?: string;
  /** 操作时间 */
  operTime?: string;
  /** 操作人 */
  operUser?: string;
  /** 状态: 0 删除，1 正常 */
  state?: string;
  /** 修改时间 */
  updateTime?: string;
}
