/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * ,保存表单模型
 */
export interface TemplateSonOperationSaveRequest {
  /** id */
  id?: string;
  /** 操作时间 */
  operTime?: string;
  /** 操作人 */
  operUser?: string;
  /** 状态: delete 删除，enable 正常 */
  status?: string;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
