/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface UcRbacRoleDto {
  /** 角色所属三方用户code（当role_type是私有时有效） */
  belongCode?: string;
  /** 创建时间 */
  createTime?: string;
  /** 主键 */
  id?: string;
  /** 所选权限列表 */
  ids?: string[];
  /** 备注 */
  memo?: string;
  /** 角色编码 */
  name?: string;
  /** 角色类型 {BPULIC:‘共有’,PRIVATE:‘私有’} */
  roleType?: string;
  /** 角色名称 */
  title?: string;
  /** 修改时间 */
  updateTime?: string;
}
