/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 挂账单类型,FORWARD:购买挂账,REVERSE:退货挂账
 */
export type UnpaidBillPageQueryRequestSearchEQUnpaidBillsType = typeof UnpaidBillPageQueryRequestSearchEQUnpaidBillsType[keyof typeof UnpaidBillPageQueryRequestSearchEQUnpaidBillsType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UnpaidBillPageQueryRequestSearchEQUnpaidBillsType = {
  FORWARD: 'FORWARD',
  REVERSE: 'REVERSE',
} as const;
