/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 联合查询,默认为no,yes:是,no:否
 */
export type UnpaidBillPageQueryRequestSearchJointQuery = typeof UnpaidBillPageQueryRequestSearchJointQuery[keyof typeof UnpaidBillPageQueryRequestSearchJointQuery];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UnpaidBillPageQueryRequestSearchJointQuery = {
  no: 'no',
  yes: 'yes',
} as const;
