/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Money } from './money';
import type { 商品信息 } from './商品信息';
import type { UnpaidBillsLongAgreement } from './unpaidBillsLongAgreement';
import type { UnpaidBillsProductSettleMethod } from './unpaidBillsProductSettleMethod';
import type { UnpaidBillsStatus } from './unpaidBillsStatus';
import type { UnpaidBillsUnpaidBillsType } from './unpaidBillsUnpaidBillsType';

/**
 * 挂账单
 */
export interface UnpaidBills {
  agreementNo?: string;
  /** 挂账金额 */
  amount?: Money;
  billsGoodsAmount?: Money;
  busiOrderNo?: string;
  businessType?: string;
  /** 商品信息 */
  buyOrderLogisticsProductInfoList?: 商品信息[];
  /** 买家名称 */
  buyerName?: string;
  buyerNo: string;
  comments?: string;
  createTime?: string;
  freight?: Money;
  id?: string;
  /** null,yes:是,no:否 */
  longAgreement?: UnpaidBillsLongAgreement;
  /** 订单号 */
  orderNo?: string;
  /** null,BEFORE_PRODUCT:先货后款,BEFORE_PAY:先款后货 */
  productSettleMethod?: UnpaidBillsProductSettleMethod;
  purchaseOrderNo?: string;
  /** 收货单号 */
  receiptNo?: string;
  /** 退款编码 */
  refundNo?: string;
  /** 卖家名称 */
  sellerName?: string;
  sellerNo: string;
  settleNo?: string;
  /** 挂账状态,INIT:待生成对账单,DELETED:已删除,GENERATED_PAYMENT:已生成对账单,CLOSED:已关闭 */
  status?: UnpaidBillsStatus;
  unionOrderNo?: string;
  /** 挂账单号 */
  unpaidBillNo?: string;
  /** 挂账类型,FORWARD:购买挂账,REVERSE:退货挂账 */
  unpaidBillsType?: UnpaidBillsUnpaidBillsType;
  updateTime?: string;
}
