/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 挂账类型,FORWARD:购买挂账,REVERSE:退货挂账
 */
export type UnpaidBillsUnpaidBillsType = typeof UnpaidBillsUnpaidBillsType[keyof typeof UnpaidBillsUnpaidBillsType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UnpaidBillsUnpaidBillsType = {
  FORWARD: 'FORWARD',
  REVERSE: 'REVERSE',
} as const;
