/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * null,BEFORE_PRODUCT:先货后款,BEFORE_PAY:先款后货
 */
export type UnpaidBillsProductSettleMethod = typeof UnpaidBillsProductSettleMethod[keyof typeof UnpaidBillsProductSettleMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UnpaidBillsProductSettleMethod = {
  BEFORE_PAY: 'BEFORE_PAY',
  BEFORE_PRODUCT: 'BEFORE_PRODUCT',
} as const;
