/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { UnpaidBillPageQueryRequestSearchEQStatus } from './unpaidBillPageQueryRequestSearchEQStatus';
import type { UnpaidBillPageQueryRequestSearchEQUnpaidBillsType } from './unpaidBillPageQueryRequestSearchEQUnpaidBillsType';
import type { UnpaidBillPageQueryRequestSearchJointQuery } from './unpaidBillPageQueryRequestSearchJointQuery';

/**
 * 挂账单分页查询
 */
export interface UnpaidBillPageQueryRequest {
  /** 是否分页{特殊场景:可动态切换模式;默认:true;true-分页，false-不分页} */
  isPage?: boolean;
  /** 页码(默认值:1) */
  page?: number;
  /** 挂账单状态,INIT:初始化,DELETED:已删除,GENERATED_PAYMENT:已生成付款单,CANCLE:取消,CLOSED:已关闭 */
  search_EQ_status?: UnpaidBillPageQueryRequestSearchEQStatus;
  /** 挂账单类型,FORWARD:购买挂账,REVERSE:退货挂账 */
  search_EQ_unpaidBillsType?: UnpaidBillPageQueryRequestSearchEQUnpaidBillsType;
  /** 开始生成时间，请严格按照提供的示例时间格式传入精确到秒！！ */
  search_GTE_createTime?: string;
  /** 关联订单号 */
  search_LIKE_orderNo?: string;
  /** 关联退款单号 */
  search_LIKE_refundNo?: string;
  /** 挂账单号 */
  search_LIKE_unpaidBillNo?: string;
  /** 结束生成时间，请严格按照提供的示例时间格式传入精确到秒！！ */
  search_LTE_createTime?: string;
  /** 联合查询,默认为no,yes:是,no:否 */
  search_jointQuery?: UnpaidBillPageQueryRequestSearchJointQuery;
  /** 页量(默认值:10) */
  size?: number;
  /** 登录code,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserCode?: string;
  /** 登录tokenUserName,前端无需传,网关解析:接口生成已屏蔽 */
  tokenUserName?: string;
}
