/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface User {
  createTime?: string;
  descn?: string;
  email?: string;
  enabled?: boolean;
  expirationTime?: string;
  id?: string;
  lastModifyTime?: string;
  loginFailTimes?: number;
  loginStatus?: number;
  loginTime?: string;
  mobileNo?: string;
  orgId?: string;
  orgName?: string;
  pinyin?: string;
  realName?: string;
  roleName?: string;
  status?: number;
  unlockTime?: string;
  updateTime?: string;
  userType?: number;
  username: string;
}
