/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { Money } from './money';

export interface 商品信息 {
  comments?: string;
  diffNum?: number;
  diffType?: number;
  id?: string;
  orderNo?: string;
  productImg?: string;
  /** 商品名称 */
  productName?: string;
  /** 商品编号 */
  productNo?: string;
  /** 商品数量 */
  productNum?: number;
  /** 商品价格 */
  productPrice?: Money;
  productSpec?: string;
  productSurplusNum?: number;
  productUnit?: string;
  productUnitPrice?: Money;
  recNum?: number;
  sendNum?: number;
}
