/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 商品四级分类实体
 */
export interface 商品四级分类 {
  childId?: string;
  childName?: string;
  fourId?: string;
  fourName?: string;
  grandsonId?: string;
  grandsonName?: string;
  id?: string;
  name?: string;
}
