/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { 结算单SettleStatus } from './结算单SettleStatus';
import type { Money } from './money';

export interface 结算单 {
  /** 买家名称 */
  buyerName?: string;
  /** 买家编码 */
  buyerNo?: string;
  comments?: string;
  createTime?: string;
  id?: string;
  /** 子订单号 */
  orderNo?: string;
  /** 退款记录编码门,分割 */
  refundNos?: string;
  /** 卖家名称 */
  sellerName?: string;
  /** 卖家编码 */
  sellerNo?: string;
  /** 结算单号 */
  settleNo?: string;
  /** 结算状态,WAIT:待结算,PART:部分结算,SETTED:已结算,CLOSED:已关闭 */
  settleStatus?: 结算单SettleStatus;
  /** 已结算金额 */
  settledAmount?: Money;
  /** 订单总金额 */
  totalAmount?: Money;
  /** 订单号 */
  unionOrderNo?: string;
  updateTime?: string;
  waitForAmount?: Money;
}
