/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

export interface 营销活动审核记录实体 {
  /** 活动编码 */
  activityCode?: string;
  /** 活动价（单位：分） */
  activityPrice?: string;
  /** 活动起订量 */
  activityStartStock?: number;
  createTime?: string;
  id?: string;
  /** sku编码 */
  skuCode?: string;
  /** sku商品名称 */
  skuName?: string;
  updateTime?: string;
}
