/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 状态,TO_BE_REVIEW:待审核,FAIL:审核驳回,PASS_TO_BE_START:审核通过,待开始,IN_PROGRESS:进行中,CLOSED:结束
 */
export type 营销活动实体ActivityStatus = typeof 营销活动实体ActivityStatus[keyof typeof 营销活动实体ActivityStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const 营销活动实体ActivityStatus = {
  CLOSED: 'CLOSED',
  FAIL: 'FAIL',
  IN_PROGRESS: 'IN_PROGRESS',
  PASS_TO_BE_START: 'PASS_TO_BE_START',
  TO_BE_REVIEW: 'TO_BE_REVIEW',
} as const;
