/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */

/**
 * 审核状态,PASS_TO_BE_START:审核通过,FAIL:审核驳回
 */
export type 营销活动审核记录实体ResActivityReviewStatus = typeof 营销活动审核记录实体ResActivityReviewStatus[keyof typeof 营销活动审核记录实体ResActivityReviewStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const 营销活动审核记录实体ResActivityReviewStatus = {
  FAIL: 'FAIL',
  PASS_TO_BE_START: 'PASS_TO_BE_START',
} as const;
