/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { 营销活动审核记录实体ResActivityReviewStatus } from './营销活动审核记录实体ResActivityReviewStatus';

export interface 营销活动审核记录实体Res {
  /** 活动编码 */
  activityCode?: string;
  /** 审核状态,PASS_TO_BE_START:审核通过,FAIL:审核驳回 */
  activityReviewStatus?: 营销活动审核记录实体ResActivityReviewStatus;
  /** 审核状态描述 */
  activityReviewStatusStr?: string;
  /** 备注 */
  comments?: string;
  createTime?: string;
  id?: string;
  /** 操作员姓名 */
  realName?: string;
  updateTime?: string;
  /** 用户名 */
  username?: string;
}
