/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * 工业资源boss管理端【API接口文档】
 * 工业资源boss管理端
 */
import type { 营销活动实体ActivityStatus } from './营销活动实体ActivityStatus';

export interface 营销活动实体 {
  /** 活动编码 */
  activityCode?: string;
  /** 备注 */
  activityComments?: string;
  /** 活动规则 */
  activityContent?: string;
  /** 活动图片 */
  activityPic?: string;
  /** 审核驳回原因 */
  activityReviewFailReason?: string;
  /** 状态,TO_BE_REVIEW:待审核,FAIL:审核驳回,PASS_TO_BE_START:审核通过,待开始,IN_PROGRESS:进行中,CLOSED:结束 */
  activityStatus?: 营销活动实体ActivityStatus;
  /** 活动标题 */
  activityTitle?: string;
  /** 创建人 */
  author?: string;
  createTime?: string;
  /** 活动结束时间 */
  endTime?: string;
  id?: string;
  /** 是否删除（0-否，1-是） */
  isDelete?: number;
  /** 活动开始时间 */
  startTime?: string;
  /** 终端 0-PC */
  terminal?: number;
  updateTime?: string;
}
